### PR TITLE
Update build system to Java 7

### LINKED ISSUE #978: Upgrade to Java 7 minimum
Starting with Java 9, it appears the ai.javac5 ant task breaks because 1.5 is no longer supported by the javac compiler. We need to update the build system to use Java 7, which is the earliest supported Java language in the Java 9 compiler. This will also require testing the buildserver and components to make sure we don't break functionality after upgrading.

### PR DESCRIPTION
**Pull request by ewpatton**
Fixes #978

Change-Id: I50e4cf4df28e49189ac9f933e61cc44180ec27c1

### CODE REVIEW

**Comment by ewpatton** [comment]
The bulk of the work for this commit actually comes from the fact that I updated the dx.jar file to a version that understands the Java 7 classfile format. We still need to do some UAT for this, but as far as I know there shouldn't be any breaking changes introduced by updating Java 5 to Java 7.

**Comment by jisqyv** [comment]
Do we know how far back java 7 is supported on Android devices?

**Comment by ewpatton** [comment]
It looks like most features are supported all the way back to SDK 8. Try with resources requires SDK 19.

Via https://stackoverflow.com/questions/20480090/does-android-support-jdk-6-or-7

**Comment by jisqyv** [comment]
The important question, which I didn't see the answer to, is what version of the .class file format is supported. From what I can findout, the jre 7 format isn't supported until Lollipop, but I'm not sure.

**Comment by jisqyv** [comment]
Btw. I would mark #978 as a won't fix. To me it is much more important that we reliably support older devices then we support building with Java 9. Although this change is easy to make, I'm nervous about deploying it unless we test on *many* devices.

**Comment by halatmit** [comment]
I agree with Jeff.



== Hal

Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.

**Comment by ewpatton** [comment]
Which version of the class format is supported is controlled by dx, not by the Android version. The version of dx we use supports the Java 7 class file format.

**Comment by ewpatton** [comment]
Also note that the companion compiled with this patch runs in the current emulator, which is SDK level 7, and is the same as we are targeting in the next companion release.

**Comment by pavi2410** [comment]
I don't think there will any issue if we update the java version if we desugar the classes. With that, maybe we can use most Java 8 features even on older Android versions.

More info here:
* https://developer.android.com/studio/write/java8-support.html#supported_features
* https://github.com/bazelbuild/bazel/blob/master/src/tools/android/java/com/google/devtools/build/android/desugar/Desugar.java

**Comment by MeteorKoder** [comment]
What about getting ready for Java 11? I mean it's already out but, will there be support to be able to compile for devices above SDK 26?

**Comment by CaptainGlac1er** [comment]
@ewpatton is it currently on Java8 now?

**Comment by ewpatton** [comment]
@CaptainGlac1er The components library still compiles for Java 5. The problem is that newer versions of javac starting with Java 9 don't support compiling for Java 5 and 6. This change makes it so that everything targets at a minimum Java 7 so that newer versions of javac will compile the system.

**Comment by CaptainGlac1er** [comment]
@ewpatton ah because I noticed that in this PR it was removing `ai.javac5` from the builds and I noticed that everything I looked at on master was using `ai.javac` now.

**Comment by ewpatton** [comment]
This is no longer needed.

**Pull request closed without merging**
