### PR TITLE
Easier for beginners

### PR DESCRIPTION
**Pull request by MeteorKoder**
This ensures that a beginner doesn't have to read documentation to build their extension.

### CODE REVIEW

**Comment by AppInventorWorkerBee** [comment]
Can one of the admins verify this patch?

**Comment by MeteorKoder** [comment]
If this is good to go I can possibly look into `.sh` for Linux and MacOS users.

**Comment by ewpatton** [comment]
@MeteorKoder I think we would still need to update the documentation to inform people of this option. It might not be obvious that you should run this file. Does `@echo off` suppress the `ant extensions` output? If so, that might not be the best thing to do in the event the build fails as any errors will not be shown to the developer.

**Comment by MeteorKoder** [comment]
> @MeteorKoder I think we would still need to update the documentation to inform people of this option. It might not be obvious that you should run this file. Does `@echo off` suppress the `ant extensions` output? If so, that might not be the best thing to do in the event the build fails as any errors will not be shown to the developer.

No, `@echo off` turns of which commands are being run. For example any commands in the bat file (`ant extensions`) won't be seen by the user. Meaning it won't output `ant extensions`, however when building, it shows all output.

**Comment by ewpatton** [comment]
I guess what I'm failing to understand is how this is really easier than just running ant extensions? Might it be better to improve the README document rather than add more scripts? I think the fact that the README makes no mention of extensions is probably the bigger disservice.

**Comment by MeteorKoder** [comment]
> I guess what I'm failing to understand is how this is really easier than just running ant extensions? Might it be better to improve the README document rather than add more scripts? I think the fact that the README makes no mention of extensions is probably the bigger disservice.

Yes but, see... It takes more energy to right click or type cmd into the folder and then have to type ant extensions.

**Comment by MeteorKoder** [comment]
Removed as not needed.

**Pull request closed without merging**
