### PR TITLE
Fix button height when font size is changed

### PR DESCRIPTION
**Pull request by jisqyv**
Make sure the button in the designer scales along with the font size.

This change is a simplification of work originally done by Olivier Midy
<osmidy@mit.edu>.

Change-Id: Iad2033001f26b102506f8bba2dff89f94f6b8ab6

### CODE REVIEW

**Comment by moliata** [comment]
Great, works for me. This pull request should be merged, as it does fix the problem.

**Comment by ewpatton** [comment]
Compared with the production version, the default button is 6px shorter with this branch. The dimensions in values.xml specify that the padding on the device should be 6px vertically and 4px horizontally. It may be worth adopting these values.

**Comment by halatmit** [comment]
I agree we should be consistent.  Thanks.


== Hal

Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.

**Comment by jisqyv** [comment]
@ewpatton Here is another approach. It scales properly and the default button is the same size as our current production version. I actually believe this is a more correct fix.

**Pull request merged**
