### PR TITLE
Use modified kawa jar

### PR DESCRIPTION
**Pull request by jisqyv**
This version does not in-line call/cc which results in errors in certain
situations.

Change-Id: I8710ce5e85fcaa564c270aa80166779eb96ef502

### CODE REVIEW

**Comment by jisqyv** [comment]
Fixes #1282

**Comment by jisqyv** [comment]
@p4ssw0rd @ewpatton I plan on putting this code up on ai2-test either tomorrow or over the weekend.

**Comment by p4ssw0rd** [comment]
Good job, what changes have been made?
I have tested in my server, seems working properly.

BTW, How can I add a constructor like Screen1(Context context, AttributeSet attrs) in kawa ?

**Comment by p4ssw0rd** [comment]
I want to wrap the apply method to invoke the default constructor.

`java.lang.RuntimeException: Unable to start activity ComponentInfo{wxbit.ai_U53BFBC1E86951A783F647EE548E96354.bug/wxbit.ai_U53BFBC1E86951A783F647EE548E96354.bug.Screen1}: java.lang.NoSuchMethodException: <init> [class com.google.appinventor.components.runtime.Form]
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2747)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2808)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1541)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:163)
	at android.app.ActivityThread.main(ActivityThread.java:6360)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:880)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)
Caused by: java.lang.NoSuchMethodException: <init> [class com.google.appinventor.components.runtime.Form]
	at java.lang.Class.getConstructor0(Class.java:2204)
	at java.lang.Class.getConstructor(Class.java:1683)
	at gnu.expr.PrimProcedure.apply(PrimProcedure.java:255)
	at gnu.mapping.CallContext.runUntilDone(CallContext.java:234)
	at gnu.mapping.CallContext.runUntilValue(CallContext.java:298)
	at gnu.kawa.reflect.Invoke.applyN(Invoke.java:209)
	at gnu.mapping.ProcedureN.apply2(ProcedureN.java:39)
	at wxbit.ai_U53BFBC1E86951A783F647EE548E96354.bug.Screen1.$define(Screen1.yail:10201)
	at com.google.appinventor.components.runtime.Form.onCreateFinish(Form.java:348)
	at com.google.appinventor.components.runtime.Form.onCreate(Form.java:295)
	at android.app.Activity.performCreate(Activity.java:6863)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2700)
	... 9 more
`

**Comment by jisqyv** [comment]
@p4ssw0rd @ewpatton This code is now deployed on ai2-test

**Comment by ewpatton** [comment]
@jisqyv LGTM, but do you want to put this on hold while you investigate fixing the inlining?

**Comment by jisqyv** [comment]
@ewpatton I've put this on hold. I have another fix that only involves a re-written "while" macro. I'll put it up as a PR after I finish testing it (sometime on Tuesday), assuming it all works.

**Comment by jisqyv** [comment]
This fix is deprecated in favor of #1295.

**Pull request closed without merging**
