### PR TITLE
Replace use of isRenderingOn with Blockly event management

### LINKED ISSUE #1071: Overlapping blocks
A few months ago, Ewan made a commit 853908e07d2311510b67c9f465cf1f03ac3ce6de which had to fixed #920, but after that commit I didn't see an issue being fix... I have already given a notice about that to Hossein, who made a post on Open Source Development forum.
Indeed, blocks states are not stored during upgrades. This is probably happening because either block positions are stored incorrectly or we do not retain them correctly.

### PR DESCRIPTION
**Pull request by ewpatton**
When the 2017 Blockly update was done, it used isRenderingOn to
determine when to position and render the blocks. This was to optimize
the interaction between the load/upgrade process and workspace
resizes. However, in rare instances it seems to result in blocks not
being placed correctly.

This change removes the special handling of upgrading. Instead, it
disables and enables the Blockly event system during a load/upgrade
operation. At the end of the upgrade process (if needed), it will also
force a save of the blocks workspace.

Fixes #1071

Change-Id: I6bec41dd67bc6371e794e93850ea1455b9acf8c7

### CODE REVIEW

**Comment by ewpatton** [comment]
@kkashi01 @ColinTree @moliata You may also want to take a look at this.

**Comment by ewpatton** [comment]
-1 at the moment. One test is failing for a yet-to-be-determined reason.

**Comment by ewpatton** [comment]
The issue was in a test I added after my previous attempt to address the overlapping blocks problem. In that change, we were fixing the blocks being munged due to an upgrade, and I updated the MoleMash test to verify that the blocks stored their coordinates. The variables relied on for that test were removed with this change. I have updated the test to use the `getRelativeToSurfaceXY()` method call, which is a more appropriate way to check this information.

**Comment by kkashi01** [comment]
@ewpatton  Will pull and check.

**Comment by Amerkashi** [comment]
Some additional info from forum:
https://groups.google.com/d/msg/mitappinventortest/RoFmeZxFEdU/4akZJjsBFAAJ

**Comment by ewpatton** [comment]
@jisqyv @SusanRatiLane I think I have a strategy for testing this that I can replicate on my Mac. See if you can as well.

1. Compile a clean copy of App Inventor from master
2. Run the dev server
3. Log into localhost:8888
4. Open your dev tools to the Network tab
5. Create a new project
6. Open the blocks editor
7. Drag a block (I used controls_if)
8. Wait 5 seconds for the autosave to occur
9. Examine the project RPC. You should see that the `<block>` tag has undefined `x` and `y`.
10. Apply the patch and repeat steps 1-9. In this case, the `x` and `y` values should be defined.

**Comment by SusanRatiLane** [comment]
There seems to be at least one more factor in reproducing. When I created a small functional program (Click a button to pop up a notification), the locations of the blocks were fine. When I created a program -- maybe best described as a pile of blocks -- with warnings and errors, then the locations were not set on save in master.

Confirmed that this fix resolves the problem for the cases I found.

**Pull request merged**
