### PR TITLE
Improve app resizing on Chromebooks

### LINKED ISSUE #1740: companion on Chromebook
On my Acer Chromebook the companion of App Inventor looks not good. Fonts and buttons are much to big. 

I compared the companions from the four biggest builders and added them here for reference. Two of them work as it should, two of them show the same effect of large fonts and buttons. 

Screenshot 2019-07-12 at 15 14 35

Maybe it has to do with the screen being set to fixed instead of responsive.

### PR DESCRIPTION
**Pull request by ewpatton**
Fixes #1740

Change-Id: I58de7133e0eb76d13353ed152c38137bbdb31a3d

### CODE REVIEW

**Comment by PeterMathijssen** [comment]
I have a Chromebook. Can i help in testing this?

Peter

Op do 16 jan. 2020 15:30 schreef Jeffrey Schiller <notifications@github.com

**Comment by jisqyv** [comment]
@PeterMathijssen I'm going to put this change, and a few others up on ai2-test, likely later today so people can test. I'll put a note in the community forum when it is up. Thanks.

**Comment by PeterMathijssen** [comment]
@jisqyv, companion is looking good and when i use fixed sizing it is also looking good.

**Comment by ewpatton** [comment]
@PeterMathijssen Thanks for testing that it fixes your issue. @jisqyv Let's go ahead and merge this one.

**Pull request merged**
