### PR TITLE
Close the NXT file handles in NxtDirectCommands.ListFiles.

### PR DESCRIPTION
**Pull request by lizlooney**
This should fix the problems reported recently in the forum. https://groups.google.com/forum/#!topic/mitappinventortest/y4bfnAliW-A
https://groups.google.com/forum/#!topic/mitappinventortest/8IaIcWE0t_o

@josmas @halatmit

### CODE REVIEW

**Comment by jisqyv** [comment]
@lizlooney I don't have the hardware needed to test this. Can you tell me that you have tested it?

**Comment by lizlooney** [comment]
I cannot tell you that I have tested it because that would be a lie.
I'll test it and let you know. You can keep this in the "needs review" state until I get back to you.

**Comment by jisqyv** [comment]
@lizlooney Thanks.

**Comment by afmckinney** [comment]
Hi Liz, just wondering if you have had a chance to test this yet.

**Comment by lizlooney** [comment]
I'm sorry. I haven't had a chance to test it. I'm in St Louis (at the FIRST
World Championships) until Sunday. I'll try to test it next week.

Sorry!

-Liz

**Comment by afmckinney** [comment]
Thanks Liz.

**Comment by lizlooney** [comment]
FYI: I'm still working on testing this. I need to build a program that runs on the NXT (which I haven't done in years) and I'm having trouble running the NXT-G software on my Mac. I think I have friends who can build a program for me.

**Comment by lizlooney** [comment]
I'm in the process of testing this and I have found some problems. I'll let you know when it is ready.

Thanks for your patience!

**Comment by lizlooney** [comment]
I tested this and it doesn't work. In some cases, it makes things worse. (Thanks for not just blindly trusting me!)

I'm closing this pull request.

**Comment by halatmit** [comment]
Thanks!


== Hal

Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.

**Pull request closed without merging**
