### PR TITLE
Removed if condition converting list-of-lists into dictionary

### LINKED ISSUE #2408: Dictionary constructors coerces list-of-lists to dict
**Describe the bug**

[Forum post](https://community.appinventor.mit.edu/t/problem-with-dictionary-of-list-of-lists/25850/2?u=ewpatton): Passing a list-of-lists as a value in the dictionary constructor converts it into a dictionary unexpectedly. Using a set block to update an empty dictionary does the correct thing (storing the list in the dict).

**Affects**

- [ ] Designer
- [ ] Blocks editor
- [x] Companion
- [x] Compiled apps
- [ ] Buildserver
- [ ] Debugging
- [ ] Other... (please describe)

**Expected behavior**

The value should be stored unmodified in the dictionary.

**Steps to reproduce**

1. Create a list of lists
2. Create a dictionary, setting mapping a string key to the list-of-lists value
3. Print the dictionary using Do It or a label, observe that the what should be a list of lists is now a dictionary

### PR DESCRIPTION
**Pull request by AnujSinghal12**
Fixes #2408 
Steps to Check :

1. Build an app similar to the screenshot attached.
2. Run it on the companion to see the output message.

I could not run the unit tests on my local due to issue #2413. 

Screenshot from 2021-02-18 22-38-02

### CODE REVIEW

**Comment by AppInventorWorkerBee** [comment]
Can one of the admins verify this patch?

**Comment by ewpatton** [comment]
@AppInventorWorkerBee ok to test

**Comment by AnujSinghal12** [comment]
In the [test case](https://jenkins.appinventor.mit.edu/job/appinventor-sources/1177/testReport/junit/com.google.appinventor.components.runtime.util/YailDictionaryTest/testDictListConstructor/) that is failing, the input into `makeDictionary` is 
`[["number", 1], ["string", "foo"], ["empty-list", []], ["list", [["a", "b"], 2, 3]], ["dict", ["a", "b"]],  ["list-with-dict", [["a","b"]]]]`

The expected output is 
`{"number":1,"string":"foo","empty-list":[],"list":[["a","b"],2,3],"dict":{"a":"b"},"list-with-dict":[{"a":"b"}]}`

In order for the test case to pass, `makeDictionary` must coerce list-of-list into dictionaries. 

Looking at the code, the `makeDictionary` constructor has been written to convert list of lists into a dictionary. Hence, this test has been written to check this particular behavior. 
So the question is, what was the purpose for this behavior to exist in the first place? I am asking to understand if removing this behavior will affect anything adversely.

Moreover, if we remove this behavior then we will have to change the failing test as well.

**Comment by ewpatton** [comment]
@AnujSinghal12 That's correct. The test was asserting that the old behavior was correct, but since we're changing the semantics you'll need to update the test to reflect that. That particular makeDictionary signature is only invoked via that one block and the tests, so it should be safe to just update the test to reflect the change.

**Comment by AnujSinghal12** [comment]
Sounds good, thanks!

**Comment by ewpatton** [comment]
@AnujSinghal12 Will you have time soon to update the failing test to reflect the semantic change?

**Comment by AnujSinghal12** [comment]
Oh I'm really sorry I assumed since you had self-assigned this that you were going to change it. But yeah I'll get it done in couple of days.

**Comment by ewpatton** [comment]
@AnujSinghal12 No worries. We use the PR assignment to indicate who on the core team is responsible for reviewing and merging the change.

**Comment by AnujSinghal12** [comment]
I've updated the test. The `getTestList` method was written with the previous functionality in mind, I changed some parts of it to reflect the updated `makeDictionary` constructor.

**Review by ewpatton — APPROVED** [review]
LGTM

**Comment by OfficialDarkComet** [comment]
I am having issues that I believe are related with this problem as well. Everything works as predicted up until you add a list of nested pairs. Hopefully posting this will help narrow down the issue.

I posted on [Kodular's community forum](https://community.kodular.io/t/problem-with-nested-dictionaries-and-lists/134537), but was referred to this issue as it seems to be related with App Inventors source code.

This is the point at where I am having issues:

In JSON, lets say you have a list variable.

Screenshot 2021-07-26 143930

```
[ 
  item_1, 
  item_2, 
  item_3 
]
```

That’s fine, now replace those items with key-value pairs. Now it’s a “list of pairs”.

Screenshot 2021-07-26 144112

```
[ 
  (key_1, value_1),
  (key_2, value_2),
  (key_3, value_3)
]
```

Now, lets replace each of those values with dictionary.

Screenshot 2021-07-26 144207

```
[ 
  (key_1, {}),
  (key_2, {}),
  (key_3, {})
]
```

In each of those dictionaries, lets add some key and values.

Screenshot 2021-07-26 144401

```
[ 
  (key_1, {
    "key_1_1" : "value_1_1",
    "key_1_2" : "value_1_2"
  }),
  (key_2, {
    "key_2_1" : "value_2_1",
    "key_2_2" : "value_2_2"
  }),
  (key_3, {
    "key_3_1" : "value_3_1",
    "key_3_2" : "value_3_2"
  })
]
```

Now, let us replace those values with lists.

Screenshot 2021-07-26 144507

```
[ 
  (key_1, {
    "key_1_1" : [ ],
    "key_1_2" : [ ]  
  }),
  (key_2, {
    "key_2_1" : [ ],
    "key_2_2" : [ ]
  }),
  (key_3, {
    "key_3_1" : [ ],
    "key_3_2" : [ ]
  })
```
]

Now… Let’s stop here, because this is where I am having issues.

Everything up to this point formats correctly. However, **after the screen initializes**, if the last nested list is **empty** and I was to add key-value pairs making it a paired-list, then I can use all the regular methods for “Lists”. I can lookup pairs, find by index or find the index of a pair, etc…

**However…** IF the lists had pairs inside them **before screen initialization**, things go haywire. I can no longer use lookup pairs, find the index or use an index because the nested lists and all future (deeper nested) lists are converted to dictionaries…

The reason I discovered this was I added data to my main database (written in JSON with dictionaries, lists and paired-values), which up to this point had worked correctly, **but having data prior to screen initialization causes the issue.**

Thank you for your time, and hopefully I explained things clearly/organized enough that my issue can be understood (and not sound like gibberish). If I need to clarify anything, then let me know.

 -- Logan (a.k.a. DarkComet)

**Comment by OfficialDarkComet** [comment]
This test AIA was made and runs on App Inventor 2. It is an issue on both builders (App Inventor & Kodular)

This AIA project is a little janky and quickly thrown together, but it shows the issues in App Inventor. On run time the list of key-value pairs are converted to a dictionary, however if the list is empty on runtime, everything is fine (format is correct).

App Inventor 2 AIA:
[AI2_Nested_List_Bug_Test.zip](https://github.com/mit-cml/appinventor-sources/files/6888762/AI2_Nested_List_Bug_Test.zip)

**Pull request merged**
