### PR TITLE
implement hint property for ListView

### PR DESCRIPTION
**Pull request by mlcstrc**
Create Hint property for ListView component.

### CODE REVIEW

**Comment by AppInventorWorkerBee** [comment]
Can one of the admins verify this patch?

**Comment by ewpatton** [comment]
@mlcstrc This is looking pretty good but you will need to bump the version number of the List View component and then write the upgrade paths in YoungAndroidFormUpgrader.java and versioning.js.

**Comment by ewpatton** [comment]
@AppInventorWorkerBee ok to test

**Comment by patryk84a** [comment]
I think the name "Hint" doesn't say enough about what this property is about. Maybe "FilterHint"?

**Comment by SusanRatiLane** [comment]
> I think the name "Hint" doesn't say enough about what this property is about. Maybe "FilterHint"?

I think "HintText" makes sense. That would be consistent with the similar TextBox property.

**Comment by SusanRatiLane** [comment]
@ewpatton This is ready for a second look.

**Pull request merged**
