### PR TITLE
Updated the Storage documentation to reflect the changes to the Fusion T...

### PR DESCRIPTION
**Pull request by ajcolter**
...ables component that allows Service Authentication. Added the additional necessary steps to make this possible. Also proofread the other entries on the Storage page.

@afmckinney @jisqyv

### CODE REVIEW

**Comment by halatmit** [comment]
Doc looks good, and can be merged.
@jisqyv 
@afmckinney 

Does DoQuery work at all now?  If not, do we want to use the upgrader to mark  the block bad and put an error message telling people toi use SendQuery?  If so, I'd merge this current doc fix, and file the DoQuery thing as a new issue.

**Comment by josmas** [comment]
It was deprecated in the api so not working, should be deprecated in the component too.

This happened before we moved to AI2, so the chances of finding one of those blocks is rather slim, but still, should be marked as bad.

**Comment by jisqyv** [comment]
We can deprecated. In fact I *did* deprecate when I was testing the bad block code (but I only deprecated it in my testing) so I know that the deprecation code will do the right thing.

**Comment by halatmit** [comment]
sounds good.  Does DoQuery work at all?  If not, we should clearly
deprecate.



== Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.
MIT Media Lab, Second Class Faculty

**Comment by jisqyv** [comment]
Let me test it, I'm pretty sure it doesn't work.

-Jeff

**Comment by afmckinney** [comment]
DoQuery is obsolete now, and should be deprecated. But, I will double check just to be 100% sure.

Andrew F. McKinney
andrew.f.mckinney@gmail.com <mailto:andrew.f.mckinney@gmail.com>
+1 978-255-3979

**Comment by jisqyv** [comment]
I just checked. You get a 404 Error if you attempt to use it.

**Comment by jisqyv** [comment]
LGTM, Sending to Gerrit...

**Comment by ajcolter** [comment]
I will say that I found a few more errors in the text. But I can just
submit them as another pull request.

**Comment by jisqyv** [comment]
MERGED

**Pull request closed without merging**
