### PR TITLE
Combine Yail Forms sent to the Companion

### PR DESCRIPTION
**Pull request by jisqyv**
When we have a queue of forms ready to go to the Companion, combine
them into one large Ajax request. Unfortunately we lose track of which
block each form is form. However combining forms is likely only going
to happen when this isn’t as important. Keeping track of blocks
requires a new support in the Companion, which is forthcoming.

Change-Id: I312729fda02155fc0b142e2149fab1bdbadb3921

### CODE REVIEW

**Comment by jisqyv** [comment]
@halatmit @afmckinney This addresses #220. It eliminates the "Ghost Component" that we see when loading a project into the Companion.

**Comment by jisqyv** [comment]
@halatmit @afmckinney OK. Now we are ready for a review...  -Jeff

**Comment by halatmit** [comment]
I tried this and it seems to work.   Is there some specific test I should try?
If not, then LGTM.

**Comment by jisqyv** [comment]
@halatmit There isn't a specific test. I have been running it on largish projects and it appears to work.

I'll arrange to merge it.

**Comment by jisqyv** [comment]
Latest commit is just a squash of the previous commits.

**Pull request merged**
