### PR TITLE
Spreadsheet component name

### PR DESCRIPTION
**Pull request by SusanRatiLane**
Remove Google Sheets-specific names from this component. It currently only supports Google Sheets, but that may change in the future.

### CODE REVIEW

**Comment by jisqyv** [comment]
@SusanRatiLane @ewpatton There is a fence post error with YAV. ai2-testing currently has YAV set to 217, so the check should be < 218 and YAV should be set to 218 in this change. I can make the change and push it here prior to merging. I'm currently in the process of verifying that apps built on ai2-test will do the right thing when I update ai2-test after this change is merged.

**Comment by ewpatton** [comment]
@jisqyv Sure that should be a quick fix.

**Comment by jisqyv** [comment]
@ewpatton @SusanRatiLane So when I test this upgrading a project I have with the GoogleSheets extension, it blows up in the upgrader. Still working on figuring out why and how.

**Comment by jisqyv** [comment]
@ewpatton @SusanRatiLane I figured it out. I'll push a few commits later tonight or tomorrow which fixes this and another minor issue I found.

**Comment by jisqyv** [comment]
@ewpatton @SusanRatiLane This code is now on ai2-test (08/21/2022 version)

**Review by ewpatton — APPROVED** [review]
LGTM

**Pull request merged**
