### PR TITLE
update backpack.html to have web published version

### PR DESCRIPTION
**Pull request by jsheldonmit**
instead of editable/commentable version, with viewership restrictions

### CODE REVIEW

**Comment by jisqyv** [comment]
@jsheldonmit Last time I checked, the web published version was formatted screwy, which is why I went with the actual doc.

**Comment by jsheldonmit** [comment]
@jis gotcha – I’ll look more carefully
================
Josh Sheldon
Director of Strategic Programs – MIT App Inventor
Project Manager - MIT Scheller Teacher Education Program
MIT Center for Mobile Learning
20 Ames St., Bldg E15-309
Cambridge, MA 02139
cell: 617-671-5491
work: 617-715-4051

http://appinventor.mit.edu - @MITAppInventor<http://twitter.com/MITAppInventor>
http://education.mit.edu - @mitSTEPlab<http://twitter.com/mitSTEPlab>

**Comment by jsheldonmit** [comment]
@jis ugh – yes, it is screwy – I’ll try to get Ralph or Grace to improve it.
================
Josh Sheldon
Director of Strategic Programs – MIT App Inventor
Project Manager - MIT Scheller Teacher Education Program
MIT Center for Mobile Learning
20 Ames St., Bldg E15-309
Cambridge, MA 02139
cell: 617-671-5491
work: 617-715-4051

http://appinventor.mit.edu - @MITAppInventor<http://twitter.com/MITAppInventor>
http://education.mit.edu - @mitSTEPlab<http://twitter.com/mitSTEPlab>

**Comment by halatmit** [comment]
I played with the formatting and issued a new pull request. #570

**Comment by halatmit** [comment]
I tweaked it a little.   Looks like a Google Docs issue


== Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.
MIT Media Lab, Second Class Faculty

**Pull request closed without merging**
