### PR TITLE
Bugfix to typeblock, fix component-event blocks.

### PR DESCRIPTION
**Pull request by jisqyv**
Bugfix to typeblock.js to work correctly on component-event blocks.

Change-Id: I4e152bf7086ab3b6c4a646a8b7cde8868feb5ebc

### CODE REVIEW

**Comment by jisqyv** [comment]
@halatmit @josmas This fixes the problem referenced in #242

**Comment by halatmit** [comment]
@jisqyv 

Tried it and it seems to work.
LGTM

by the way, what broke things?

**Comment by jisqyv** [comment]
@halatmit Evan converted the code to call Blockly.Drawer.getDefaultXMLString(). However that call doesn't provide default code for every block, in which case it returns null. His code for constructing the block was just not right (and I didn't catch it in the review). The code there now is the correct way to construct the block if there isn't a default XML String to start with.

**Comment by jisqyv** [comment]
@halatmit I meant to say his code for constructing the block when when getDefaultXMLString doesn't provide one was where the problem was.

**Comment by halatmit** [comment]
thanks



== Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.
MIT Media Lab, Second Class Faculty

**Pull request merged**
