### PR TITLE
Update display list documentation for AI2 (The trivial change here is…

### PR DESCRIPTION
**Pull request by halatmit**
… to force a re-push)

### CODE REVIEW

**Comment by josmas** [comment]
What do you mean by _**forcing a re-push**_?

**Comment by halatmit** [comment]
Someone I thought I'd pushed this to github before, but it's not there.
So I'm trying again.



== Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.

**Comment by josmas** [comment]
Are you in the right branch? There's only one file change in here, and it's the trivial change you pushed last (no other changes than a space added to _displaylist.html_).

**Comment by jisqyv** [comment]
Change already made

**Pull request closed without merging**
