### PR TITLE
[GSoC] New Projects Explorer

### PR DESCRIPTION
**Pull request by Vishwas-Adiga**
This PR introduces a new projects explorer with support for folders and project shortcuts. These changes are based on my GSoC '21 [proposal](https://docs.google.com/document/d/1vfNO8Pm1zGFtKwPU16oH6Jhb-nDniuGjnphCOne1G3E/edit).

Changelog:
- [X] Allow user to opt-in to new explorer
- [X] Create, import, and template-import projects from explorer
- [X] Separate bundle generation for new explorer
- [X] Support for mobile devices
- [X] Skin support
- [X] View, restore, and permanently delete trashed projects
- [x] Export projects from explorer 
- [x] Support multiple skins that can be switched at runtime (useful for dark mode)
- [x] New top bar based on UiBinder
- [x] Build a project from the explorer (checks for cached builds)
- [x] Rename/batch rename projects
- [x] Create folders
- [ ] Move folders
- [ ] Trash/restore folders
- [ ] Drag and drop projects
- [ ] Sort projects/folders
- [ ] Use strings from OdeMessages

### CODE REVIEW

**Comment by ewpatton** [comment]
@SusanRatiLane @Vishwas-Adiga Something that would be helpful as part of this refresh is if we could potentially increase the size of the rows to be at least 44px (with maybe a few pixels for border/padding). Apple iOS guidelines recommend touch targets be at least 44px in size, and we know that people are using the App Inventor interface on touch devices. This would help improve the experience.

**Comment by Vishwas-Adiga** [comment]
As of now, rows are 35px in height, but I can conditionally make them 44px tall when accessed from a mobile device. We should be able to take the same approach with other UI elements, but I will have to try this out first

**Comment by ewpatton** [comment]
Sure. Depending on the visual difference it might make sense to apply it evenly across devices.

**Comment by rudrathedev** [comment]
Epic work! Excited to see this PR live 💟

**Comment by SRIKAR-B-S-S** [comment]
Hope you finish this PR soon 😁

Good Luck 👍

**Comment by SusanRatiLane** [comment]
> Hope you finish this PR soon 😁 and make it live

Vishwas's contribution here is being included in a larger user interface refactor that I am working on. It's a great more modern look that I'm hoping to extend to the designer.

**Review by Nisarga-Developer — APPROVED** [review]

**Pull request closed without merging**
