### PR TITLE
Use globs for proguard library paths

### PR DESCRIPTION
**Pull request by ewpatton**
Change-Id: Ia00a67f38b037712094dc7a8846b93e87ebb192e

### CODE REVIEW

**Comment by ewpatton** [comment]
The moving around of libraries for the Spreadsheet component broke the Proguard target. We don't use this particular target for building our sources but extension developers make use of it to obfuscate their bytecode. This change switches the Proguard task to use filesets and globs to be more robust to library additions/changes/deletions in the future.

**Comment by ewpatton** [comment]
@puravidaapps confirmed that this addressed the issue: https://community.appinventor.mit.edu/t/proguard-issue-while-building-an-extension-using-the-latest-sources/66444?u=ewpatton

**Comment by jisqyv** [comment]
@ewpatton This change makes me a little queasy. We should have fixed the progard target, no argument there. But I fear this change may lead to hidden dangers. For example, someone not using "ant clean" and then getting successful builds have shuffling libraries or whatever because of a jar file left lying around, but later builds fail (or our builds fail) after a clean. In other words, this may lead to non-reproduceable builds. Sort of the same reason we do not want * imports in java files.

**Comment by ewpatton** [comment]
The extensions target, which is the only thing that invokes proguard, performs a clean, so leftover libraries should not be an issue.

I'm also not sure that the default proguard configuration would lead to reproducible builds anyway since the obfuscated names can be randomly assigned IIRC, so to reproduce you have to seed the build with a specific value.

**Comment by jisqyv** [comment]
@ewpatton OK. I guess I didn't realize this is just for the Proguard target. So, in that case, I'm fine with it.

**Review by jisqyv — APPROVED** [review]
LGTM

**Comment by ewpatton** [comment]
@jisqyv Ah okay, I can see how your argument made sense then. Yes, we still are copying individual files over for the regular build process (into deps) and then this references the files from the deps folder for proguarding.

**Comment by ewpatton** [comment]
The extensions target performs a clean, so leftover libraries should not be an issue. I'm not sure that using proguard results in reproducible builds anyway since one can always change how the minified class names are randomly assigned.

**Comment by alphanumericaracters** [comment]
Hello everyone, im trying to update de BarcodeScanner to PDF417 (Updating to 3.5.1 core.jar and javase.jar) but ant securitymanager trigger and fail building.

Anyone can helpme? or has a extension Barcode to read PDF417

**Comment by ewpatton** [comment]
@alphanumericaracters Please ask your question at https://community.appinventor.mit.edu.

**Pull request merged**
