### PR TITLE
Support for options menu, ordered components on palette, renaming method/property blocks

### PR DESCRIPTION
**Pull request by lizlooney**
These are changes that I made for FTC, but I think would be useful on the master branch.

@jisqyv @halatmit

### CODE REVIEW

**Comment by halatmit** [comment]
@lizlooney 
Liz,
Please add something -- maybe an extended comment -- that explains how the component ordering mechanism is intended to be used?     thanks

**Comment by lizlooney** [comment]
I added another file: NxtPaletteHelper.java to show how to use the component ordering mechanism.

Please let me know if I'm re-inventing the wheel here. I could not find an existing way to order the components in the palette, but it's hard to believe we never needed/wanted that before.

**Comment by halatmit** [comment]
This is not reinventing the wheel.  It's very useful.   Can you add an
extended comment to show developers how to use this when adding new
components?






== Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.
MIT Media Lab, Second Class Faculty

**Comment by afmckinney** [comment]
Hi Liz, 
Don't worry about the comment I will add a section in our "How build a component" doc how to use this.

Thanks 

Andrew

**Comment by afmckinney** [comment]
Looks good to me. Now merged into gerrit.

**Pull request closed without merging**
