### PR TITLE
Select all on renaming component

### PR DESCRIPTION
**Pull request by E-Hon**
@halatmit 

Please read the doc for details. If this change is a go, a new commit will be made so that the doc will not stay in master branch.

### CODE REVIEW

**Comment by E-Hon** [comment]
**Description**
Automatically select all the text of the new name input textbox when renaming a component

**Scenario 0**
1. Choose a component that can be renamed
2. Click Rename button in the panel
3. Imgur

**Scenario 1**
1. Choose a component that can be renamed
2. Enter an invalid new name. e.g. *foo
3. Click the OK button on the warning message
4. Imgur

**Comment by halatmit** [comment]
Please indicate what bad behavior is  being fixed here.  The message isn't clear.   Also please put this up on a test instance on Appengine so reviewers can check it.   Thanks!

**Comment by E-Hon** [comment]
Originally, when renaming, the cursor of the "New name:" input goes to the beginning. This may be inconvenient.

**Comment by halatmit** [comment]
That comment is still not clear

**Comment by josmas** [comment]
This is a UX improvement, not trying to fix a bug per se. I quite like it and it's a very common pattern nowadays. If you are going to rename something, it's easier if it's already selected so you can start typing the new name (which will delete the old name automatically). As it works now, you have to select and delete the old name before typing the new one.

**Comment by josmas** [comment]
@E-Hon but that pdf file has to go away! :)

**Comment by halatmit** [comment]
Jose:  Thanks for the explanation.
Can you look at the code and give it a LGTM if it seems OK?

**Comment by E-Hon** [comment]
@halatmit 
Please have a look to see if it can clear things up.
Imgur

@josmas 
I forgot to update this branch. I just removed it.

**Comment by josmas** [comment]
@halatmit can't right now but can do some time tonight or tomorrow night. will assign it to me.

**Comment by josmas** [comment]
thanks @E-Hon will check the code as soon as I can!

**Comment by halatmit** [comment]
José:  Thanks for offering to take a look.





== Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.
MIT Media Lab, Second Class Faculty

**Comment by E-Hon** [comment]
You may try this change here.
http://ai2newfeatures.appspot.com

**Comment by josmas** [comment]
@E-Hon @halatmit it works as expected but after having tried it, I am not sure I like it in all cases.

The changes affect renaming components (which I do like), and using either the 'save as' or 'checkpoint' menus (which I like a little less).

It would be wise to push to appspot and ask PowerUsers what they think.

**Comment by josmas** [comment]
oh! I did not see the new comments; it's already on appspot.

**Comment by E-Hon** [comment]
Right, because there are naming conventions for 'save as' and 'checkpoint',
users may not want to change the whole name.

How should I ask PowerUsers to play with this new change on appspot?

**Comment by jisqyv** [comment]
LGTM

**Comment by jisqyv** [comment]
MERGED

**Pull request closed without merging**
