### PR TITLE
Add Speed to Location Sensor

### PR DESCRIPTION
**Pull request by jisqyv**
Also made sure that “LocationChanged” event is fired on the UI Thread.

Change-Id: Iee477442e1acad69e755e5fea4344be5f28b559b

### CODE REVIEW

**Comment by jisqyv** [comment]
@halatmit @afmckinney Please Review. This code has been tested and is running on ai2-test.

**Comment by jisqyv** [comment]
@halatmit @afmckinney This review has been moved to Gerrit. Review will take place there. This will permit us to "stack" the remaining component changes on top of each other so we avoid conflicts in YaVersion (given that each has to modify YaVersion).

**Comment by jisqyv** [comment]
@halatmit @afmckinney Gerrit Review:

https://gerrit.appinventor.mit.edu/#/c/1908/

**Comment by afmckinney** [comment]
reviewed tested and merged

**Pull request closed without merging**
