### PR TITLE
Support carriage return "\r" in blocks language

### LINKED ISSUE #1090: Support carriage return "\r" in blocks language
[From the forum](https://groups.google.com/d/msg/mitappinventortest/05-nzpptCwA/3_vLdzEhBwAJ): It would be nice if \r was supported similarly as \n.

### PR DESCRIPTION
**Pull request by conorshipp**
Resolves #1090

### CODE REVIEW

**Comment by ColinTree** [comment]
What about \r\n? This should be considered as one Enter only.

**Comment by moliata** [comment]
A possible way to handle that, which is not so beautiful, would be calling `String.replace(target, replacement);` method.

**Comment by ewpatton** [comment]
@moliata @ColinTree I disagree.

\r and \n are different characters (unicode points 000D and 000A, resp.), and should be treated as such. My motivation for issue #1090 was that some people may want to interface with HTTP servers or Windows where the traditional line ending is \r\n.

**Comment by moliata** [comment]
@ewpatton, I disagree too. A lot of IDEs, for example IntelliJ IDEA, Android Studio, PyCharm, Xcode and lots of others use \r\n as a secondary option & this is default new line characters in Windows. More details at https://stackoverflow.com/questions/15433188/r-n-r-n-what-is-the-difference-between-them

**Pull request merged**
