### PR TITLE
Recreate the ScaledFrameLayout on orientation change

### PR DESCRIPTION
**Pull request by jisqyv**
This should solve the “black bar” problem when rotating the screen.

Change-Id: Ib1a272a256dc4c3bf03e0b7e6c32da8f76453cec

### CODE REVIEW

**Comment by jisqyv** [comment]
@halatmit Seems to work so far...

**Comment by halatmit** [comment]
LGTM :)

**Comment by jisqyv** [comment]
@halatmit I'll merge this as soon as we get a little bit of feedback indicating that it solves folks problems (and doesn't cause new ones!). :-)

**Comment by jisqyv** [comment]
MERGED

**Pull request closed without merging**
