### PR TITLE
Fix No Projects message

### PR DESCRIPTION
**Pull request by halatmit**

### CODE REVIEW

**Comment by halatmit** [comment]
fixes issue #467 
@afmckinney 
Please review and also close #467 when this is merged.

**Comment by jisqyv** [comment]
@halatmit Heh heh I was going to do this today, but you beat me to it. ☺

**Comment by halatmit** [comment]
If you have time, try that experiment with using SP for font sizes in the
ai4 branch.



== Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.
MIT Media Lab, Second Class Faculty

**Comment by jisqyv** [comment]
> If you have time, try that experiment with using SP for font sizes in the
> ai4 branch.

Will do.

-Jeff

**Comment by jisqyv** [comment]
LGTM -- Should merge shortly. I'll likely deploy this today. The less time we confuse new users, the better.

**Comment by jisqyv** [comment]
MERGED

**Pull request closed without merging**
