### PR TITLE
Update GWT to fix dropdown position in Chrome 61

### LINKED ISSUE #944: Property dropdown positioning in Chrome 61
Reported by @kkashi01 on the [dev forum](https://groups.google.com/d/msg/app-inventor-dev/QRRsFH2NjEs/-8yPQ75IBwAJ):

In the latest version of Chrome (Chrome 61) the dropdowns for properties in the designer do not adjust for the scroll position of the page. They seem to appear always at the location they should appear if scrollTop = 0. This is likely an issue with GWT and we may need to update/patch GWT to address this.

### PR DESCRIPTION
**Pull request by ewpatton**
Fixes #944

Change-Id: I9fbb8d8a5d2c546ad44ab639f21a165fd7194d1e

### CODE REVIEW

**Comment by ewpatton** [comment]
@kkashi01 You may want to test this as well.

**Comment by kkashi01** [comment]
@ewpatton Thanks. Sure, will give it a try.

-Hossein.

**Comment by kkashi01** [comment]
@ewpatton Took updates, rebuilt (without ant clean) and still same issue.

-Hossein.

**Comment by ewpatton** [comment]
I don't know that ant will pick up on the change to the GWT library without a clean. Alternatively, make sure you force reload your browser just to make sure it's not using an older cached version. 

Evan

**Comment by kkashi01** [comment]
@ewpatton cleaned, rebuilt, but unfortunately issue still there. Even tried in incognito; same issue.

-Hossein.

**Comment by moliata** [comment]
@ewpatton issue was fixed in GWT v1.8.2 not v1.8.1

**Comment by ewpatton** [comment]
@kkashi01 Thanks. It looks like when I cherry-picked this fix from my development branch to master, git decided to resolve the conflicts by renaming the files but not taking the updated jars. I'm running some additional tests now and should have the update pushed soon.

**Comment by ewpatton** [comment]
@moliata 2.8.2 has not yet been released. We maintain our own repo that tracks the gwt development with some additional patches to fix problems compiling the latest Blockly/Closure compiler sources, so that is why the version is 2.8.1-patched and not 2.8.2 or 2.8.2-patched.

**Comment by moliata** [comment]
Oh ok, thanks for the info.

**Comment by kkashi01** [comment]
@ewpatton We tested on couple browsers and positioning looks great.

**Comment by ewpatton** [comment]
@kkashi01 Thanks for the confirmation that this latest update is working for you.

**Comment by moliata** [comment]
Issue has been fixed. Tested twice.

**Comment by ewpatton** [comment]
This PR was closed by 2d6e239.

**Pull request closed without merging**
