### PR TITLE
Update ftc branch with released master commits.

### PR DESCRIPTION
**Pull request by lizlooney**
@jisqyv

### CODE REVIEW

**Comment by jisqyv** [comment]
@lizlooney Note: There were merge conflicts in ko_kr/_messages.js. I fixed them, but you might want to pull this commit over to your local branch. Make sure you notion of ftc is the same as here (they should have the same SHA1 commit ID).

**Comment by jisqyv** [comment]
@lizlooney I just nuked this commit (sorry) via a force push. I'm merging your other PR first and then I'm going to redo the merge of master. It makes the branch cleaner...

**Comment by jisqyv** [comment]
@lizlooney merge of master is now redone.

Again, make sure your version of "ftc" corresponds with this version (7b9038212eaea4617f15bc880f0f4b25fedf4f2c)

Sorry about the confusion.

**Comment by lizlooney** [comment]
Thanks!

**Pull request merged**
