### PR TITLE
Update to target Android SDK 34

### PR DESCRIPTION
**Pull request by ewpatton**
This PR updates App Inventor to target Android SDK 34. The changes are based on my reading of [Behavior changes: Apps targeting Android 14 or higher](https://developer.android.com/about/versions/14/behavior-changes-14). I've done some preliminary testing with the following components:

- [x] Texting
- [x] ImagePicker
- [x] ListPicker

Here's a complete list of items that I looked at the code for but haven't tested:

	- [ ] ActivityStarter
	- [ ] BarcodeScanner
	- [ ] Camcorder
	- [ ] Camera
	- [ ] ContactPicker
	- [ ] ExternalTextToSpeech
	- [ ] FilePicker
	- [ ] Form
	- [ ] GingerbreadUtil
	- [ ] ImagePicker
	- [ ] PhoneCall
	- [ ] PhoneCallUtil
	- [ ] ReplForm
	- [ ] Sharing
	- [ ] SmsBroadcastReceiver
	- [ ] SplashActivity
	- [ ] Spreadsheet
	- [ ] SpeechRecognizer
	- [ ] Twitter
	- [ ] WebViewActivity

I also tested with the BLE and micro:bit extensions to ensure that the changes to dynamic code loading didn't break extensions.

### CODE REVIEW

**Comment by ewpatton** [comment]
Some other notes:

- I've only tested this on a Apple Silicon Mac. The updated binaries for the build tools may not run on Intel Macs.
- I have not tested the Windows/Linux build tools.
- Testing has occurred on a Google Pixel 6a running Android 14. I haven't tested for breaking changes on earlier Android versions (particularly, something below SDK 14 given the newer libraries).

**Comment by ewpatton** [comment]
@AppInventorWorkerBee retest this please

**Comment by ewpatton** [comment]
@jisqyv I've updated some testing resources, which solved many of the test failures. Map-related tests still seem to fail, so I've disabled those for now while testing manually.

**Review by jisqyv — APPROVED** [review]
LGTM

**Pull request merged**
