### PR TITLE
Fix typo in title for Extensions doc

### PR DESCRIPTION
**Pull request by halatmit**

### CODE REVIEW

**Comment by jisqyv** [comment]
@halatmit @afmckinney LTGM. However I'm putting this on hold because I am in the middle of merging api4, ucr and master together. Once that work is complete, I will place this commit on "top" before the release.

**Comment by halatmit** [comment]
Sounds fine. Merge well.

**Comment by jisqyv** [comment]
@halatmit I also updated the length of the iframe to avoid the second scroll bar. Change on Gerrit now as we put the release together.

**Comment by halatmit** [comment]
Thanks for noticing that and fixing.




== Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.
MIT Media Lab, Second Class Faculty


On Tue, Aug 11, 2015 at 12:49 PM, Jeffrey Schiller <notifications@github.com

**Pull request closed without merging**
