### PR TITLE
Updatedoc

### PR DESCRIPTION
**Pull request by jisqyv**
This change is three commits (as of initial posting). The first is to update the header/footer of the embedded documentation to put us in sync with the website.

The second updates build.xml to use the bundler instead of calling Jekyll directly. This eliminates warnings on my machine. Evan: Make sure I didn't break it for you.

The third is just the build of the documentation with the updated header and footer.

### CODE REVIEW

**Comment by jisqyv** [comment]
@ewpatton The Jenkins barfed on my bundler change. I'll poke at it a bit more. I may wind up putting the ruby Gems into the sources if they don't take up too much space. That way people can build the documentations (I hope) without regard to what version of the Gems happened to be installed on their system.

**Comment by ewpatton** [comment]
Maybe we should put a Gemfile and have Jenkins run `gem install` prior to running ant? This way we don't need to keep it in the sources (although I know that hasn't been our policy re. dependencies).

**Comment by ewpatton** [comment]
Never mind, I see you included the lock file.

**Comment by pavi2410** [comment]
Can we use https://jbake.org/ instead?

**Comment by ewpatton** [comment]
@pavi2410 We'll consider it, but we also use Jekyll for generating https://appinventor.mit.edu and so using Jekyll here ensures that we know the output should be consistent with what we get on the website. Using a different technology may introduce subtle differences and every update of either technology will require us to recheck it.

**Pull request merged**
