### PR TITLE
Make App Inventor target Android SDK 28 (Pie 9.0)

### LINKED ISSUE #1691: Upgrade to target SDK 27
We need to upgrade everything to support SDK 27 before Aug 1st.

### PR DESCRIPTION
**Pull request by ewpatton**
Resolves #1691

Change-Id: Id830f9bad0ff873a8df6ddc29c58e24e98fae452

### CODE REVIEW

**Comment by ewpatton** [comment]
This is a first pass at updating the Android SDK from 26 to 27. Based on my reading of the Android documentation, it seems like we won't need to do much of anything other than upgrade all of the corresponding support libraries. So far I have tested this companion on my phone (Android 7.1.2) and in the macOS emulator (Android 5.1.1). Once the bugfix release goes out this should go up on ai2-test.

**Comment by NmdOfficial** [comment]
Its not recommended to use mixed versions.
You should only one version number instead of support libs 26 and 27.
By the way.. why not switch direct to android x libs?

Support v28 is the last one. Google cancled updates in it.
After it there will be only android x future support.

**Comment by ewpatton** [comment]
@NmdOfficial Which ones did I miss? I thought I updated everything to 27.

**Comment by NmdOfficial** [comment]
After a second look it looks all okay.
Maybe I had overseen something.

What about my other questions fact that the support libs are deprecated without future support after v28?
Would it not be better to switch to android x?

**Comment by ewpatton** [comment]
@NmdOfficial It's a logistical thing. The Aug 1 deadline for apps to target SDK 27 is also the start of the MIT App Inventor Summit. Since we're in the middle of planning an all hands on deck event, we don't want to be making more changes than necessary to be compatible with Play Store requirements. Bumping target SDK by more than one version will introduce potentially unnecessary bugs we'd have to try and squash while taking away effort from polishing the stuff we want to demo at the summit.

**Comment by ewpatton** [comment]
@AppInventorWorkerBee test this please

**Pull request merged**
