### PR TITLE
Enable multiple component selection using shift key presses

### PR DESCRIPTION
**Pull request by matthewcoufal**
This PR allows for users to copy properties from one component to another using the shift key. Here is how it works:
- user selects a component and then clicks on another component while pressing the shift key
- both of the selected components are highlighted, all properties that the two selected components share show up on the design properties panel, and the label for the design properties panel becomes `(number of components selected) components selected` (which is `2 components selected` in this case)
- all property value changes in the updated properties panel are applied to all selected components (f.e. setting the background color property to blue in the panel sets the background color to blue for all selected components)

This tackles issue https://github.com/mit-cml/appinventor-sources/issues/1887.

### CODE REVIEW

**Comment by AppInventorWorkerBee** [comment]
Can one of the admins verify this patch?

**Comment by kkashi01** [comment]
This is good, but it would be great to have some kind of confirmation dialog first, allowing user to confirm or cancel out

**Comment by ewpatton** [comment]
@matthewcoufal I was thinking of a different workflow in #1887, mainly that shift-clicking would select the components and we would update the properties panel to only show in-common properties among all the selected components. At this point, if the user changes the value of a property it would collectively change it for all selected components. This as described sounds more like the "format paintbrush" feature of editors like Microsoft Word, which I'm not opposed to, but are a different UX than what I thought we would start with.

**Comment by ewpatton** [comment]
@matthewcoufal Thanks. Make the changes and then let us know when you're ready for another review. Ping me on hangouts if you have any questions.

**Comment by matthewcoufal** [comment]
@ewpatton @SusanRatiLane I refactored my changes to achieve the functionality you mentioned above, so this is ready for another review.

**Comment by SusanRatiLane** [comment]
@matthewcoufal Could you step me through the workflow here? My first attempt to select multiple components using Shift on Chrome didn't seem to work.

**Comment by matthewcoufal** [comment]
@SusanRatiLane Click on a component, then click on another component while holding the shift key, and you should see `Multiple Components` show up as the new label for the designer properties panel. The properties in that panel constitute the property intersection of the two components that you clicked. If you then change the background color in the properties panel, for example, then that background color should be set for both components that you clicked.

**Comment by SusanRatiLane** [comment]
OK, I got it. It worked as I expected, but I was looking for a different confirmation. The "Multiple Components" header is pretty subtle, and the selected item highlight only displays on the last item clicked. Is there a way to select-highlight all the selected items?

Right now, I can't tell how I would know how many items I have selected.

**Comment by matthewcoufal** [comment]
@SusanRatiLane Good point! That seems to be a user experience issue. I will investigate to see if I can leave the highlight for all selected components.

**Comment by ewpatton** [comment]
@matthewcoufal In addition to keeping the highlight, maybe you could make it so the title was "n component(s) selected" rather than "Multiple components"?

**Comment by matthewcoufal** [comment]
@ewpatton Sure! I will do both of those and will let you know when I am ready for another review.

**Comment by matthewcoufal** [comment]
@ewpatton @SusanRatiLane I am ready for another review. Thanks!

**Comment by SusanRatiLane** [comment]
@AppInventorWorkerBee Ok to test

**Comment by matthewcoufal** [comment]
@SusanRatiLane I agree. Will add that functionality and let you know when I'm ready for another review.

**Comment by matthewcoufal** [comment]
@SusanRatiLane Just added the functionality that you mentioned, so this is ready for another review. Thanks!

**Comment by SusanRatiLane** [comment]
@matthewcoufal  OK, one more thing, and I think I'm done picking. After selecting multiple components, clicking an already-selected component while holding shift should unselect it.

**Comment by matthewcoufal** [comment]
@SusanRatiLane @ewpatton Just added that final piece of functionality, so this is ready for another review. Thanks!

**Pull request merged**
