### PR TITLE
OTG Input Device Support

### PR DESCRIPTION
**Pull request by rsthomp**
My original proposal [here](https://groups.google.com/forum/#!topic/app-inventor-open-source-dev/i5fGUtLCH_0), along with example app code. I've exported to appspot, but I don't have a server on which to run my implementation, and I'm not clear on how to get one,  but if anyone could point me toward more information, I'll get one set up ASAP.

Edited implementations of onKeyUp and onKeyDown in Form, and added new methods to dispatch key and motion events from an OTG input device to a component handler rather than the general android handler. I implemented an OTG Gamepad component to test this, but the changes made should support components for any OTG input device.

### CODE REVIEW

**Comment by jisqyv** [comment]
@RachaelT Your change is built on top of an older version of the system. You should either merge our master branch into your change, or rebase your change on top of our current master branch. Then test to make sure your code still works.

Also, some of your commits seem to back out other changes made to the system. Make sure only your changes are in your PR and do not back out other system changes.

-Jeff

**Comment by RachaelT** [comment]
@jisqyv Ok, I rebased the changes, tested, and tried to fill in the missing changes so it's all up-to-date.

**Comment by jisqyv** [comment]
@RachaelT Note: The build binaries are still part of this change. We cannot merge it with the binaries in there.

**Comment by RachaelT** [comment]
Sorry, I had an issue with the gitignore when trying to merge changes. It should be fixed now.

**Comment by moliata** [comment]
It seems like a nice proposal, great job for a first time contributor.

**Comment by ewpatton** [comment]
We now have the Serial component. It should be investigated whether that addresses the original need for OTG. This PR has over 5000 files in it and just won't be mergable in its current state.

**Pull request closed without merging**
