### PR TITLE
fix regression due to compiler refactor

### PR DESCRIPTION
**Pull request by pavi2410**
General items:

- [ ] I have updated the relevant documentation files under docs/
- [ ] My code follows the:
    - [ ] [Google Java style guide](https://google.github.io/styleguide/javaguide.html) (for .java files)
    - [ ] [Google JavaScript style guide](https://google.github.io/styleguide/jsguide.html) (for .js files)
- [x] `ant tests` passes on my machine

If your code changes how something works on the device (i.e., it affects the companion):

- [ ] I branched from `ucr`
- [ ] My pull request has `ucr` as the base

Further, if you've changed the blocks language or another user-facing designer/blocks API (added a SimpleProperty, etc.):

- [ ] I have updated the corresponding version number in YaVersion.java
- [ ] I have updated the corresponding upgrader in YoungAndroidFormUpgrader.java (components only)
- [ ] I have updated the corresponding entries in versioning.js

For all other changes:

- [x] I branched from `master`
- [x] My pull request has `master` as the base

What does this PR accomplish?

*Description*

Fixes # .

Resolves # .

### CODE REVIEW

**Comment by pavi2410** [comment]
https://github.com/mit-cml/appinventor-sources/blob/ec1e463c9b7f819d00bd38b6774c9664d58fc80f/appinventor/buildserver/src/com/google/appinventor/buildserver/context/AndroidPaths.java#L29

In this line, the drawable dir is set relative to the `build` dir, but before the refactor, it was relative to `build/res` dir.

image

**Comment by ewpatton** [comment]
@pavi2410 What are the conditions to trigger this? Do you have a test project?

**Comment by pavi2410** [comment]
> @pavi2410 What are the conditions to trigger this? Do you have a test project?

I am working on integrating the compiler refactor to Kodular codebase and this regressions were caught when building the companion app. I verified the changes with the App Inventor codebase before and after the refactor and thought to create the PR. I do not have minimal reproducible example.

**Review by ewpatton — APPROVED** [review]
LGTM

**Pull request merged**
