### PR TITLE
Disallow string->number on strings that contain L or l

### PR DESCRIPTION
**Pull request by halatmit**

### CODE REVIEW

**Comment by halatmit** [comment]
do not review yet.   I need to install Evan's better method.

**Comment by ewpatton** [comment]
Currently leaning toward taking this solution, slightly modified with more characters that also exhibit similar behavior with Kawa, so as to maintain an expectation that string primarily numbers with a single non-E character are not magically parsed as numbers.

**Comment by halatmit** [comment]
@evan: Is this pull request now obsolete?

**Comment by ewpatton** [comment]
@halatmit I think we can close it for now. The patch we made to Kawa seems to have addressed the issue for now.

**Pull request closed without merging**
