### PR TITLE
Update Dutch translations

### PR DESCRIPTION
**Pull request by bartmathijssen**
While working on other issues I noticed that some strings were not translated to Dutch. This change adds translations for strings that did not have Dutch translations before, while also updating some existing translations.

### CODE REVIEW

**Comment by AppInventorWorkerBee** [comment]
Can one of the admins verify this patch?

**Comment by ewpatton** [comment]
@AppInventorWorkerBee ok to test

**Comment by ewpatton** [comment]
@SusanRatiLane I'm assigning this one to you since it will also feed into your work on a new translation system now that Google's shuttering Translate Toolkit.

**Comment by SusanRatiLane** [comment]
@bartmathijssen It is great to have a translation update.

As Evan mentioned, Google is shutting down Google Translator Toolkit in December (without much warning). I'm looking at setting up something new with gitlocalize. If you're interested in working with me on that workflow, I would be deeply grateful.

**Comment by bartmathijssen** [comment]
@SusanRatiLane I am interested in working with you on that workflow, just let me know how I can help.

**Comment by bartmathijssen** [comment]
@SusanRatiLane I have been thinking about what the best way to translate App Inventor is for some time now. I found different systems that would provide continuous localization and GitLocalize is one of them, unfortunately it doesn't support the .properties file format. So while looking for different options I found Weblate. Weblate can be self-hosted, this way there are no restrictions to what functionality you may or may not have. 

https://weblate.org/

**Comment by SusanRatiLane** [comment]
@bartmathijssen I was looking to convert in and out of the .properties format. Most alternatives I found were commercial and priced prohibitively or else didn't provide features we need.

Weblate doesn't look familiar. I'll look into it ASAP.

**Comment by SusanRatiLane** [comment]
Some bits that were not in the OdeMessages file that could use a translation:

# Description: User Interface Switch component
appengine.switchComponentPallette=Switch

SwitchHelpStringComponentPallette=Toggle switch that raises an event when the user clicks on it. There are many properties affecting its appearance that can be set in the Designer or Blocks Editor.

TrackColorActiveProperties=TrackColorActive

TrackColorActivePropertyDescriptions=Color of the toggle track when switched on

TrackColorInactiveProperties=TrackColorInactive

TrackColorInactivePropertyDescriptions=Color of the toggle track when switched off

# Description: Storage CloudDB
cloudDBComponentPallette=CloudDB

CloudConnectedMethodDescriptions=returns True if we are on the network and will likely be able to connect to the CloudDB server.

CloudConnectedMethods=CloudConnected

CloudDBErrorEventDescriptions=Indicates that an error occurred while communicating with the CloudDB Redis server.

CloudDBErrorEvents=CloudDBError

CloudDBHelpStringComponentPallette=Non-visible component allowing you to store data on a Internet connected database server (using Redis software). This allows the users of your App to share data with each other. By default data will be stored in a server maintained by MIT, however you can setup and run your own server. Set the "RedisServer" property and "RedisPort" Property to access your own server.

# Description: Maps FeatureCollection
featureCollectionComponentPallette=FeatureCollection

FeatureCollectionHelpStringComponentPallette=A FeatureCollection contains one or more map features as a group. Any events fired on a feature in the collection will also trigger the corresponding event on the collection object. FeatureCollections can be loaded from external resources as a means of populating a Map with content.

**Pull request merged**
