### PR TITLE
Fix blockly context menu not hiding itself

### PR DESCRIPTION
**Pull request by BeksOmega**
### Resolves

Closes: #2082 

### Description

Adds an a click listener to every button I thought could conflict with the blocks editor context menu. The click handler calls hideChaff() to hide any blockly UI.

Specific buttons are:
Buttons
Buttons2
The project buttons get the callback, because their toolbar inherits from Toolbar. But there are no adverse affects from adding the callback.

This also eliminates some code duplication in how buttons are created.

### Testing
Hiding

### Additional Info

I haven't done Java in a while, so please tell me if there's anything I can improve!

### CODE REVIEW

**Comment by ewpatton** [comment]
@BeksOmega I'm still wondering if maybe there's a more general way to do this, especially seeing as we are planing to update the UI. A general solution not tied to the particulars of the UI elements would give us more flexibility and reduce the chances of reintroducing the bug.

**Comment by BeksOmega** [comment]
@ewpatton as far as I know, that's not going to be possible. Blockly Core attempted to fix this by adding a listener to the document. But both attempts had problems:
* https://github.com/google/blockly/pull/2286 caused context menus to not receive clicks.
* https://github.com/google/blockly/pull/2359 caused clicks in generally to be dropped, among other things.

The [recommended solution](https://github.com/google/blockly/issues/2066#issuecomment-507423263) is to do what I've done above :/ But there might be something in gwt that I'm not aware of that would allow it to be fixed more generally.

Note that I've also tried to reopen the [issue](https://github.com/google/blockly/issues/2066) in Blockly Core (since they should have complete control of the event handling now that closure UI is gone) but I've gotten no response.

**Comment by ewpatton** [comment]
@BeksOmega Here's the patch I came up with. Do you have a good sense of the problems Blockly encountered with something like this?

```javascript
diff --git a/appinventor/blocklyeditor/src/blocklyeditor.js b/appinventor/blocklyeditor/src/blocklyeditor.js
index 336e5e2334..ac3d920675 100644
--- a/appinventor/blocklyeditor/src/blocklyeditor.js
+++ b/appinventor/blocklyeditor/src/blocklyeditor.js
@@ -576,3 +576,16 @@ window['Blockly'] = Blockly;
 top['Blockly'] = Blockly;
 window['AI'] = AI;
 top['AI'] = AI;
+
+top.document.addEventListener('mousedown', function(e) {
+  if (e.target) {
+    var target = e.target;
+    while (target) {
+      if (target.className == 'blocklyWidgetDiv' || target.classsName == 'blocklySvg') {
+        return;
+      }
+      target = target.parentElement;
+    }
+    Blockly.hideChaff();
+  }
+}, false);
```

**Comment by BeksOmega** [comment]
@ewpatton I did a bunch of testing and it looks great! This shouldn't have any problems with context menus because of the classname checks. And it shouldn't have problems with dropping clicks because it is bound to mousedown, not mouseup.

Only thing that could change is switching:
```
if (target.className == 'blocklyWidgetDiv' || target.classsName == 'blocklySvg')
```
to:
```
if (target.className.indexOf('blocklyWidgetDiv') != -1 ||
    target.classsName.indexOf('blocklySvg') != -1)
```
b/c in future versions of blockly those elements have additional classes based on the renderer and theme. But idk if that is a priority or not.

So how would you like to handle this?
A) I close this PR and you put up one for your patch.
B) I close this PR and I put up one for your patch.
C) I modify this PR to contain your patch.

**Comment by ewpatton** [comment]
@BeksOmega You're welcome to just modify this PR to use the new code. Might I suggest that in order to deal with the newer versions of Blockly we test on `target.classList` instead? It's a collection so one can do `target.classList.contains('blocklySvg')`

**Comment by BeksOmega** [comment]
Ok @ewpatton I tested, and I believe this is ready for another look.

I went ahead and reverted #1940 as well, since your fix covers those cases. But if you want me to add it back just shout hehe.

**Comment by ewpatton** [comment]
@BeksOmega I'd rather not revert that change, just in case. I know people have done things with mapping keyboard shortcuts to activating certain parts of the UI, so if they are doing that the hideChaff call will still work seeing as we're binding to mousedown in this fix.

**Comment by BeksOmega** [comment]
@ewpatton I have un-reverted the reversion!

**Pull request merged**
