### PR TITLE
Tutorial Tab added

### PR DESCRIPTION
**Pull request by doburaimo**
The tutorial tab has been added to the gallery

### CODE REVIEW

**Comment by doburaimo** [comment]
@jisqyv @wolberd Added a tutorial tab to the gallery.

**Comment by doburaimo** [comment]
http://appinventor2-1023.appspot.com/
is the link to my appengine test site.

**Comment by jisqyv** [comment]
@doburaimo @wolberd I'm acknowledging your PR. We won't have time to look at it until next week, we are currently getting ready to release the "Responsive" version of App Inventor, which is a bit of work for now!

-Jeff

**Comment by wolberd** [comment]
Thanks, Jeff and understood. We'll continue with some other changes and
touch base next week.

Dave

**Comment by jisqyv** [comment]
New version coming...

**Pull request closed without merging**
