### PR TITLE
Fix Camera filename ending in PNG, not JPG

### PR DESCRIPTION
**Pull request by ewpatton**
Change-Id: Ibe479cf038d00229c84f0ee394730e42aef469e6

### CODE REVIEW

**Comment by ewpatton** [comment]
@daki7711 I've assigned this to you to review. Approve, but don't merge, if it looks good.

**Review by daki7711 — APPROVED** [review]
Seems like a simple change LGTM

**Comment by jisqyv** [comment]
@ewpatton Does the Camera always create a jpeg, on all devices?

**Comment by jisqyv** [comment]
@ewpatton Answering my own question... Looks like we ask for a jpeg in the intent. I'm going to merge this change and put it in today's update of ai2-test

**Pull request merged**
