### PR TITLE
Fix bug when scrollbar invisible

### PR DESCRIPTION
**Pull request by E-Hon**
@halatmit 

Please read the doc for details. If this change is a go, a new commit will be made so that the doc will not stay in master branch.

### CODE REVIEW

**Comment by E-Hon** [comment]
**Description**
http://youtu.be/bmqnF0EFpP8

**Test environment**
* OSX Yosemite 10.10.2
* Firefox 35.0.1
* Chrome 40.0.2214.111
* Safari 8.0.3

**Step(s) to reproduce**
1. Open any drawer
2. Resize the window so that the vertical scrollbar is invisible, i.e. all content can be shown without scrolling
3. Scroll the drawer

**Expected outcome**
1. The content is not scrolled

**Actual outcome**
1. The content is scrolled to the bottom

**Related file(s)**
1. appinventor-sources/appinventor/lib/blockly/src/core/scrollbar.js

**Root cause**
In related file 1, Blockly.Scrollbar.prototype.set(value) does not constrain the knob value, leading to a negative value being set to the y attribute of svgKnob_
Imgur

**Solution**
Use the contrainKnob_() function, which is also used elsewhere in the class to prevent from setting negative value to the x, y attribute of svgKnob_, to constrain the value

**Comment by halatmit** [comment]
Please put up a test server where we can check it.
Have you tested this on Firefox, Chrome, and Safari?

**Comment by E-Hon** [comment]
Yes, I have tested it on them. The y value in the root cause was also
corrected.

I am going to merge those branches into one and put the instance to
appspot.com. Please allow me some time to go through the materials.

**Comment by E-Hon** [comment]
You may try this change here.
http://ai2newfeatures.appspot.com

**Comment by halatmit** [comment]
@afmckinney @jisqyv 
LGTM

**Comment by jisqyv** [comment]
@E-Hon LGTM, Will squash and merge.

**Comment by jisqyv** [comment]
MERGED!

**Comment by E-Hon** [comment]
THX!!!

**Pull request closed without merging**
