### PR TITLE
WIP: Upgrade to D8 compiler

### PR DESCRIPTION
**Pull request by pavi2410**
Docs & Res:
- https://android-developers.googleblog.com/2017/08/next-generation-dex-compiler-now-in.html
- https://r8.googlesource.com/r8/+/master/
- https://developer.android.com/studio/write/java8-support
- https://proandroiddev.com/the-d8-dexer-6736deb55fb8
- https://developer.android.com/studio/command-line/d8
- https://jakewharton.com/androids-java-8-support/

### CODE REVIEW

**Comment by pavi2410** [comment]
>   [java] Error: **Cannot fit requested classes in a single dex file. Try supplying a main-dex list.**
     [java] # methods: 88939 > 65536
     [java] Compilation failed
     [java] Nov 21, 2018 3:04:48 PM com.google.appinventor.buildserver.Compiler runD8
     [java] WARNING: YAIL compiler - D8 execution failed.

@ewpatton Can you please help me in building a main-dex list?

**Comment by jisqyv** [comment]
@pavi2410 @ewpatton I'm opposed to this change for now. I experimented with using d8 while working on the WebRTC code. It wasn't much of an improvement, and I suspect it generates code that will not run on older devices. The real work to upgrade to d8 isn't putting the jars in the source tree and getting things to compile, it is the extensive testing that needs to be done. This will take significant resources which we currently do not have to spare.

**Comment by AppInventorWorkerBee** [comment]
Can one of the admins verify this patch?

**Comment by pavi2410** [comment]
@jisqyv Can you please reconsider this PR? I hope the following links may help you see the improvements which D8 brings to the table over dx
https://jakewharton.com/androids-java-8-support/
https://jakewharton.com/androids-java-9-10-11-and-12-support/
https://jakewharton.com/avoiding-vendor-and-version-specific-vm-bugs/
https://jakewharton.com/d8-optimizations/

**Comment by jisqyv** [comment]
@pavi2410 Does the code produced by the d8 compiler run on Android 2.2 (Froyo)?

**Comment by pavi2410** [comment]
Indeed, it supports all of the API levels starting from 1 (the default min API level)
Source: https://r8.googlesource.com/r8/+/refs/heads/master/src/main/java/com/android/tools/r8/utils/AndroidApiLevel.java

**Comment by pavi2410** [comment]
Can this PR be reopened? I am starting to work on this again as I am gaining some success by having generated main-dex-list. Also, I want to keep the discussions in place.

**Pull request closed without merging**
