### PR TITLE
Implement per-component tooltips on collison

### PR DESCRIPTION
**Pull request by ewpatton**
Tooltips can be internationalized but the way it was implemented results in oddities when multiple components share event/method/property names. This change detects collisions in tooltip content and falls back to a scheme that addresses tooltips by including the component name as well.

Note that this PR isn't complete as it will require updating the Korean and Polish translation files, which are the only two that include tooltip translations. Once we approve the code I can script updating the translation files to duplicate those entries that are now split.

Change-Id: I5778d0ddad1a34c1019645478fb6061d88acea10

### CODE REVIEW

**Comment by SusanRatiLane** [comment]
Now the Pedometer methods have tooltips about counting steps rather than video playback. Hurrah.

**Comment by SusanRatiLane** [comment]
@ewpatton As far as I can tell, the tooltips always appear in English now, even if there is no collision. Is this expected?

**Comment by ewpatton** [comment]
@SusanRatiLane AFAIK, we don't have any tooltip translations at this time, so yes they should all appear in English. Are you saying that if you provide a translation for another language, e.g. Spanish, you still get the English tooltip? I thought I had tested this but maybe I am mistaken.

**Comment by SusanRatiLane** [comment]
@ewpatton I meant that in Polish and Korean, all the tooltips on component blocks were appearing in English, whether or not there was a collision.

**Comment by ewpatton** [comment]
@SusanRatiLane The latest commit fixes the issue of Polish and Korean translations not appearing, but it will only do so for situations where there aren't collisions in the tooltip. Fixing that still requires updating the properties files to reflect the new keys.

**Pull request merged**
