### PR TITLE
Fix String comparisons

### PR DESCRIPTION
**Pull request by kkashi01**
Fixing String comparisons

### CODE REVIEW

**Comment by AppInventorWorkerBee** [comment]
Can one of the admins verify this patch?

**Comment by ewpatton** [comment]
@Amerkashi Was the lib/blockly change intentional?

**Comment by kkashi01** [comment]
On mobile. Will check in an hour and reply

**Comment by kkashi01** [comment]
Still on mobile. I just went through entire project and applied updates. Revert blocky?

**Comment by kkashi01** [comment]
@ewpatton That was not intentional and not sure how it got there. How can I revert those?

image

**Comment by kkashi01** [comment]
Closing this one because don't really know how the blocky files were committed. Opened new one:

https://github.com/mit-cml/appinventor-sources/pull/1968

**Pull request closed without merging**
