### PR TITLE
Improve Clock component: time calculation and conversion, documentation, including unit test update

### PR DESCRIPTION
**Pull request by graceRyu**
I added methods to add duration to instants and convert them to different time units. These changes are based on the initial proposal for improving the Clock component. 

Here is the original proposal: 
https://docs.google.com/document/d/1pSwuMDPqS4up27dMtWB_4ZoDXJ9k4T8K3rkOwPwOB9E/edit?usp=sharing

Here is the instance: http://improveclock.appspot.com/

Here is the user-level document: 
https://docs.google.com/document/d/12syiWHz6owfWxnpwbuEjCABt18h3QF0EEpRQpz2hDkU/edit?usp=sharing

@ram8647 @fturbak @halatmit

### CODE REVIEW

**Comment by halatmit** [comment]
Very nice!    I think Ralph should review this.

**Comment by ram8647** [comment]
I'll try to do it Sun AM. Then I'm heading to TX for the CSTA mtg for a few
days.

-- ralph

**Comment by graceRyu** [comment]
The changes in this pull request are more useful and testable with the
DatePicker and TimePicker instant getters/setters. Thus, I made another
instance and an example project. This instance includes both the changes
made in the pull request #449
<https://github.com/mit-cml/appinventor-sources/pull/449>

Here is the instance:http://grace-ai2.appspot.com

aia file is attached at the bottom

--Grace

**Comment by ram8647** [comment]
LGTM  but Lyn should probably take a look at this too because the procedures added to the Clock component in this change were suggested by him.  

I also tested this with the already merged changes to TimePicker and DatePicker.  It works as advertised.  

This change adds several additional Duration procedures to the Clock component. Currently the Clock component has Duration(start, end), where start and end are instants.   This change adds DurationToDays(duration),  DurationToHours(duration), DurationToMinutes(duration), DurationToSeconds(duration), and DurationToWeeks(duration).  These are especially useful for interacting with the DatePicker and TimePicker components.   Grace's documentation provides an example.

**Comment by halatmit** [comment]
@ram8647 
We'll need to add documentation when this is released.  Let me know when this is all done and send me a link to Grace's documentation.   We should proabably put that out as 'working with time" under reference->other

**Comment by ram8647** [comment]
@halatmit, @graceRyu, @fturbak, @jisqyv

Grace has already done the documentation.  The link is here: https://docs.google.com/document/d/12syiWHz6owfWxnpwbuEjCABt18h3QF0EEpRQpz2hDkU/edit?usp=sharing

**Comment by halatmit** [comment]
@afmckinney @jisqyv 
@fturbak @graceRyu @ram8647 
LYNN is there any reason not to go ahead a merge this now?
I'll move the documentation to the web site (under Reference -> Other)

**Comment by halatmit** [comment]
@fturbak Lynn, please respond to the question from August 1 so we can go ahead with this, if you approve.

**Comment by halatmit** [comment]
@fturbak PTAL

**Comment by halatmit** [comment]
@fturbak 
@afmckinney 
@jisqyv 
@ram8647 
@graceRyu 

Is someone going to review/merge this?

**Comment by jisqyv** [comment]
I'll look at it.

-Jeff

On Thursday, January 7, 2016, hal <notifications@github.com> wrote:

> @fturbak <https://github.com/fturbak>
> @afmckinney <https://github.com/afmckinney>
> @jisqyv <https://github.com/jisqyv>
> @ram8647 <https://github.com/ram8647>
> @graceRyu <https://github.com/graceRyu>
>
> Is someone going to review/merge this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mit-cml/appinventor-sources/pull/460#issuecomment-169776045>
> .
>


-- 
_______________________________________________________________________
Jeffrey I. Schiller
Information Systems and Technology – MIT App Inventor
Massachusetts Institute of Technology
77 Massachusetts Avenue  Room 32-386
Cambridge, MA 02139-4307
617.910.0259 - Voice
jis@mit.edu
http://jis.qyv.name
http://appinventor.mit.edu
_______________________________________________________________________

**Comment by jisqyv** [comment]
@graceRyu @ram8647 @halatmit I am concerned about the hardcoded english strings in components.js (the dropdown menu). Those strings need to be internationalized. YET the XML versions need to be standardized (not internationalized). The Clock component version needs to be incremented along with YaVersion.YOUNG_ANDROID_VERSION and appropriate upgraders need to be supplied. Also requires master to be merged in and conflicts fixed.

**Comment by fturbak** [comment]
@graceRyu @ram8647 @halatmit @jisqyv Is anyone working on the problems with this raised by Jeff. I can help knock this off in the next few days if no one else is working on it.

**Comment by ram8647** [comment]
Hi Lyn,

I think Grace is in Korea and may not be in a position to work on this.
And I don't have time at the moment either.

That would be great if you could finish that up.

-- ralph

**Comment by jisqyv** [comment]
I was planning on finishing this one up before the next component release.

-Jeff

On Thursday, January 14, 2016, Ralph Morelli <notifications@github.com>
wrote:

> Hi Lyn,
>
> I think Grace is in Korea and may not be in a position to work on this.
> And I don't have time at the moment either.
>
> That would be great if you could finish that up.
>
> -- ralph
>
> On Thu, Jan 14, 2016 at 3:49 PM, Franklyn Turbak <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> wrote:
>
> > @graceRyu <https://github.com/graceRyu> @ram8647
> > <https://github.com/ram8647> @halatmit <https://github.com/halatmit>
> > @jisqyv <https://github.com/jisqyv> Is anyone working on the problems
> > with this raised by Jeff. I can help knock this off in the next few days
> if
> > no one else is working on it.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/mit-cml/appinventor-sources/pull/460#issuecomment-171775293
> >
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mit-cml/appinventor-sources/pull/460#issuecomment-171783271>
> .
>


-- 
_______________________________________________________________________
Jeffrey I. Schiller
Information Systems and Technology – MIT App Inventor
Massachusetts Institute of Technology
77 Massachusetts Avenue  Room 32-386
Cambridge, MA 02139-4307
617.910.0259 - Voice
jis@mit.edu
http://jis.qyv.name
http://appinventor.mit.edu
_______________________________________________________________________

**Comment by jisqyv** [comment]
I have internationalized the code, added and upgraded and fixed some other minor issues. The code is now on Gerrit for final review. Otherwise LGTM

  https://gerrit.appinventor.mit.edu/#/c/1879/

**Comment by jisqyv** [comment]
MERGED (a while ago)

**Pull request closed without merging**
