### PR TITLE
Possible fix for button problem

### PR DESCRIPTION
**Pull request by NmdOfficial**
Fixes hopefully https://github.com/mit-cml/appinventor-sources/issues/1331

### CODE REVIEW

**Comment by NmdOfficial** [comment]
Issue can be watched here:
https://github.com/mit-cml/appinventor-sources/issues/1331

**Comment by ewpatton** [comment]
@NmdOfficial Do you have any way in Makeroid to create new buttons at runtime? I still don't see how this could logically follow in the core components, but if one had the ability to add/remove UI elements (versus simply changing their visibility), then I can imagine a scenario where a button can be clicked but isn't registered in the form environment. This would lead to unregistering the component, and thus causing the `ConcurrentModificationException`. However, in that scenario this fix would not correct the problem. Additional logic for why this is is provided in the comment on #1331.

**Comment by NmdOfficial** [comment]
Yes we have a component which can create buttons at runtime.

**Comment by ewpatton** [comment]
Since we believe that this doesn't affect App Inventor, and we have know way to replicate it in App Inventor, we are going to close this PR.

**Pull request closed without merging**
