### PR TITLE
Configurable links for help, forums, etc

### PR DESCRIPTION
**Pull request by lizlooney**
This will allow FIRST Tech Challenge to specify different urls than MIT, so FTC users won't ask MIT for help.

It looks like a few of the URLs in the code are not the ones actually used for http://ai2.appinventor.mit.edu/. For example, in the code, the "Report an Issue" URL is http://something.example.com, but in MIT App Inventor 2, it actually goes to a URL that quickly redirects to https://groups.google.com/forum/#!forum/mitappinventortest. (It redirects so quickly, that I can't tell what it was.) This pull request uses http://something.example.com for the property value in appengine-web.xml.

Also, the pull request does not (yet) handle the URLs to the companion app specified as COMPANION_UPDATE_URL and COMPANION_UPDATE_URL1 in YaVersion.java. In the code, these are both empty strings, but in MIT App Inventor 2, the Companion Information dialog shows http://ai2.appinventor.mit.edu/companions/MITAI2Companion.apk.

@halatmit

### CODE REVIEW

**Comment by halatmit** [comment]
Liz,

I think what's going on is that there's a step called "branding" that we do
to add MIT specific stuff to the public code.    Jeff or Andrew can explain.

== Hal



== Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.
MIT Media Lab, Second Class Faculty

**Comment by lizlooney** [comment]
Thanks Hal.

I also posted questions about this on App Inventor Open Source Development group:
https://groups.google.com/forum/#!topic/app-inventor-open-source-dev/oP0edlJ5C84
https://groups.google.com/forum/#!topic/app-inventor-open-source-dev/NariailiLIM

@jisqyv @afmckinney

**Comment by halatmit** [comment]
Yes, I saw those questions.

Let's see what Jeff thinks.



== Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.
MIT Media Lab, Second Class Faculty

**Comment by jisqyv** [comment]
@lizlooney @halatmit Sorry to be slow. I like this change and will likely merge it later in the weekend. As Hal mentioned, we've been swamped with the API4 stuff. We'll likely put out a new release to deal with bugs in it later today. Then I can look at this.

Also as Hal mentioned, we handle the branding by having a few commits that have changes specific to MIT. This set of commits is then rebased onto master when we do a release. Your change will reduce the amount of stuff in that commit (we'll just have that commit update appengine-web.xml).

-Jeff

**Comment by lizlooney** [comment]
@jisqyv @halatmit 
Has the API4 stuff settled down yet? Can you maybe please merge this change in to master?
Thanks,
Liz

**Comment by jisqyv** [comment]
@lizlooney Its settled down some, but we still have issues with it (at least we are going to make it through this weekend without 4 or 5 component releases!).

I promise I'll merge this next week.

-Jeff

**Comment by jisqyv** [comment]
@lizlooney Note: I'm changing the document reference and terms of service URL to be relative instead of absolute (pointing at our public service).

**Comment by jisqyv** [comment]
@lizlooney @halatmit @afmckinney LGTM

**Comment by jisqyv** [comment]
@lizlooney MERGED

**Pull request closed without merging**
