### PR TITLE
Update support library for ProguardUpdate build.xml

### PR DESCRIPTION
**Pull request by mishra-kunal**
Update android support library in build.xml, which were used in proguarding the extension.

### CODE REVIEW

**Comment by AppInventorWorkerBee** [comment]
Can one of the admins verify this patch?

**Comment by jisqyv** [comment]
@AppInventorWorkerBee ok to test

**Comment by jisqyv** [comment]
@mishra-kunal Do we know the value of minSdk for this version?

**Comment by mishra-kunal** [comment]
> @mishra-kunal Do we know the value of minSdk for this version?

It's by default of App inventor.

**Comment by jisqyv** [comment]
@mishra-kunal My issue with this change is that it needs to be tested on a wide range of devices and Android versions, starting with Android 2.2 (which we still support). Google tends to ignore versions that old...

**Comment by StormiFire** [comment]
> My issue with this change is that it needs to be tested on a wide range of devices and Android versions, starting with Android 2.2 (which we still support). Google tends to ignore versions that old...

This is why App Inventor should support Android 5 (@ewpatton) at the minimum. Eventually support will discontinue for older Android versions and you will not be able to upgrade dependencies.

**Review by ewpatton — APPROVED** [review]

**Comment by ewpatton** [comment]
After some internal discussion we are going to approve this change. I had to make one minor adjustment due to the conflict in library names, which I have tested with a same extension and confirmed by reviewing the proguarded JAR file.

**Pull request merged**
