### PR TITLE
Fix Marker sizing

### PR DESCRIPTION
**Pull request by ewpatton**
Reported via the [forum](https://community.appinventor.mit.edu/t/marker-imageasset-width-and-height-issue/38089?u=ewpatton) by @kdclang: Marker image does not respect the width/height properties. This PR addresses this issue.

For testing, I loaded kitty.png into a project and set it to be the image of a marker. I adjusted the width and height to be 64px each. The companion properly reflected changing these properties.

### CODE REVIEW

**Comment by ewpatton** [comment]
Note that this change includes the actual fix but also a commit that cleans up the code a bit. If necessary, the head commit can be reverted, but it makes no semantic changes to the code.

**Comment by jisqyv** [comment]
@ewpatton Actually the head commit contains one substation change (call call to setNeedsUpdate), but no matter... It will all get squashed together when merged.

**Comment by ewpatton** [comment]
Whoops. I thought when I rebased I put them in the opposite order...

**Review by jisqyv — APPROVED** [review]
LGTM

**Pull request merged**
