### PR TITLE
Select all projects checkbox

### LINKED ISSUE #2386: Select all projects checkbox
**Describe the desired feature**

[From the forum](https://community.appinventor.mit.edu/t/suggestion-select-all-button-for-managing-projects/24506?u=ewpatton): It is suggested to add a checkbox in the upper left corner of the project list to select all projects, which could be useful for bulk emptying the trash, among other things.

**Give an example of how this feature would be used**

After removing multiple projects from the project list, being able to select all the projects to dump them from the trash would save time when cleaning up projects. For example, if a teacher is clearing out homework assignments.

**Why doesn't the current App Inventor system address this use case?**

One can manually check all the boxes, so this would serve as a convenience.

**Why is this feature beneficial to App Inventor's educational mission?**

This improves the project management process by both students and teachers.

### PR DESCRIPTION
**Pull request by AnujSinghal12**
closes #2386 

**Functionality added :**
1. A new selectAllCheckBox to select all the projects of the current view.
2. If all projects are manually selected, the selectAllCheckBox also gets checked.
3. If selectAllCheckBox is checked and a project is manually deselected, the selectAllCheckBox also gets unchecked.

### CODE REVIEW

**Comment by AppInventorWorkerBee** [comment]
Can one of the admins verify this patch?

**Comment by ewpatton** [comment]
@AppInventorWorkerBee ok to test

**Review by ewpatton — CHANGES_REQUESTED** [review]
Thanks for the change. I think it looks good for the most part but there are a number of code style issues you should address before we can merge this. If you run `ant checkstyle -Dcommit=master`, you should get a report that will tell you what items you need to address.

**Comment by AnujSinghal12** [comment]
Thanks @ewpatton for helping out with the codestyle, will keep that in mind for future PRs! I've made the necessary changes. Please have a look.

**Review by ewpatton — APPROVED** [review]
LGTM

**Pull request merged**
