### PR TITLE
Swedish translations updated based on latest Pootle data

### PR DESCRIPTION
**Pull request by carlrobert**
Jeffrey Schiller should make a sanity check since this is my first PR of these files :)

### CODE REVIEW

**Comment by carlrobert** [comment]
Hi Jeff,
Thanks for your help. Is the problem in the Pull request or elsewhere?
I will ask "my" users to give it a try on ai2-test.

**Comment by jisqyv** [comment]
@carlrobert http://ai2-test.appinventor.mit.edu is ready for you to test against. Let me know if all is well and I can merge this change into the master branch. Once this is done, we are planning a non-component release within a day or so that would include this change.

I made a few changes to your PR to make things work. Later today I'll put a Pull Request in against your repo that will let you see the changes that I made.

**Comment by carlrobert** [comment]
Looks good to me. OK to deploy on master.

**Comment by jisqyv** [comment]
MERGED!

**Comment by carlrobert** [comment]
Hi Jeff,
Two brief follow-up questions:
1. I can't seem to find any changes made to my pull request. Did the files work out as is?
2. For, as yet, non-localized strings, what is the procedure for getting them into Pootle? There a number of items that still need localization based on feedback from my reviewers.

**Comment by jisqyv** [comment]
1) I just added a Pull Request on your "fork" (PR #1) which outlines the
changes I made. You can close it when you like, it is just there for your
information.
2) I'll try to update the English in Pootle later this week (have a few
other things to get done first).

-Jeff

On Saturday, April 16, 2016, Robert Storlind <notifications@github.com>
wrote:

> Hi Jeff,
> Two brief follow-up questions:
> 1. I can't seem to find any changes made to my pull request. Did the files
> work out as is?
> 2. For, as yet, non-localized strings, what is the procedure for getting
> them into Pootle? There a number of items that still need localization
> based on feedback from my reviewers.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/mit-cml/appinventor-sources/pull/743#issuecomment-210828885>
>


-- 
_______________________________________________________________________
Jeffrey I. Schiller
Information Systems and Technology – MIT App Inventor
Massachusetts Institute of Technology
77 Massachusetts Avenue  Room 32-386
Cambridge, MA 02139-4307
617.910.0259 - Voice
jis@mit.edu
http://jis.qyv.name
http://appinventor.mit.edu
_______________________________________________________________________

**Pull request closed without merging**
