### PR TITLE
Make collapsed dictionary constructor look like JSON

### PR DESCRIPTION
**Pull request by ewpatton**
Change-Id: Ie61a8c3d0f11df726885df6ab2015c3bd5b5c7ff

### CODE REVIEW

**Comment by SusanRatiLane** [comment]
Could you write a bit about the motivation for this change?

**Comment by SusanRatiLane** [comment]
@ewpatton @BeksOmega I haven't merged this PR because I wanted to have a conversation on what features increase the intuitiveness of our interface. It's not obvious to me that, in such a small space, the JSON improves the usability of the Dictionary constructor.

It looks like this is now part of a larger conversation in #1964 . How does this change fit into the bigger picture, including renaming collapsed blocks?

**Comment by BeksOmega** [comment]
Hello @SusanRatiLane 

I don't have any particular opinions about this feature. I just linked to this PR because I stole some of the optimizations ewpatton added to `toString` for #2074 hehe

I think it's a cool feature to add! But I'm not sure if it increases usability or decreases it. I imagine it won't have a /huge/ impact either way, because the max collapsed chars is so low you often won't see it:
blocks
blocks (1)
blocks (2)

Still it might be a nice way to introduce students to JSON syntax

I tested this ontop of #2074 and editing the collapsed dictionary updates the text as expected! =)

**Comment by ewpatton** [comment]
@SusanRatiLane 

> It's not obvious to me that, in such a small space, the JSON improves the usability of the Dictionary constructor.

I think this is actually why this change is useful. The string limit for collapsed blocks is pretty small to begin with, so using `make a dictionary key ... value ...` is much longer than `{key: value...`. Odds are, most people will never collapse these blocks to begin with (it tends to be an operation more on event handlers/statements), but I do think it is useful for people to learn the association with JSON as a more collapsed presentation if they do.

**Comment by SusanRatiLane** [comment]
I guess since it's only when the block is collapsed, so they can compare to the expanded block that says explicitly "Make a Dictionary"

**Pull request merged**
