### PR TITLE
attempting to merge changes?!

### PR DESCRIPTION
**Pull request by AlanRosenthal**
mit/master -> isense/updated_ai2

### CODE REVIEW

**Comment by halatmit** [comment]
@fgmart 
@AlanRosenthal @jisqyv @afmckinney @jsheldonmit 
Is there an idea we make this part of MIT App Inventor (for all users)?  We'd need to discuss that.  There might be better ways to accomplish this, but it needs discussion.
Also, does the code in this pull request current work when built on the newest master branch?

**Comment by jsheldonmit** [comment]
I would doubt that the existing version works with current master, but I would imagine Fred can answer that.

My working plan is not to make this available for all users initially, but should we get the grant, to make it an exemplar of the CDK put to use. We’d be able to limit which users get it for the duration of the grant, and over that time, devise a plan for scaling as appropriate.
================
Josh Sheldon
Director of Strategic Programs – MIT App Inventor
Project Manager - MIT Scheller Teacher Education Program
MIT Center for Mobile Learning
20 Ames St., Bldg E15-309
Cambridge, MA 02139
cell: 617-671-5491
work: 617-715-4051

http://appinventor.mit.edu - @MITAppInventor<http://twitter.com/MITAppInventor>
http://education.mit.edu - @mitSTEPlab<http://twitter.com/mitSTEPlab>

**Comment by halatmit** [comment]
Josh,

I've marked this pull request "on hold" and assigned it to you, so you can
keep track and decide when/how to do more on it.




== Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.
MIT Media Lab, Second Class Faculty

**Comment by jisqyv** [comment]
@jsheldonmit @halatmit Note: If we decide to incorporate this feature, we will need a new pull request, which I can provide.

**Comment by fgmart** [comment]
Hi Jeff - Alan told me that this particular pull request was a Git error...
he meant to merge MIT stuff into his branch, not the other way around.

On Sun, Jul 19, 2015 at 10:41 AM, Jeffrey Schiller <notifications@github.com
> wrote:

> @jsheldonmit
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_jsheldonmit&d=AwMCaQ&c=TqceLeU8_c9CVUat-eLTFu19-lyGiWSvB_skZXlxt8Q&r=18cCOnjUNVJkR7XAgiboog&m=1A9iVY2U4uyE8yki3_WFBtc7mq5mLARQECyJC7kZuRI&s=p5OTw20GJFD-q7bDw8AIvcksY416WzUiLSgj7s-8ARg&e=>
> @halatmit
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_halatmit&d=AwMCaQ&c=TqceLeU8_c9CVUat-eLTFu19-lyGiWSvB_skZXlxt8Q&r=18cCOnjUNVJkR7XAgiboog&m=1A9iVY2U4uyE8yki3_WFBtc7mq5mLARQECyJC7kZuRI&s=l3xrwAqb2JYKfM8vqArVx7rwod1jAECV9OrlKB17wDg&e=>
> Note: If we decide to incorporate this feature, we will need a new pull
> request, which I can provide.
>
> —
> Reply to this email directly or view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_mit-2Dcml_appinventor-2Dsources_pull_451-23issuecomment-2D122666748&d=AwMCaQ&c=TqceLeU8_c9CVUat-eLTFu19-lyGiWSvB_skZXlxt8Q&r=18cCOnjUNVJkR7XAgiboog&m=1A9iVY2U4uyE8yki3_WFBtc7mq5mLARQECyJC7kZuRI&s=02gbYwZP-SIAAsjC6sda6Phb5akG3aRpbNAQynUVZos&e=>
> .
>



-- 

Work Ready Life Ready World Ready

Director, Engaging Computing Group <http://www.cs.uml.edu/ecg>
Associate Professor, Computer Science <http://blog.uml.edu/cs>
Director of Student Success, College of Sciences
<http://blog.uml.edu/science>
University of Massachusetts Lowell, 1 University Avenue, Lowell MA 01854
p: 978/934–1964 f: 978/934–2705 email: fredm@cs.uml.edu

**Comment by jisqyv** [comment]
I'm going to close this. We can always revisit it later.

**Pull request closed without merging**
