### PR TITLE
Add numbers to the property values shown in the designer dropdowns fo…

### PR DESCRIPTION
**Pull request by halatmit**
…r alignment, as requested in issue #812

### CODE REVIEW

**Comment by halatmit** [comment]
Issue #813

**Comment by halatmit** [comment]
I added numeric values only to the drop-downs for the alignment properties, not for all properties where we might want this.

**Comment by jisqyv** [comment]
LGTM, moving to Gerrit

**Comment by jisqyv** [comment]
@halatmit MERGED

**Pull request closed without merging**
