### PR TITLE
Backpack

### PR DESCRIPTION
**Pull request by a-suarez**
Added designs for new backpack icon. Updated view and its behavior to use new icons.

@afmckinney @jisqyv

### CODE REVIEW

**Comment by jisqyv** [comment]
@a-suarez Hmmm. When I empty the back pack, it still shows that there are blocks in it. It shrinks, but the blocks (not the real blocks, but the icon with blocks showing) are still there.

**Comment by a-suarez** [comment]
@jisqyv I updated code to fix the 'empty backpack' behavior

**Comment by jisqyv** [comment]
@a-suarez LGTM, moving to Gerrit

**Comment by jisqyv** [comment]
MERGED

**Pull request closed without merging**
