### PR TITLE
Zero divide form

### PR DESCRIPTION
**Pull request by halatmit**

### CODE REVIEW

**Comment by halatmit** [comment]
@jisqyv @afmckinney I think this PR replaces #818 , but please check to make sure.
Also ... this PR mistakenly includes the pull that optimizes building:  changes to YaClient.gwt.xml and replmgr.js.   Please do not merge until these have been restored.

**Comment by jisqyv** [comment]
@halatmit I like this version :-) I still need to test it (and I can remove the debugging commit before merging).

**Comment by jisqyv** [comment]
@halatmit LGTM (as ammended: see: https://github.com/jisqyv/appinventor-sources/commit/ec992d6e978378244165dbc874a7911bcad2ba51). On Gerrit.

-Jeff

**Comment by jisqyv** [comment]
@halatmit MERGED

**Pull request closed without merging**
