### PR TITLE
Add blockly mocha tests to ant

### PR DESCRIPTION
**Pull request by BeksOmega**
### Description

Allows you to write blockly mocha tests that will be run when you run `ant tests`.

This uses the mocha testing library, the chai assertion library, and the mocha-phantomjs library (which lets us run the tests), and their dependencies. Currently the dependencies are obtained using npm. The dependencies take up ~58M of space see [here](https://github.com/mit-cml/appinventor-sources/pull/2074#issuecomment-601829049).

If this is acceptible I will need to create a package.json and update the README to include installation instructions.

It may also be good to write a little README specifically for the mocha testing. Similar to the current README for the blocklyeditor/tests directory.

### Testing
Test1
Test2
Test3

### To Test
1. Install npm.
2. Run the following commands
```
npm install mocha --save-dev
npm install chai --save-dev
npm install mocha-phantomjs --save-dev
```
3. Pull this branch and run `ant tests`.

### CODE REVIEW

**Comment by BeksOmega** [comment]
@ewpatton is the Jenkins pipeline stored in this repo? This is breaking b/c jenkins doesn't have the correct dependencies installed. I think it will be easier to get jenkins to install them, rather than try to get it working through ant.

**Comment by ewpatton** [comment]
@BeksOmega For now you could add the npm call(s) as an `<exec>` task to the blocklyeditor test target.

**Comment by BeksOmega** [comment]
@ewpatton got it working! Tested and it still works locally as well.

**Comment by ewpatton** [comment]
@BeksOmega @jisqyv and I discussed this and our recommendation is to check in the node_modules into the repo and not bother with running npm install prior to the tests. However, on my machine I note that the node_modules directory created is only 15 MB, not 58 MB that you cite. Can you clear out your node_modules and run npm install again to see if you get similar numbers?

**Comment by BeksOmega** [comment]
@ewpatton Yeah I got much less upon deleting and reinstalling. Only 18MB now.

I'll remove the `npm install` call and check the node modules into the repo. Do you want me to remove the package.json as well? Or should it be kept as a record?

**Comment by BeksOmega** [comment]
@ewpatton Looks like the tests succeeded! Local tests work as well.

**Pull request merged**
