### PR TITLE
Change integer division to produce decimals, not rational numbers

### PR DESCRIPTION
**Pull request by halatmit**

### CODE REVIEW

**Comment by halatmit** [comment]
#307
@afmckinney @jisqyv

**Comment by jisqyv** [comment]
@halatmit I'm a little concerned about whether we have projects out there that depend on the current behavior...

**Comment by halatmit** [comment]
Jeff, thanks for being careful.   You are correct.  The issue I was looking at was something else.
Closing this pull request.

**Comment by halatmit** [comment]
This was the wrong fix in any case.  I closed the pull request.



== Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.
MIT Media Lab, Second Class Faculty


On Mon, Mar 16, 2015 at 12:32 PM, Jeffrey Schiller <notifications@github.com

**Comment by halatmit** [comment]
@jisqyv

**Comment by halatmit** [comment]
not ready for review ... needs a bit more ... working on it

**Comment by halatmit** [comment]
@jisqyv @afmckinney 
Changing division uncovered another bug that ListView and the Pickers were displaying floats with Kawa's default precision rather than with the App Inventor precision.  To test this fix, create a ListView and set ListView.Elements to makeList(sqrt 3, (/ 2 17)) and see how this displays. Similarly with ListPicker and Spinner.

**Comment by jisqyv** [comment]
Working on this review now...

**Comment by jisqyv** [comment]
@halatmit LGTM

**Comment by jisqyv** [comment]
MERGED

**Pull request closed without merging**
