### PR TITLE
Upgrade GWT from version 2.5.1 to 2.7

### PR DESCRIPTION
**Pull request by jisqyv**
Change-Id: I3fd171e32f545adec9266df273e4b3c940c5b6ca

### CODE REVIEW

**Comment by jisqyv** [comment]
@halatmit @afmckinney Seems to work!

**Comment by halatmit** [comment]
I don't have an idea how to test this.   So shall we just merge and hold our breath?

**Comment by jisqyv** [comment]
Let's merge it after we do the release, which should be sometime this
evening.

-Jeff

**Comment by halatmit** [comment]
sounds good.



== Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.
MIT Media Lab, Second Class Faculty

**Comment by jisqyv** [comment]
This will likely get merged today, just want to run a few more tests... (given the other changes on the master branch since this pull request was created).

**Comment by jisqyv** [comment]
MERGED

**Pull request closed without merging**
