### PR TITLE
Support fill-opacity/stroke-opacity for map features

### PR DESCRIPTION
**Pull request by rgangela99**
Adds support for fill-opacity and stroke-opacity as properties for map features. #1745

### CODE REVIEW

**Comment by AppInventorWorkerBee** [comment]
Can one of the admins verify this patch?

**Comment by ewpatton** [comment]
@AppInventorWorkerBee ok to test

**Comment by ewpatton** [comment]
@rgangela99 

You will need to rebase the branch onto ucr from master. You can do this by:

```shell
git checkout ucr   # makes sure that we have the ucr branch locally
git checkout map_feature_opacity
git rebase master --onto ucr
```

It should go cleanly. If so, force-push up to GitHub. Otherwise, ping me and we'll get it sorted out.

**Comment by SusanRatiLane** [comment]
More on documentation: Do we know what the scale is for the stroke width properties? Is that thickness in pixels? Also useful to include.

**Comment by ewpatton** [comment]
@SusanRatiLane Yes, StrokeWidth is specified in pixels, but I think any unrelated documentation updates should be in a separate PR.

**Comment by SusanRatiLane** [comment]
OK, then are the opacity properties intended to be implemented for Marker?

**Comment by ewpatton** [comment]
@SusanRatiLane Yes, Opacity should be made to work on Marker as well. Marker has a lot of special cases so it overrides quite a bit of the super implementation. My guess is that @rgangela99 will just need to make some tweaks to the Marker-specific code.

**Pull request merged**
