### PR TITLE
Use PROPERTY_TYPE_TEXTAREA instead of PROPERTY_TYPE_STRING

### LINKED ISSUE #1914: Long text in textfield of textbox or label
**Describe the desired feature**

When i want to add a long text to the about screen textfield i can make the field bigger.

Would it be helpful if we can do the same with the text fields of a textbox and a label in the designer? Those are the components that might have the most text inside of them but now only have one small textfield to put the text inside of it. So editing is difficult.

**Give an example of how this feature would be used**

When learning AI users will use the designer textfields more then in a later stadium where they will learn how to use blocks. 

**Why doesn't the current App Inventor system address this use case?**

Designer textfields are just a single line not a textarea like the about textfield. 

**Why is this feature beneficial to App Inventor's educational mission?**

When learning AI and putting larg amounts of text in the bigger textfield users have a better view of what they are doing. 

This is a list of the designer textfields that could be made into a textarea.

**UserInterface**
Label.Text
TextBox.Text
Spinner.ElementsFromString
ListView.ElementsFromString

**Maps**
LineString.PointsFromString
Polygon.HolePointsFromString
Polygon.PointsFromString
FeatureCollection.FeaturesFromGeoJSON

### PR DESCRIPTION
**Pull request by bartmathijssen**
Resolves #1914

### CODE REVIEW

**Comment by AppInventorWorkerBee** [comment]
Can one of the admins verify this patch?

**Comment by ewpatton** [comment]
@AppInventorWorkerBee ok to test

**Comment by jisqyv** [comment]
Shouldn't this be based on ucr instead of master as it impacts the components on devices.

**Comment by ewpatton** [comment]
Since it’s just changing the property editor shown in the designer, there isn’t an API change that will affect the companion. I think it is safe for master.

**Comment by jisqyv** [comment]
@ewpatton I stand corrected. :-)

**Pull request merged**
