### PR TITLE
Improve designer handling of font sizes in label and button text

### PR DESCRIPTION
**Pull request by osmidy**
Recreation of pull request #212 

@halatmit @jisqyv

### CODE REVIEW

**Comment by halatmit** [comment]
@osmidy @jisqyv @afmckinney 
The button height in the designer doesn't change when you change the fontsize, unlike with labels, where the height does change.   Also unlike the real phone, where the height changes.  You don't need to make what's shown in the designer exactly match the real phone, but it should be a reasonable approximation.  See if you can make the button height in the designer closer to what's on the phone.

**Comment by osmidy** [comment]
@halatmit I've fixed the issue of the Button actually resizing, but now when the font size is less than 10, the button drops out of it's proper position (see border and button positions in attached image). I've tried seeing the problem but can't find it.

scrot

**Comment by halatmit** [comment]
@osmidy @afmckinney @jisqyv 
I won't get a chance to look at this quickly, but we need to bring closure to this since it's been hanging on so long.   I suggest you see how it works if you simply don't try to make the size in the designer less than 10.  If that works ok, but a comment in the code, and file the desired change as a new issue.   I assume that by now there a lot of merge conflict that need to be fixed.   The key thing is to get this out of the queue.

**Comment by osmidy** [comment]
@halatmit @afmckinney @jisqyv 
Haven't seen any conflicts; I've pulled from upstream master without issue.  Should this be closed before filing the new bug?

Other than that, I'm moving on to another ticket.

**Comment by halatmit** [comment]
@afmckinney <https://github.com/afmckinney> @jisqyv
<https://github.com/jisqyv>

You can't close it until it's reviewed.   But I'd treat the small font
thing as a separate issue, unless the review can pick up what's wrong.  Are
you going to take my advice and force a minimum font size (in the designer
only) to avoid the errors.

Andre of Jeff should review this.


== Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.
MIT Media Lab, Second Class Faculty

**Comment by osmidy** [comment]
@halatmit I've added the forced font size, I'm looking at this issue: https://github.com/mit-cml/appinventor-sources/issues/180. I am open to others or different projects.

**Comment by osmidy** [comment]
@halatmit This still needs to be opened up for review.

**Comment by halatmit** [comment]
@afmckinney @jisqyv 
Please review this.

**Comment by halatmit** [comment]
@osmidy 
This looks fine and works for buttons (also DatePicker).
Could you make a similar fix for checkbox?  Right now, if you increase the font size on a checkbox the green "frame" on the designer doesn't change, and width for the field that holds the label does not expand.  See image below:

screen shot 2015-04-18 at 9 07 02 am

**Comment by osmidy** [comment]
@halatmit I don't see an immediate fix (the problems are related, but not exactly the same); it can be made a separate issue.

**Comment by halatmit** [comment]
OK.   I'll file it as a separate issue.




== Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.
MIT Media Lab, Second Class Faculty

**Comment by halatmit** [comment]
LGTM
There's still more that can be done here, for example, when the font gets so large that the text cannot display on one line.
Also, we need to make the analogous fix for checkboxes.
But we can save that for a separate issue.

**Comment by jisqyv** [comment]
@osmidy When I do my testing, a "normal" button (i.e., one where the font size is the default) appears different int he designer. Before this change there is a 3d-ish shadow effect around the button. With this change that is missing.

**Comment by osmidy** [comment]
@jisqyv @halatmit I was attempting to debug the shadow effect, but something is wrong with my machine.  Ant refuses to build my local appinventor with changes to my code; it seems to stick to the initial build made in the directory. I've tried different OS installs and git clones, and ant clean doesn't help either. I've been trying to debug for hours to no avail. I'll be in Monday to fix this ASAP.

**Comment by osmidy** [comment]
@jisqyv @halatmit So my "ant bug" was really just me needing to clear my cache.  The closest I can get to proper button appearance is given by changing line 55 to "buttonWidget.setStylePrimaryName("ode-SimpleMockButton");", which shows up as seen below.

shot

**Comment by osmidy** [comment]
Also, I've gained some insight on the issue for sizes less than 10:  the Deckpanel contains the button, and for some reason when the font size for the button is under 10, it changes it's position . The DeckPanel stays put.

**Comment by osmidy** [comment]
@halatmit @jisqyv Jeff, the shadow is back, but the button still looks a bit different than it does in the current version. Otherwise, functionality seems fine from my testing.

**Comment by jisqyv** [comment]
@afmckinney I'm going to look at this again.

**Comment by moliata** [comment]
@jisqyv did you have any look into this?

**Comment by jisqyv** [comment]
@moliata Turns out I have a simpler fix which will be pushed up as a new PR shortly.

**Comment by moliata** [comment]
@jisqyv that means, this pr will be closed.

**Comment by jisqyv** [comment]
This change is superseded by #929.

**Pull request closed without merging**
