### PR TITLE
Create _messages.js

### PR DESCRIPTION
**Pull request by shush1980**
test adding arabic language

### CODE REVIEW

**Comment by moliata** [comment]
If you are making a pull request. It **must be** not a test. Did you even test this on your own fork? Or just modified code & made a PR. There is a lot of stuff to do. Make OdeMessages for Arabic language, modify YaClient.gwt.xml & etc. Please check whether your pull request works at all...

**Comment by moliata** [comment]
@ewpatton @josmas @afmckinney @jisqyv @jsheldonmit May take a look here too...

**Comment by ewpatton** [comment]
@shush1980 Thanks for starting this. There is some additional infrastructure changes that need to be done to support RTL languages beyond just the translations. I have a branch somewhere that explores this. Would it be possible for you to provide a translation for the string "Switch to Arabic"? I could then add it to the language selection drop down so it would be testable.

**Comment by SusanRatiLane** [comment]
This is a lot more Arabic than we have in Weblate. It need to be converted to JSON and added into the current system.

**Comment by AppInventorWorkerBee** [comment]
Can one of the admins verify this patch?

**Comment by SusanRatiLane** [comment]
More work is now available on weblate.

**Pull request closed without merging**
