### PR TITLE
Dx Capacity Exceeds - Error handling 

### LINKED ISSUE #2344: More than Sufficient classes in MainDexList produces Dex Error
**Bug Description**
I doubted that more classes in the Main Dex List file (main-classes.txt)  produce errors as it must not exceed the 65k methods limit according to the official Android developer's documents(https://developer.android.com/studio/command-line/d8).

Testing with 8 Screens with some palette resources and setting dex verbose to true showed the following error.

MainDexListCapacityError

A tool to track the method count from classes.dex - https://github.com/mihaip/dex-method-counts

**Affects**

- [ ] Designer
- [ ] Blocks editor
- [ ] Companion
- [ ] Compiled apps
- [x] Buildserver
- [ ] Debugging
- [ ] Other... (please describe)

**Some alternatives we can choose to improve(Need Reviews to work on this issue)**
One of the following alternatives can fix the issue-

- **Excluding user-created class description in main dex list:** Including only first screen classes in Primary dex list as it loads initially and skipping all the other classes. By doing this, the speed of booting up screens can't degrade more than some nanoseconds which are negligible. Class description for other crucial jars in the input set(mainly responsible for creating main-classes.txt) will make the list non-incremental and will be risk-free. We can choose to perform this method only if we identify exceed main dex list capacity during dex task compilation

- **Generating Main dex list:** We can generate the main dex list with the help of dex list generator library and proguard. Proguard also provides options for shrinking and obfuscations. An example of dex list generator can be found in the android maven plugin build.

### PR DESCRIPTION
**Pull request by rupeshkumar22**
Fixes #2344
Checks if the dx produced "too many classes in main-classes.txt" error, If yes then recreates main-classes.txt by excluding the user-created classes. Executes the dx task again with the replaced main-classes.txt. The existing execute methods are used by other processes, so there was a need to create a separate stream handler method that can print to stdin and return the output buffer to check the type of error.
Excluding user source classes in main-classes.txt will add them in secondary dex files. Since the necessary Appcompat, Runtime, etc. classes are in primary dex and loaded initially by Dalvikvm, It's okay to include user-created screens in the secondary dex file if in case the error occurs. The projects with dx error and regular projects are tested and APK files worked fine on devices.
Project .aia that produces similar dex error and handled by the functionality:
[CheckDex2.zip](https://github.com/mit-cml/appinventor-sources/files/5762996/CheckDex2.zip)

### CODE REVIEW

**Comment by AppInventorWorkerBee** [comment]
Can one of the admins verify this patch?

**Comment by ewpatton** [comment]
It seems to me a simpler solution would be to only ever include Screen1 in the main dex and allow all other screens to be put in a secondary dex. If that fails, nothing else will work anyway as Screen1 must be present. That would eliminate the need to process and interpret the output of dx. On Android 5+ everything is converted at install time to oat from dex anyway so multidex performance will mostly just affect devices running earlier versions of Android.

**Comment by rupesh-kumar-lpu** [comment]
@ewpatton you are right, I think Screen1 must be included in primary dex file, I will also ensure the working on earlier versions of Android devices. Thanks for correcting, Please don't merge it for now.

**Comment by ewpatton** [comment]
@rupesh-kumar-lpu I've marked this as a draft for the time being until you are ready for it to be reviewed again.

**Comment by ewpatton** [comment]
We are no longer using dx as we have switched to d8 in the Java 11 update. This change is no longer needed.

**Pull request closed without merging**
