### PR TITLE
Fix buttons not taking a translucent background color

### PR DESCRIPTION
**Pull request by ewpatton**
Change-Id: I7781e710b4c3efd41c9585e2e5cd4c6cc2d50736

### CODE REVIEW

**Comment by ewpatton** [comment]
Note that I have not yet tested this on a version of Android lower than SDK 21 Lollipop.

**Comment by ewpatton** [comment]
Here is an example of what this looks like. Button2 has a blue background with 50% transparency which yields a purple tint, Button3 has a yellow background with 50% transparency which yields an orange tint, and Button4 has no background, which also needs the shadow suppressed (the state/outline manipulation is responsible for this).

Screenshot_20231012-211325

**Comment by ewpatton** [comment]
@jisqyv I've pushed two changes. The first fixes the crash on Android versions prior to 5.0. The second one removes a check that no longer seems to be need which forces the background color in Device Default and other themes to be white. The latter was something I bumped into when testing using the old emulator running Android 2.x using the button test project previously shared. We may want to keep the last commit separate since it's somewhat independent of the original reason for this change (but needed if testing the change on an old version of Android).

**Comment by ewpatton** [comment]
Screenshot 2023-10-30 at 3 48 19 PM

**Review by jisqyv — APPROVED** [review]
LGTM

**Pull request merged**
