### PR TITLE
Update AndroidX libraries

### LINKED ISSUE #2290: Outdated Android dependencies
In the recent release, support for the **`androidx`** libraries was added. It was an overall nice change, except for the `androidx` libraries being very old. There might be no effect of this on the main repo, but for extension devs who need to access the newer Android APIs, this is a major issue. I've no idea why these old libraries were used instead of the newer ones. Do the new versions of these libraries have some issues with App Inventor? Or is there some different reason? 

cc @jisqyv @ewpatton

### PR DESCRIPTION
**Pull request by ShreyashSaitwal**
Resolves #2290

### CODE REVIEW

**Comment by AppInventorWorkerBee** [comment]
Can one of the admins verify this patch?

**Comment by ewpatton** [comment]
@AppInventorWorkerBee ok to test

**Comment by ShreyashSaitwal** [comment]
Umm... The AAPT execution is failing. Does anyone have any idea why's this happening? 🤔

**Comment by StormiFire** [comment]
> Umm... The AAPT execution is failing. Does anyone have any idea why's this happening? 🤔

You can try process of elimination.

**Comment by ShreyashSaitwal** [comment]
> The AAPT execution is failing. Does anyone have any idea why's this happening? 🤔

Okay, so, it was happening because of some duplicate `android:{sth}` attributes in values.xml. I fixed this by downgrading some libraries.

**Comment by ShreyashSaitwal** [comment]
Okay, so, in previous commit, I fixed the issue that caused AAPT to fail. It was caused by some duplicate `android:sth` attributes in values.xml which were being added by some of the libs. I downgraded those and several other libs to their original versions. 

Although, this commit has fixed the AAPT error, it has caused some tests (`com.google.appinventor.components.runtime.*` to be precise) to fail. I'll take a look at it tonight.

**Pull request closed without merging**
