### PR TITLE
Load Blockly translations as needed using JSON files

### PR DESCRIPTION
**Pull request by SusanRatiLane**
This builds on Evan's change in (https://github.com/ewpatton/appinventor-sources/tree/feature/blockly-json-i18n) to load JSON files for Blockly translations as needed.

At compile time, the App Inventor Blockly translations are combined with translations from the Blockly library to create a master JSON file for each language. This is loaded as needed when the user selects a language.

Files in msg folder can now be updated using Weblate (http://weblate.appinventor.mit.edu).

### CODE REVIEW

**Comment by ewpatton** [comment]
@SusanRatiLane #1953 mentions a qqq.json file, which isn't present in this change. I just want to confirm that it will make it in here (or is no longer needed?).

**Comment by SusanRatiLane** [comment]
> @SusanRatiLane #1953 mentions a qqq.json file, which isn't present in this change. I just want to confirm that it will make it in here (or is no longer needed?).

I decided include those files because I'm not sure I can use them in the current weblate setup. If/when I figure that out, they can be a separate PR.

Open to suggestions.

**Comment by ewpatton** [comment]
@SusanRatiLane Ok. I just wanted to make sure we captured why the file went away. If it's not something that Weblate can do in your estimation it's probably okay for us to leave it out. On the other hand, it might make sense for us to capture the work you did so that we can incorporate it in a future update.

**Comment by SusanRatiLane** [comment]
@ewpatton I was unable to find or create any shared context to allow us to load messages.json only once. It looks like, once you dig through the layers of exec calls and argument arrays, that the test can only access the equivalent of command-line parameters. 

There's still one test failing. I'm looking into that.

**Comment by SusanRatiLane** [comment]
This forum thread contains things that need to be fixed: https://community.appinventor.mit.edu/t/for-testing-translation-overhaul/14950/3

Help links in the context menu seem to have a bug.

**Comment by SusanRatiLane** [comment]
Status: The HELP context menu option is disabled for all blocks because the helpUrl field is now set for the elements in Blockly.Blocks before Blockly.Msg is populated.

Fix in process.

**Comment by SusanRatiLane** [comment]
@ewpatton This is ready for another look.

**Comment by SusanRatiLane** [comment]
@AppInventorWorkerBee  OK to test

**Comment by SusanRatiLane** [comment]
@ewpatton Checks have now passed.

**Review by ellelili2025 — APPROVED** [review]

**Pull request merged**
