### PR TITLE
Canvas upgrade11

### PR DESCRIPTION
**Pull request by halatmit**

### CODE REVIEW

**Comment by halatmit** [comment]
I did some quick testing, but it could use more.

**Comment by halatmit** [comment]
@jisqyv 
I did some quick testing, but it could use more.

**Comment by jisqyv** [comment]
@halatmit I would suggest not incrementing the component version number again. There are no projects that have seen version 10.

-Jeff

**Comment by jisqyv** [comment]
I've backed out the version increment on my copy and am testing it now.

**Comment by halatmit** [comment]
@jisqyv 
I removed the extra versiosn upgrade.  WARNING: I did not test this.

**Comment by jisqyv** [comment]
LGTM, MERGED

**Pull request closed without merging**
