### PR TITLE
Add Reverse Text Block

### PR DESCRIPTION
**Pull request by conorshipp**
This PR adds a new `Reverse` block to the text section of the built-in blocks.

Demonstration of the block using the `Do It` function:
image

### CODE REVIEW

**Comment by AppInventorWorkerBee** [comment]
Can one of the admins verify this patch?

**Comment by ewpatton** [comment]
@AppInventorWorkerBee ok to test

**Comment by ewpatton** [comment]
@conorshipp Thanks. One last request before we can merge: I would recommend adding a test case to buildserver's YailEvalTest.

**Comment by ewpatton** [comment]
@conorshipp Do you want to resolve the conflicts here and provide the test so that we can get this merged?

**Comment by conorshipp** [comment]
@ewpatton sure. I've been having issues with the unit tests on my PC (as you saw on the community) and haven't had the chance to look into it yet. Still need to test the combining characters you mentioned too.

**Comment by ewpatton** [comment]
@conorshipp I must have missed it. Can you point me in the right direction?

**Comment by conorshipp** [comment]
@ewpatton [here's the community topic](https://community.appinventor.mit.edu/t/problems-running-unit-tests-on-windows-10/2905/). You did reply :smiley:

**Comment by ewpatton** [comment]
@conorshipp #2044 has been merged and we have merged master into ucr. You should be able to rebase this change to bring it current.

**Comment by conorshipp** [comment]
@ewpatton please look at the unit test and let me know if that's what you're looking for. I'm not very familiar with unit tests so I'm not exactly sure how to write them but it was successful so I think it's right 🤷‍♂

**Comment by ewpatton** [comment]
@conorshipp Yeah that's good enough for now. We'll probably need to add more if issues crop up (especially around multiple code point characters).

**Comment by conorshipp** [comment]
@ewpatton can you think of any way to make this work with Emojis? If not, would it make sense to update the documentation to state that Emojis won't work properly?

**Comment by ewpatton** [comment]
@conorshipp I'll need to do some experimentation to find out.

**Comment by ewpatton** [comment]
@conorshipp The commit I just pushed implements a unicode-aware string->list function*. Because the emojis are in the part of Unicode plane that needs code surrogates to encode them, reversing puts all the pairs in the wrong order. This new string->list function swaps the surrogates so that when they are reversed the chars will be in the correct order.

**Comment by SusanRatiLane** [comment]
@ewpatton @conorshipp Put an additional set of eyes/tests on the unicode-aware change, and it looks good to me.

**Pull request merged**
