### PR TITLE
Updated AI2 Project Merger Tool

### PR DESCRIPTION
**Pull request by aesmaili**
Changes made:

-Rename second Screen1
-Remember last browser location
-Check all buttons
-Automatic upload of projects
-Layout change
-Show asset extensions
-Typo fixes

@jsheldonmit @halatmit

### CODE REVIEW

**Comment by jsheldonmit** [comment]
I have tested this and these changes are working for the test case from Ben Shapiro's student & with files I've made - it seems to be working so far. The design looks good.

**Comment by afmckinney** [comment]
I can do the review.

**Comment by halatmit** [comment]
@afmckinney Please review this.

**Comment by afmckinney** [comment]
LGTM

**Comment by halatmit** [comment]
Thanks.  Send a note to areszu when this gets released.  There's also a
thread in the forum where you could add a note, so people realize that we
listen to them. :)



== Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.
MIT Media Lab, Second Class Faculty

**Pull request closed without merging**
