### PR TITLE
Implement custom zoom controls

### LINKED ISSUE #1250: Map zoom controls do not work in Fixed sizing mode
[From the forum](https://groups.google.com/d/msg/mitappinventortest/gfoFJBJhYVE/RMk4dnvPAQAJ): The zoom controls for the Map component do not work when in Fixed sizing mode and on a screen where the display isn't medium density. The controls are drawn in the wrong position and do not appear to respond to touch events. My hypothesis is that the touch zones and the drawn controls are not aligned, making it look as though the controls are not responding to events. Switching to Responsive mode resolved the issue and the controls are in the "right" position, bottom center of the map.

### PR DESCRIPTION
**Pull request by ewpatton**
The Android SDK provided zoom controls used by osmdroid are not scaled
by ScaledFrameLayout, and so do not work correctly when Sizing is
Fixed. Further, the ZoomButtonsController is deprecated starting with
SDK 26 and Google recommends that developers provide custom views for
zoom controls.

This change implements zoom controls for the Map component similar to
those shown in the designer.

Fixes #1250 

Change-Id: Ifd85de7fc60a042eb1cddc23c6b037964395da7d

### CODE REVIEW

**Comment by jisqyv** [comment]
@p4ssw0rd Yep, that moves the Compass to the location where it is shown in the designer...

**Comment by jisqyv** [comment]
@ewpatton When I run "ant tests" the tests seem to loop in MapTest. No output is generated and CPU is spinning. Never finishes.

**Comment by ewpatton** [comment]
There were two separate issues here. First, the tests were coded to the more specific ShadowMapView and, by changing the view hierarchy to group the map and view controls under another layout, the shadow view no longer matched. I updated the tests to use the more general ShadowView class. The change in the view hierarchy also resulted in map layout not being computed correctly by the test setup. This resulted in a 0 width/height map. Setting the bounding box with a zero-size map results in an infinite loop in the osmdroid library when it tries to compute appropriate bounds (goes toward +Infinity). Tests should be passing now.

**Comment by jisqyv** [comment]
@ewpatton LGTM

**Pull request merged**
