### PR TITLE
ScrollArrangement handlers & Nine-Patch support

### PR DESCRIPTION
**Pull request by ColinTree**
> I m still not sure about some formula or standard of app inventor community's code.
> plz check my code and tell me if i need to do anything else

* **ScrollArrangement handlers** are almost same as my extension [ScrollArrangementHandler](http://aix.colintree.cn/en/extensions/ScrollArrangementHandler.html)  
  and i just attend my code into source file of two Scroll Arrangements.  
  New features:
  * scroll events (scrolling, scrolling and touch ends)
  * control scrolling

* **Nine-Patch** is using [Anatolii/NinePatchChunk](https://github.com/Anatolii/NinePatchChunk) (Apache License 2.0). The features are also similar to my [ColinTreeNinePatch](http://aix.colintree.cn/en/extensions/ColinTreeNinePatch.html)
  I put the new codes into MediaUtil and redirected the components. So they are now calling the new method [getDrawable](https://github.com/mit-cml/appinventor-sources/commit/c8b46357c99559e7e8740055b567d0a954aa2529#diff-6e361981d7529f5d09aa657865faf8a9R524) instead of calling [getBitmapDrawable](https://github.com/mit-cml/appinventor-sources/commit/c8b46357c99559e7e8740055b567d0a954aa2529#diff-6e361981d7529f5d09aa657865faf8a9R355). The drawable will be convert into NinePatchDrawable if it can be converted.
Above all, for users, there is nothing changed, unless they are setting a raw/compiled Nine-Patch image.

Attached:
[Nine-patch testing source.zip](https://github.com/mit-cml/appinventor-sources/files/1327065/Nine-patch.testing.source.zip)
[apk & aia.zip](https://github.com/mit-cml/appinventor-sources/files/1327068/apk.aia.zip)

Thanks

### CODE REVIEW

**Comment by moliata** [comment]
Please note that you can easily convert BitmapDrawable to Drawable: (Drawable) your bitmap drawable, you are changing a whole system, which is very bad. A lot of extensions will be broken, plus it won't be possible to get Bitmap out of BitmapDrawable.

**Comment by moliata** [comment]
Also, when you are updating current components, you have to increase level in YaVersion & have to upgrade Form by YoungAndroidFormUpgrader.java

**Comment by ColinTree** [comment]
hello @moliata.
is the [commit 29aa5af](https://github.com/mit-cml/appinventor-sources/pull/937/commits/29aa5afb58331eb00fd9d72bfc92f6b47576d123) fixed the version problem?

**Comment by conorshipp** [comment]
@ColinTree You also need to change versioning.js when you change the version.

**Comment by ColinTree** [comment]
(i will close this pull request, and reopen a well-formed one later.)

**Comment by ColinTree** [comment]
so i think i should put away the nine-patch first, that involves the construction of the system.

cause i can't find a perfect solution here:
- *adding a new property or method**, mess up the variables in components.
- **re-construct the getBitmapDrawable**, NinePatchDrawable will mess up when in BitmapDrawable
- **add something between view.setBackgroundImage() and getBitmapDrawable()**, that is what i m using now, but it still make a mess of variables and interfaces as moliata said.
- nope

emmm, sad

**Pull request closed without merging**
