### PR TITLE
Fix Regex Invoke

### PR DESCRIPTION
**Pull request by XomaDev**
I apologize, I messed up the previous pull request and it got closed for some reason, I have set the target branch to ucr.

### CODE REVIEW

**Comment by AppInventorWorkerBee** [comment]
Can one of the admins verify this patch?

**Comment by jisqyv** [comment]
@AppInventorWorkerBee ok to test

**Comment by ewpatton** [comment]
@XomaDev This PR is not as clean as the previous PR. There are a lot more modifications to runtime.scm and you've committed the IntelliJ project files, which should not be included.

**Comment by XomaDev** [comment]
I have corrected the problems

**Review by jisqyv — APPROVED** [review]
LGTM

**Pull request merged**
