### PR TITLE
Added documentation for special regex characters in 'replace all' block

### PR DESCRIPTION
**Pull request by JustinFrost47**
fixes: #2360
I have added the required explanations about how to use special regex characters in 'replace all' block
A short intro about  regex, special characters followed by an example was also added 

I hope that the changes  fulfill the requirements

This is one of my first time contributing to opensource organizations
So, if you would like to add any corrections or best practices for me to follow, I am happy to listen

### CODE REVIEW

**Comment by AppInventorWorkerBee** [comment]
Can one of the admins verify this patch?

**Comment by ewpatton** [comment]
@AppInventorWorkerBee ok to test

**Review by ewpatton — COMMENTED** [review]
Note that the HTML documentation is automatically built during a compilation step, or if you run `ant docs`. I have rebuilt it so that it matches the Markdown files. If you agree with the update let me know and we can go ahead and merge this.

**Comment by JustinFrost47** [comment]
@ewpatton  
ok, understood :+1:  

thanks for the correction
please go  ahead with merging

**Review by ewpatton — APPROVED** [review]

**Pull request merged**
