### PR TITLE
Image sprite rotation bug fixing + Improving the drawing code.

### PR DESCRIPTION
**Pull request by Momoumar**
Improve the drawing code for image sprites using the second method of issue #407, which leads to fix the black background bug.

### CODE REVIEW

**Comment by halatmit** [comment]
LGTM
Very nice work!

**Comment by Momoumar** [comment]
Thanks @halatmit.

**Comment by halatmit** [comment]
Thank *you*



== Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.
MIT Media Lab, Second Class Faculty

**Comment by jisqyv** [comment]
@Momoumar MERGED into the "ucr" branch for the next component release.

**Pull request closed without merging**
