### PR TITLE
Added generic event handlers

### PR DESCRIPTION
**Pull request by jisqyv**
Change-Id: Iadaefaa460a5183c282e120d1769204108b0396d

### CODE REVIEW

**Comment by jisqyv** [comment]
This pr takes over #347

**Comment by halatmit** [comment]
@gitars @jisqyv 
Yanesh:
Jeff had to do some massaging to deal with the merge conflicts.   Could you download this pull request into a clean updated master branch and check that is seems OK, before we review?
Thanks.

**Comment by gitars** [comment]
@halatmit @jisqyv 
I just tried some tests out (a few for generic and multi-generic, and also on the companion app with the Do It functionality) and it seems good to me. The only thing I noticed there was a slight issue in the duplicate event warning code, so I created a pull request against the branch (jisqyv:patelmultigeneric).

**Comment by mark-friedman** [comment]
I'm glad to see that this is proceeding!  I was worried that it was stalled.

**Comment by jisqyv** [comment]
@halatmit @gitars Note: Because runtime.scm was modified, YaVersion.BLOCKS_LANGUAGE_VERSION and YaVersion.YOUNG_ANDROID_VERSION need to be bumped.

**Pull request closed without merging**
