### PR TITLE
TextToSpeech: Need a "Default" choice #447

### PR DESCRIPTION
**Pull request by E-Hon**
see #447 

Tested on emulator of API level 19
- When the default values of Country and Language are set to an empty string, once their getters are called, the device's default values are retrieved.

### CODE REVIEW

**Comment by halatmit** [comment]
LGTM

but it might need to be merged with latest master changes and blocks version numbers.

**Comment by jisqyv** [comment]
I'll take care of the version numbers when I put it on the UCR branch

**Comment by halatmit** [comment]
That's what I figured.


== Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.
MIT Media Lab, Second Class Faculty

**Comment by halatmit** [comment]
@jisqyv 

Close #447 when this is merged.

**Comment by jisqyv** [comment]
@E-Hon @halatmit MERGED into the ucr branch for the next component release.

**Pull request closed without merging**
