### PR TITLE
Replaced resizableActivity to resizeableActivity

### PR DESCRIPTION
**Pull request by jewelshkjony**
Fixed a typo in the Android manifest where 'resizableActivity' was incorrectly written as 'resizeableActivity'.

### CODE REVIEW

**Comment by AppInventorWorkerBee** [comment]
Can one of the admins verify this patch?

**Comment by jewelshkjony** [comment]
@AppInventorWorkerBee, it's ready to review.

**Comment by ewpatton** [comment]
@AppInventorWorkerBee ok to test

**Review by ewpatton — APPROVED** [review]
I'm going to approve this, but in the future I recommend keeping independent changes as two different PRs.

**Pull request merged**
