### PR TITLE
Lyn's Deprecation Code with my modifications for Camera

### PR DESCRIPTION
**Pull request by jisqyv**
This PR contains two commits. The first is Lyn's original work with the changes to Camera.java removed. The second commit is the changes to Camera.java including updates to YoungAndroidFormUpgrader and YaVersion. Note: Although this PR is submitted against the master branch, it will either get merged into the "ucr" branch (because of the YaVersion change) OR merged into master after we merge in ucr (hopefully this coming week).

There is a test server up at http://jisqyvap4.appspot.com. This server has a template named "CameraHack" which you can import. It was written BEFORE the UseFront property was deprecated, so by loading it you will experience the deprecation process, including a warning message displayed to the user.

As an aside, this test server also has the Brazilian Portuguese translation loaded on it (and being verified by the translation owner). Once the translation owner approves the code on the test server I'll submit a separate pull request for that code. Note: That code is *not* included here.

Also note: This PR supercedes #650 which I will close.

### CODE REVIEW

**Comment by jisqyv** [comment]
@halatmit @fturbak Please review... Note test server at http://jisqyvap4.appspot.com

**Comment by afmckinney** [comment]
This has been tested and reviewed LGTM

**Comment by jisqyv** [comment]
Rebased

**Comment by jisqyv** [comment]
Pushed to Gerrit for UCR

**Comment by jisqyv** [comment]
MERGED

**Pull request closed without merging**
