### PR TITLE
added scrolling handlers of ScrollArrangement & Chinese Translation of it

### PR DESCRIPTION
**Pull request by ColinTree**
(reopen of #937 )

> I m still not sure about some formula or standard of app inventor community's code.
> plz check my code and tell me if i need to do anything else

* **ScrollArrangement handlers** are almost same as my extension [ScrollArrangementHandler](http://aix.colintree.cn/en/extensions/ScrollArrangementHandler.html)  
  and i just attend my code into source file of two Scroll Arrangements.  
  New features:
  * scroll events (scrolling, scrolling and touch ends)
  * control scrolling

Thanks

### CODE REVIEW

**Comment by moliata** [comment]
This is pretty amazing, great work.

**Comment by ColinTree** [comment]
sorry that where is that folder~?

**Comment by moliata** [comment]
Check appinventor/docs/reference/components/layout.html, you need add documentation, so people will only what each property, method & event does.

**Comment by ColinTree** [comment]
DOCS UPDATED

**Comment by moliata** [comment]
Amazing, @ewpatton @afmckinney @josmas @jisqyv may take a look at this.

**Comment by ColinTree** [comment]
Now it is clear to see the changes in [files changed](https://github.com/mit-cml/appinventor-sources/pull/938/files)

**Comment by ewpatton** [comment]
@ColinTree At preliminary glance this looks pretty good. However, before we review it you should rebase these changes on top of the `ucr` branch rather than `master` as it makes changes to the behavior of components. Assuming you have our sources configured as the `upstream` remote, you can do this by:

```shell
git branch scroll-improvements ucr  # create a new branch off of ucr
git checkout scroll-improvements  # switch to new branch
git cherry-pick 76323dd..4e0ba0a  # bring your changes over to the new branch
# Optionally at this point you could use git rebase -i to interactively rebase and squash your commits into a single change. See https://docs.google.com/document/d/1jtovCKcAlgxefZsjdOsN3UCXUwhrrGnSrUTeDJ6GMuE/edit for more details
git push --set-upstream origin scroll-improvements  # push the changes
```

You will then need to update this PR to use ucr and your new branch instead of master as the base branch. If it won't let you change the source branch, you may need to resubmit the PR.

**Comment by ColinTree** [comment]
OK, i will do that right now. thanks for noticing

**Pull request closed without merging**
