### PR TITLE
Gallery

### PR DESCRIPTION
**Pull request by kelseyc18**
Updates gallery publishing buttons and links to interact with [standalone gallery](https://github.com/kelseyc18/ai-gallery)

### CODE REVIEW

**Comment by ewpatton** [comment]
Note that I've sent around a calendar invite for us to discuss this Feb 7th as well as review the gallery code.

**Comment by jisqyv** [comment]
On hold pending our Feb. 7th meeting

**Comment by AppInventorWorkerBee** [comment]
Can one of the admins verify this patch?

**Comment by kelseyc18** [comment]
I'm working on this branch for my MEng thesis. We are not planning on merging it in this state. It will probably be a while before the branch is ready.

**Comment by ewpatton** [comment]
The gallery code was merged in a separate change.

**Pull request closed without merging**
