### PR TITLE
Fixed black bars in some layouts in fixed mode. Ref issue #511

### PR DESCRIPTION
**Pull request by Momoumar**
@halatmit,
Companion attached for testing : 
https://drive.google.com/open?id=0Bw0fmqX0oC9YUWkwWWl2bnpjZUE

### CODE REVIEW

**Comment by jisqyv** [comment]
LGTM

**Comment by jisqyv** [comment]
@Momoumar Turns out this change disables "Fixed" mode completely...

-Jeff

**Comment by Momoumar** [comment]
@jisqyv,
Thanks. I'll throw a second glance. 
Do you have a hint by passing ...

**Comment by halatmit** [comment]
This is fixed in PR #537.  Closing.

**Pull request closed without merging**
