### PR TITLE
Fix nullptr in text connection check

### LINKED ISSUE #2205: Make a list with text (string) blocks failed to save string values
**Describe the bug**

The value(s) of "Text (string)" block in "Make a list" are not saved.

**Affects**

- [ ] Designer
- [*] Blocks editor
- [ ] Companion
- [ ] Compiled apps
- [ ] Buildserver
- [ ] Debugging
- [ ] Other... (please describe)

**Expected behavior**

Strings typed in should be saved and restored after project is reopen.

**Steps to reproduce**

1. Drop a "Make a list" block onto designer
2. Drop several "Text (string)" blocks onto designer and connect to "Make a list"
3. Typed in string (any letters, numbers, etc.) in each "Text (string)" block
4. Clicked "My Projects" -> "Save project"
5. Signed out
6. Signed in and open the same project
7. Looked at designer
8. Noticed that "Make a list" -> "Text (string)" blocks are empty

Screen Shot 2020-06-08 at 13 58 06

### PR DESCRIPTION
**Pull request by BeksOmega**
### Resolves

Closes #2205 

### Description

Untyped connections have a `.check_` value of null. This meant that if you connected a text block to an untyped connection it would throw a null error when it tried to access the `.length` of the `.check_`.

This adds an explicit check for untyped connections so that this error does not occur.

### Testing

Rebuilt and replicated the steps from #2205. Could not replicate the error.

### Additional Info

Thank you for reporting this @xuwenbin ! I think this should fix it :D

### CODE REVIEW

**Comment by ewpatton** [comment]
@BeksOmega This LGTM, but it might be better if you also added a unit test for the check function.

**Comment by BeksOmega** [comment]
Thanks @ewpatton I had forgotten you addd tests for this!

**Comment by ewpatton** [comment]
@AppInventorWorkerBee retest this please

**Comment by ewpatton** [comment]
@BeksOmega That's not on you. That test is a bit unstable since it runs many threads in parallel and sometimes there is a collision.

**Pull request merged**
