### PR TITLE
[GSOC] Implementing Trash Can Functionality in MIT App Inventor.

### PR DESCRIPTION
**Pull request by HimaniKaul**
Pull Request for GSoC '19. 

Project titled "Implementing Trash Can Functionality in MIT App Inventor".

This functionality keeps the deleted project in a folder called Trash and if the project is accidentally deleted will not directly go away from App Inventor but will exist in Trash.

In Trash Window users will have functionality to permanently delete the project or restore back to My Projects or simply keep in Trash.

### CODE REVIEW

**Comment by AppInventorWorkerBee** [comment]
Can one of the admins verify this patch?

**Comment by jisqyv** [comment]
@AppInventorWorkerBee ok to test

**Comment by SusanRatiLane** [comment]
From a user interface perspective, I find it confusing that "Delete" is still used to send projects to trash. I think now that we have a trash feature, sending a project to trash should always say that to avoid confusion.

Most trash can features also have an "Empty Trash" button to delete all trashed items with one action. I think that would be a good thing to add.

**Comment by ewpatton** [comment]
@HimaniKaul @SusanRatiLane makes some good points about the naming of these actions. Please consider updating the PR based on her feedback.

**Comment by jisqyv** [comment]
@ewpatton @SusanRatiLane We can rename the buttons, menu options. Adding an "Empty Trash" feature probably goes beyond the scope of work here (we can add it later).

**Comment by HimaniKaul** [comment]
@jisqyv  @ewpatton  @SusanRatiLane I will update the code which would inform the user "Project Moved to Trash" after they delete it from My Projects tab to avoid confusion.                                               Also just like emails, we use delete button to move unwanted emails to trash. I have applied that same concept here in deleting unwanted projects to trash. Here naming might be creating confusions I will work on it.

**Comment by HimaniKaul** [comment]
@jisqyv @SusanRatiLane @ewpatton  What are your opinions if change name from "Delete Project" to "Move to Trash" and "Trash List " to "View Trash" ?

**Comment by SusanRatiLane** [comment]
> @jisqyv @SusanRatiLane @ewpatton What are your opinions if change name from "Delete Project" to "Move to Trash" and "Trash List " to "View Trash" ?

That sounds great to me. Exactly what I had in mind. Thanks!

**Comment by HimaniKaul** [comment]
@SusanRatiLane  @ewpatton  @jisqyv That's amazing.

**Pull request merged**
