### PR TITLE
implement anamoly detection for iOS

### PR DESCRIPTION
**Pull request by kidussyohanness**

### CODE REVIEW

**Comment by AppInventorWorkerBee** [comment]
Can one of the admins verify this patch?

**Comment by ewpatton** [comment]
@AppInventorWorkerBee ok to test

**Comment by ewpatton** [comment]
@kidussyohanness This doesn't appear to compile. Make sure to test locally and then push your fixes to the existing branch.

**Comment by ewpatton** [comment]
Note this is blocked by #3272

**Pull request merged**
