### PR TITLE
Re-Enable the “Update Companion” Menu Item

### PR DESCRIPTION
**Pull request by jisqyv**
Re-Enable the “Update Companion” Menu Item, but limit its use to the
Emulator.

Change-Id: I86e530b65fd7845de42cdccecb5550af6215db3c

### CODE REVIEW

**Comment by jisqyv** [comment]
Fixes #1692

**Comment by jisqyv** [comment]
@ewpatton Note: I was tempted to rename the code from companionUpdate to emulatorUpdate, but in the end decided to leave it alone, because we would have to get translations from the updated language.

**Comment by jisqyv** [comment]
@ewpatton Actually, it is a feature that we can use it for updating a phone via USB. Of course it will put the Emulator code on the phone, but if the phone is regularly used via USB, it doesn't need the native libraries anyway. The update will *not* work if the phone has the Companion from the Play Store because it doesn't implement the "_package" url. I suspect things will fail ungracefully in that case. I can catch that case and give a more reasonable error.

**Comment by ewpatton** [comment]
@jisqyv I'd be a little bit concerned about installing the emulator package onto a device that might also be used for the QR code. We know this won't be the case in the emulator, but if that person now goes and tries to scan a QR code later without checking the legacy box nothing will happen. It would be better if we could detect the USB and send the full package instead (WebRTC and extra permission)

**Comment by jisqyv** [comment]
@ewpatton Your probably right. I wonder how we can tell the difference...

**Comment by ewpatton** [comment]
I think the easiest thing would be to have a flag isUsb that we set if the USB option is clicked. When the connection is reset we just set it back to false. Then we can check in the upgrade if isUsb is true and transfer the MITAI2Companion.asc file rather than Emulator.asc.

**Comment by ewpatton** [comment]
There is an edge as well with the use of Genymotion since it goes over USB. However, in this case the installation will fail due to the missing WebRTC library for x86.

**Pull request merged**
