### PR TITLE
Update Headers of Documentations Page to match Website

### PR DESCRIPTION
**Pull request by jisqyv**
Change-Id: I58af98f8255858dc19c59a7bed86b87936d905d5

### CODE REVIEW

**Comment by jisqyv** [comment]
@halatmit @afmckinney I'll put this up on my test server so you can see the results...

**Comment by jisqyv** [comment]
@halatmit @afmckinney You can now see the pages "live" on http://jisqyvap4.appspot.com

**Comment by halatmit** [comment]
How do I see what the final pages look like?    If I go to the conponents
documentation on this site, I end up at ai2.appinventor.mit.edu.


== Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.
MIT Media Lab, Second Class Faculty

**Comment by jisqyv** [comment]
This PR addresses #277

**Comment by jisqyv** [comment]
@halatmit Try going to:

  http://jisqyvap4.appspot.com/reference/other/

You can also go to:

  http://jisqyvap4.appspot.com/reference/components/

To see an index of the component pages (the index itself is in an ancient AI1 format, but no one ever really sees it).

**Comment by afmckinney** [comment]
LGTM

**Pull request merged**
