### PR TITLE
Address crash of Recyclerview on SDK < 14

### PR DESCRIPTION
**Pull request by ewpatton**

### CODE REVIEW

**Comment by jisqyv** [comment]
@ewpatton After latest update https://github.com/mit-cml/appinventor-sources/pull/2511/commits/0e73e465125499887710b2734a75c9a9371ee0b2 The Emulator (API 7) no longer crashes and the ListView sort of works.

However, in other testing I now see that horizontal orientation now does nothing (both in Emulator and on my devices running 9.0) and setting the selection color also appears to be a no-op on both platforms.

**Comment by ewpatton** [comment]
@SusanRatiLane Can you include Jeff's comments in addition to looking into the height issue reported yesterday?

**Comment by SusanRatiLane** [comment]
> @SusanRatiLane Can you include Jeff's comments in addition to looking into the height issue reported yesterday?

I have lost track of the height issue. Is there a link to that?

**Review by jisqyv — APPROVED** [review]
LGTM

**Pull request merged**
