### PR TITLE
Json string

### PR DESCRIPTION
**Pull request by halatmit**
Changes the way lists are printed, so they appear in Json notation.   Implements the ShowListsAsLisp property.
Still need to change runtime.scm to make use-json-format a macro.    Also need to implement the upgrader.

### CODE REVIEW

**Comment by halatmit** [comment]
I updated the PR to comment out the upgrade code and the designer property.  This should now be ready for review.

**Comment by jisqyv** [comment]
@halatmit It doesn't work properly. Basically the ShowOldStyle is hidden, but it's default value is "false" so lists now only appear as JSON. We need a solution where ShowOldStyle is hidden *and* lists appear in the Companion in lisp syntax. We can discuss when we meet in person... this is tricky

**Comment by halatmit** [comment]
Thanks for catching that.   We can discuss when we meet.


== Hal

Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.

**Comment by jisqyv** [comment]
@halatmit @afmckinney A version of this change has been pushed onto the ucr branch.

**Pull request closed without merging**
