### PR TITLE
Update to latest Physicaloid with Android S support

### PR DESCRIPTION
**Pull request by ewpatton**
Change-Id: If9915b58ff3bbfe03149b4bc212527d883072710

### CODE REVIEW

**Comment by ewpatton** [comment]
The previous version of the physicaloid library used by the Serial component does not follow Android S requirements. This version updates the PendingIntent references with the FLAG_IMMUTABLE required for newer Android versions.

**Comment by shreyashsaitwal** [comment]
Is the JAR being used here built from a fork of the original physicaloid library? If yes, can you please link it here? Asking because the latest commit on the physicaloid's GitHub repo is from April 2014.

**Comment by ewpatton** [comment]
From here: https://github.com/xxxajk/PhysicaloidLibrary

**Review by SusanRatiLane — APPROVED** [review]
This was tested in the community.

**Pull request merged**
