### PR TITLE
Partial Translation of OdeMessages_fil.properties

### PR DESCRIPTION
**Pull request by vinzruzell**
Hello,

For this commit, this is my partial translation of OdeMessages_fil.properties into filipino language.

### CODE REVIEW

**Comment by ewpatton** [comment]
Thanks @vinzruzell. Note that you do not need to translate the lines beginning with `#` as these indicate comments.

I have published this PR on the test server at http://fil.ai2-ewpatton-temp.appspot.com/

**Comment by vinzruzell** [comment]
Thank you @ewpatton.

**Comment by vinzruzell** [comment]
Okay sir..I understand...I will complete the translation. I will make sure
a good translation for you. Thanks.

**Comment by ewpatton** [comment]
Marking this as "on hold" until it is done and ready for review.

**Comment by SusanRatiLane** [comment]
Imported the translated strings into weblate with attribution

**Pull request closed without merging**
