### PR TITLE
Fix screen orientation artifacts in compiled apps

### PR DESCRIPTION
**Pull request by ewpatton**
Change-Id: I119b740b6ea592d5fe8295800cbb6861f51571bd

### CODE REVIEW

**Comment by ewpatton** [comment]
Some users complained of issues where they would specify Landscape as the orientation, but the app launches in Portrait and then reorients to Landscape once activate. This change extracts the value of the ScreenOrientation property and uses it to populate the `<activity>` element's `android:screenOrientation` property so that the activity launches in the right orientation immediately rather than starting in an alternative position.

**Comment by vknow360** [comment]
Companion also shows this abnormal behaviour. Sometimes at startup whereas sometimes after scanning QR code.

**Comment by ewpatton** [comment]
@vknow360 Sure, and this is because the BarcodeScanner activity specifies that it should run in landscape mode, but it's not clear to me this is a hard requirement. I'm also less concerned about oddities like this in the companion since it's intended to be a simulation and not everything will be accurate 100% of the time.

**Review by jisqyv — APPROVED** [review]
LGTM

**Pull request merged**
