### PR TITLE
Fixed misleading "onepotato" example

### LINKED ISSUE #322: "One Potato" example not quite right for text split
The following text could be confusing in a subtle way. The example for the split text block says splitting the string 
"one-potato,two-potato,three-potato,four" at "-potato" 
renders the list "(one two three four)".

This is wrong, as the split token needs to include the comma. 

The problem is in the english, and appears to have propagated to spanish and italian translations. I'm not really competent in the non-romance languages, but zh_cn and zh_tw appear to have the comma correctly inserted.

If someone can check the following, just to make sure, that would be great:

zh_cn:
```javascript
Blockly.Msg.LANG_TEXT_SPLIT_TOOLTIP_SPLIT = '以指定文本作为分隔符，将字符串分解为不同片段，并生成一个列表作为返回结果。\n'
    + ' 如以","(逗号)分解"一,二,三,四"，将返回列表"(一 二 三 四)"，\n'
    + ' 而以"-土豆"作为分隔符分解字符串"一-土豆,二-土豆,三-土豆,四"，则返回列表"(一 二 三 四)"。'
```

zh_tw:
```javascript
Blockly.Msg.LANG_TEXT_SPLIT_TOOLTIP_SPLIT = '以指定文字作為分隔符號，將字元串分解為不同片段，並產生一個清單作為傳回結果。\n'
    + ' 如以","(逗號)分解"一,二,三,四"，將傳回清單"(一 二 三 四)"，\n'
    + ' 而以"-土豆"作為分隔符號分解字元串"一-土豆,二-土豆,三-土豆,四"，則傳回清單"(一 二 三 四)"。'
```

Also...
---------
I also found issues with the "split at first of any" tooltip. I've corrected the English, Spanish, and Italian and the pull request, but need someone to check the Chinese (just as above).

This problem was the list (ba ap) was represented with a comma, which was incorrect. I also found the examples in spanish and italian were broken (didn't split the string correctly). Here's the corrected English:
```javascript
Blockly.Msg.LANG_TEXT_SPLIT_TOOLTIP_SPLIT_AT_FIRST_OF_ANY = 'Divides the given text into a two-item list, using the first location of any item \n'
        + 'in the list \'at\' as the dividing point. \n\n'
        + 'Splitting "I love apples bananas apples grapes" by the list "(ba ap)" returns \n'
        + 'a list of two items, the first being "I love" and the second being \n'
        + '"ples bananas apples grapes."';
```
zh_cn:
```javascript
Blockly.Msg.LANG_TEXT_SPLIT_TOOLTIP_SPLIT_AT_FIRST_OF_ANY = '以列表中的任意项作为分隔符，\n'
    + '在首次出现分隔符的位置将给定文本分解为一个两项列表。\n\n'
    + '如以"(稥,苹)"作为分隔符分解"我喜欢苹果香蕉苹果葡萄"，\n'
    + '将返回一个两项列表，其第一项为"我喜欢"，第二项为\n'
    + '"果香蕉苹果葡萄"';
```
zh_tw:
```javascript
Blockly.Msg.LANG_TEXT_SPLIT_TOOLTIP_SPLIT_AT_FIRST_OF_ANY = '以清單中的任意項作為分隔符號，\n'
    + '在首次出現分隔符號的位置將給定文字分解為一個兩項清單。\n\n'
    + '如以"(稥,蘋)"作為分隔符號分解"我喜歡蘋果香蕉蘋果葡萄"，\n'
    + '將傳回一個兩項清單，其第一項為"我喜歡"，第二項為\n'
    + '"果香蕉蘋果葡萄"';
```

Thank you!

### PR DESCRIPTION
**Pull request by marksherman**
Tooltip for text split fixed.

and other fixes to tooltips for relating to that block in english, spanish, and italian. (see commit log)

fixes #322 (pending chinese languages being checked)

Change-Id: I2df5c783d8b8a00e00928e69b587f14ff326ee57

### CODE REVIEW

**Comment by halatmit** [comment]
Thanks.
@weihuali0509 
Wei, can you provide a corrected Chinese version?

**Comment by marksherman** [comment]
Chinese translation corrections have been provided by @eagles2f and added to this pull request. It now looks good to me.

**Comment by marksherman** [comment]
@halatmit, a reply has been received, I believe the tag can be updated.

**Comment by halatmit** [comment]
@marksherman 
check whether this has been totally fixed now.  I believe the Chinese text has been added to the pootle server.  Can we close the issue, or does the tooltip need to be fixed in the source?

**Comment by marksherman** [comment]
I'm not sure what the protocol is for localized text updates. The changes that this pull request reflects are correct by all assertions available to me. If the changes being in pootle is sufficient, then we're done here.

If putting them in pootle is enough, then can someone please ensure that the english, spanish, and italian translations make it in, too?

**Comment by halatmit** [comment]
Tiffany,

Can you help Mark?

**Comment by tiffanyle** [comment]
The Pootle server has been updated to match the changes from the pull request.

**Comment by halatmit** [comment]
The pootle server was updated.

**Pull request closed without merging**
