### PR TITLE
Added mutator to AND and OR in logic block

### PR DESCRIPTION
**Pull request by candicefan**
#797

Added mutator to AND and OR in logic blocks. But, I made AND and OR into separate blocks, without having the dropdown.

@halatmit @afmckinney @jisqyv

### CODE REVIEW

**Comment by jisqyv** [comment]
@candicefan You should remove the commented out code. You also need to provide an "upgrader" to upgrade existing projects to use your new block.

**Comment by halatmit** [comment]
@candicefan @jisqyv @afmckinney 
Candice:  Doing the upgrader might be a little tricky.   Ask Andrew or Jeff or me for help.   See versioning.js, but that might not tell you enough.

**Comment by halatmit** [comment]
@candicefan @jisqyv 
Candice:
This doesn't seem to bee handing the upgrading correctly.   Doing what's required is a little tricky.  Please sit down with Jeff and/or me in person, and we can go over in detail what needs to be done.

**Comment by ewpatton** [comment]
This is going to be merged as part of the Blockly update.

**Comment by moliata** [comment]
@ewpatton that pretty much means that this PR should be closed?

**Comment by ewpatton** [comment]
@moliata It will need to be rebased and some minor things will need to be fixed given the extent of the changes in the Blockly update, but I don't expect it to be too much work. I would be hesitant to close the PR given that 90% of the work has been done.

**Comment by ewpatton** [comment]
Blocked by #989

**Comment by ewpatton** [comment]
Merged as part of #2184

**Pull request closed without merging**
