### PR TITLE
Implement list reverse block

### PR DESCRIPTION
**Pull request by kuan9611**
Issue: #1347 

Introduce a `reverse list` block to list operations that reverses the order of input list and returns the result as a new list; the original list is unaffected. Update relevant documentation to include the new block.

### CODE REVIEW

**Comment by ewpatton** [comment]
@kuan9611 You should also increase the value of BLOCKS_LANGUAGE_VERSION in YaVersion.java (and add a corresponding comment), and add an entry under "Language" in versioning.js to handle the upgrade (which should be noUpgrade because you are only adding a block).

**Comment by AppInventorWorkerBee** [comment]
Can one of the admins verify this patch?

**Comment by ewpatton** [comment]
@AppInventorWorkerBee ok to test

**Comment by AppInventorWorkerBee** [comment]
All tests passed. +1 Verified.

**Pull request merged**
