### PR TITLE
Vagrantfile: Add Libvirt support

### PR DESCRIPTION
**Pull request by peanutbutterandcrackers**
@ewpatton - Here's Libvirt support, [as promised](https://github.com/mit-cml/appinventor-sources/issues/2369#issuecomment-761570850), Cap'n!

### CODE REVIEW

**Comment by AppInventorWorkerBee** [comment]
Can one of the admins verify this patch?

**Comment by jisqyv** [comment]
@AppInventorWorkerBee ok to test

**Comment by ewpatton** [comment]
@AppInventorWorkerBee retest this please

**Comment by jisqyv** [comment]
@peanutbutterandcrackers So when I try this on my linux system I get:

Stderr: VBoxManage: error: VT-x is being used by another hypervisor (VERR_VMX_IN_VMX_ROOT_MODE).
VBoxManage: error: VirtualBox can't operate in VMX root mode. Please disable the KVM kernel extension, recompile your kernel and reboot (VERR_VMX_IN_VMX_ROOT_MODE)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component ConsoleWrap, interface IConsole

I'm not certain if it is reasonable that I'm told to recompile my kernel (I know that isn't your message).

I'm sure I can eventually make this work, but I'm not certain if MIT want's to support this change, as in being in a position to help people debug why this isn't working for them.

**Comment by ewpatton** [comment]
Hmm, given the error it seems like Vagrant is preferring virtualbox to libvirt. It might be we have to pass additional flags to indicate the preferred virtualization system. @peanutbutterandcrackers  you might want to update the readme to include what flags are needed for libvirt over virtualbox

**Comment by peanutbutterandcrackers** [comment]
Hmm.... I suppose that because I do not have virtualbox installed on my system, a mere `vagrant up` is sufficing for me. For other's, however, I suppose one has to use `vagrant up --provider=libvirt`...?

@jisqyv - Hmm... Am I correct in assuming that you merely typed `vagrant up` and it didn't work (essentially, this change (somewhat) broke virtualbox support) ? Does `vagrant up --provider=virtualbox` (or something similar) work? Does `vagrant up --provider=libvirt` work?

I was hoping that a mere `vagrant up` would try the default virtualbox provider (or libvirt, if virtualbox isn't available), and `vagrant up --provider=libvirt` would try libvirt...

@ewpatton - I will update the README as soon as I get more info from @jisqyv, Cap'n!

**Comment by jisqyv** [comment]
@peanutbutterandcrackers I have both virtualbox and libvrt (KVM). I typed "vagrant up" while I was running a KVM vm. So you see the result. I'm in a meeting now, but I'll try --provider=libvirt when its done.

**Comment by jisqyv** [comment]
@peanutbutterandcrackers So vagrant does not come with a libvirt provider. There is a third party provider available on GitHub. But I have no tried it.

**Comment by jisqyv** [comment]
@peanutbutterandcrackers So if I shutdown my KVM/Libvirt VM I can use the virtualbox provider.

**Comment by peanutbutterandcrackers** [comment]
@jisqyv - If you're using a debian-derivative, you could `apt install vagrant-libvirt` to install it.

**Comment by peanutbutterandcrackers** [comment]
Just so that I don't waste anybody's time: I just discovered a major issue with this PR (`rsync` should not `--delete` anything). I'll fix it, test it, and then re-submit this. Leaving open for the time being.

**Comment by peanutbutterandcrackers** [comment]
Just committed a cardinal sin of `--force push`-ing.

The issue is now resolved.

Explanation: Everytime the virtual machine was started w/ `vagrant up --provider=libvirt`, `rsync` would `--delete` the binaries in `/vagrant` in the vm. That does not happen anymore now. Also, removed the `-z` flag. Because why not. Most compressing in the host and then decompressing in the vm takes much time. And since for the most part it will be on the same machine, I don't think it's all that necessary anyways. Added `--update` rsync flag instead.

**Comment by peanutbutterandcrackers** [comment]
This PR is being replaced by https://github.com/mit-cml/appinventor-sources/pull/2554

**Pull request closed without merging**
