### PR TITLE
Added video and image enlargement

### PR DESCRIPTION
**Pull request by msowder**
Created a modal pop-up for videos and images from the tutorial. Added changes
to separate file to create a new class that extends Frame.

### CODE REVIEW

**Comment by paulmedwal** [comment]
You can test this by typing this in your console:

postMessage({type:"video", youtubeId:"HY_oQC2UEQA"},"*")

postMessage({type:"img", imageId:"http://appinventor.mit.edu/yrtoolkit/images/snapRemix/picButtonClick.png"},"*")

**Comment by jisqyv** [comment]
@msowder @paulmedwal The code works (Good Job!). However if I click outside of the area being displayed (either the image or the video), the window closes. Is that the desired behavior? Or do you want to force the person to click the "Close" button in order to dismiss the window?

**Comment by paulmedwal** [comment]
@jisqyv That was desired behavior, we wanted it to be relatively easy to close the video/picture.

**Comment by jisqyv** [comment]
@msowder @paulmedwal LGTM -- I am getting ready to merge this change. It is currently on Gerrit running the final unit tests. I made some changes:

1. I fixed the copyright on the new module.
2. I re-indented the new module to conform to our convention.
3. I added this code:

    // Adds Image
    Image image = new Image(img);
    image.addLoadHandler(new LoadHandler() {
        public void onLoad(LoadEvent evt) {
          dialogBox.center();
        }
      });

This code is in the createImageDialog function. The problem is that when you display the dialog box, the image hasn't been loaded into the browser so the browser doesn't know its size and cannot center it properly. This code (adding the addLoadHandler) will recenter the dialog after the images has finished loading.

**Comment by jisqyv** [comment]
MERGED -- Look at the commit on master to see the final version that was merged.

**Pull request closed without merging**
