### PR TITLE
Implement updates to Tracking module for GA4

### PR DESCRIPTION
**Pull request by ewpatton**
Change-Id: I1a8317370edfb67993d69090582248687a8bbc87

### CODE REVIEW

**Comment by barreeeiroo** [comment]
Just a quick comment on this PR, as a possible future enhancement. We have also upgraded our Google Analytics implementation from Universal Analytics to Google Analytics 4, and we noticed that the event model in GA4 is different from UA.

In UA, the event model looks as follows:

```js
gtag('event', '<action>', {
  'event_category': '<category>', // Btw, right now this is set to 'action' and not 'event_category' (?)
  'event_label': '<label>', // This one is set as 'label' rather than 'event_label' in AI2
  'value': '<value>'
});
```

But in GA4, the event model is open and you can customize it:

```js
// UA Example
gtag('event', 'Enable', {
  event_category: 'Settings',
  event_label: 'Dark mode'
});

// GA4 Possibility
gtag('event', 'settings_update', {
  setting: 'mode',
  status : 'dark'
});
```

We could provide a better tracking class in AI2 with GA4 to send customized data depending on the event.

Source: [Comparison of UA and GA4 events](https://developers.google.com/analytics/devguides/migration/measurement/events#gtag.js-ua)

**Comment by ewpatton** [comment]
@barreeeiroo That might be a good long term goal, but I'm not sure we want to hold up merging this change. Also, we will want to think about what that looks like more specifically because this code is mostly called from Java, so we don't have a compact way to easily express dictionaries like in your example.

**Comment by barreeeiroo** [comment]
@ewpatton Yeah, I know Java is not as flexible as Javascript. I was just pointing out how Google recommends to apply this migrating, but the current implementation will definitely work and will keep retrieving those events.

**Review by jisqyv — APPROVED** [review]
LGTM, I'm seeing tracking from ai2-test showing up...

**Pull request merged**
