### PR TITLE
Error message while typing an incorrect project name

### PR DESCRIPTION
**Pull request by KeithGalli**
Made changes so that the first instance an error is made while you are typing a project name, an error message pops up letting you know what is wrong with the name you are typing in. One thing I wasn't sure how to handle was someone pasting a name into the textbox.

### CODE REVIEW

**Comment by jisqyv** [comment]
@KeithGalli I'm not sure I like this change. I'm not used to having errors pop up while I am typing input.

**Comment by KeithGalli** [comment]
@jisqyv Would you like the change better if a red text error message popped up on the textbox and didn't stop the user from typing, but remained there while the text didn't match the required pattern?

**Comment by jisqyv** [comment]
@KeithGalli Yeah, I like that better.

**Comment by KeithGalli** [comment]
@jisqyv I have a test instance up with an updated textbox validation. The link to this is http://appinv-projectname-errorcheck.appspot.com/ . Let me know what you think about these changes.

**Comment by jisqyv** [comment]
I'm going to work on your reviews this weekend :-)

-Jeff

On Fri, May 29, 2015 at 9:58 PM, KeithGalli <notifications@github.com>
wrote:

> @jisqyv <https://github.com/jisqyv> I have a test instance up with an
> updated textbox validation. The link to this is
> http://appinv-projectname-errorcheck.appspot.com/ . Let me know what you
> think about these changes.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mit-cml/appinventor-sources/pull/373#issuecomment-106973465>
> .
>



-- 
_______________________________________________________________________
Jeffrey I. Schiller
Information Systems and Technology – MIT App Inventor
Massachusetts Institute of Technology
77 Massachusetts Avenue  Room E17-110A, 32-392
Cambridge, MA 02139-4307
617.910.0259 - Voice
jis@mit.edu
http://jis.qyv.name
http://appinventor.mit.edu
_______________________________________________________________________

**Comment by jisqyv** [comment]
@KeithGalli Is the code from appinv-projectname-errorcheck.appspot.com in this pull request?

**Comment by KeithGalli** [comment]
@jisqyv No it currently is not. The source code for appinv-projectname-errorcheck.appspot.com can be found at https://github.com/KeithGalli/appinventor-sources/tree/projectNameValidator . Let me know if you can find all the changes easily enough.

**Comment by jisqyv** [comment]
I actually like the look of the error, so please create a pull request.

-Jeff

On Sat, May 30, 2015 at 3:09 PM, KeithGalli <notifications@github.com>
wrote:

> @jisqyv <https://github.com/jisqyv> No it currently is not. The source
> code for appinv-projectname-errorcheck.appspot.com can be found at
> https://github.com/KeithGalli/appinventor-sources/tree/projectNameValidator
> . Let me know if you can find all the changes easily enough.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mit-cml/appinventor-sources/pull/373#issuecomment-107076477>
> .
>



-- 
_______________________________________________________________________
Jeffrey I. Schiller
Information Systems and Technology – MIT App Inventor
Massachusetts Institute of Technology
77 Massachusetts Avenue  Room E17-110A, 32-392
Cambridge, MA 02139-4307
617.910.0259 - Voice
jis@mit.edu
http://jis.qyv.name
http://appinventor.mit.edu
_______________________________________________________________________

**Comment by KeithGalli** [comment]
@jisqyv I created a new pull request, with the updated code. See pull request #402 . Thank you!

**Comment by KeithGalli** [comment]
Closing this pull request, because of the new one I created for the same feature

**Pull request closed without merging**
