### PR TITLE
Fix RunD8 errors when using Windows with Java 11

### PR DESCRIPTION
**Pull request by ewpatton**
This is a workaround for an issue in the buildserver using Java 11 on Windows where the classpath for d8 is so long it causes an exception spawning the d8 process. We make use of a new feature of Java 9 onward that allows for specifying command line arguments in a file and then inserting them into the argument list by using the `@` symbol and the filename to splice the arguments into the list.

Tested on Windows 11 using Java 11 and on macOS 14 using Java 11.

### CODE REVIEW

**Comment by Soft-Buddy** [comment]
```
     [java] [RunD8] ERROR: C:\Test\appinventor\build\buildserver\dexCache\classes.dex
     [java] [RunD8] Task errored in 66.218 seconds
     [java] Apr 02, 2024 1:14:55 PM com.google.appinventor.buildserver.BuildServer checkMemory
     [java] INFO: Build 1 current used memory: 19782056 bytes
     [java] Apr 02, 2024 1:14:55 PM com.google.appinventor.buildserver.BuildServer buildAndCreateZip
     [java] SEVERE: Build 1 Failed: 1 [RunD8] ERROR: C:\Test\appinventor\build\buildserver\dexCache\classes.dex
     [java]
     [java] Apr 02, 2024 1:14:55 PM com.google.appinventor.buildserver.BuildServer$1 run
```
Compiles finely since start but fails at the end with a `not-so-descriptive` error.

**Comment by muskan6564** [comment]
[RunD8] ERROR: C:\Users\LENOVO\appinventor-sources\appinventor\build\buildserver\dexCache\classes.dex

New issues spotted @ewpatton sir

**Comment by Soft-Buddy** [comment]
@ewpatton any news?

It's also reported here : https://community.appinventor.mit.edu/t/createprocess-error-206-the-filename-or-extension-is-too-long/106972/23

**Review by SusanRatiLane — APPROVED** [review]

**Comment by SusanRatiLane** [comment]
Confirmed that the companion on this branch with the filename adjustment compiles.

**Pull request merged**
