### PR TITLE
Enable import/export block code as PNGs

### PR DESCRIPTION
**Pull request by ewpatton**
This commit adds a feature to download individual blocks as PNG
files. In the PNG file there will be a code chunk that stores the
Blockly XML representation for the block. Dragging and dropping one of
these images into the blocks editor will import that block. This can
be useful for writing tutorials because the images of the blocks will
also contain the code, so one can drag the block image into the
workspace from another page. In order for the cross-site drag to work,
the server serving the document must allow CORS from the App Inventor
server.

Change-Id: I524bbfbef739554884caa31a8b677ce1bcc893d1

### CODE REVIEW

**Comment by ewpatton** [comment]
So this is a fun little pull request that recreates something I had prototyped for PUNYA but lost to the sands of time. The basic idea is that you can right click on a block and export it to PNG (similar to workspace export). In this PNG though there will be an additional optional chunk that includes the Blockly XML code. One can then drag these special PNGs from either the file system or a CORS-enabled server to import the blocks into the block workspace. The hope is that we could use this feature for improving tutorials, documentation, and other materials published on the web.

**Comment by ewpatton** [comment]
I should also note that I have only tested this in Chrome so far.

**Comment by PeterMathijssen** [comment]
Is the name of the png file also autogenerated?

**Comment by ewpatton** [comment]
@PeterMathijssen I implemented your suggestion. If there are multiple blocks the file will be called blocks.png, same as when you export the whole workspace (rather than the autogenerated names).

**Comment by PeterMathijssen** [comment]
Great. I was thinking what would be best. Now every png will have the English name and not for instance the translated name. Could you when you use this for instance... .appendField(Blockly.Msg.**LANG_LISTS_ADD_ITEMS_TITLE_ADD**)
use this as the filename? Like i said i don't know what would be best.

**Comment by ewpatton** [comment]
I'll take a look, but I don't think it will be as trivial as it seems.

**Comment by PeterMathijssen** [comment]
Maybe start with the blocks in English and see if users from other countries would have a need for them to be in their language?

**Comment by ewpatton** [comment]
Found two bugs:

1. Top level blocks don't appear to get the Download as PNG menu item
2. Sometimes the background doesn't get reset correctly after drop completion.

**Pull request merged**
