### PR TITLE
Add drop down menu

### PR DESCRIPTION
**Pull request by ZhengCornell**
In SimpleVisibleComponentsPanel.java. I changed the checkboxPhoneTablet from CheckBox to ListBox to add more screen size options for designers. Also added four final fields for monitor option and edited changePreviewSize() in MockForm.java. Also added and edited previewTabletSize() previewMonitorSize() previewPhoneSize() in OdeMessage.java.
Now, designers can change the screen size based on these three options

### CODE REVIEW

**Comment by ewpatton** [comment]
I also wonder if it would make sense to add the resolution in parentheses in the dropdown entries so that it's more clear what the sizes are. I don't know what the monitor size is, for example (and the others I know only because I've been working with App Inventor long enough).

**Comment by ZhengCornell** [comment]
Sorry for the negligence. I will check it and pr again ASAP. And for the resolution, do you mean that designers can see the specific pixel width and pixel height for each options?

**Comment by ewpatton** [comment]
Yes, by resolution I mean size in pixels. Thanks.

**Comment by ewpatton** [comment]
Superseded by #1557

**Pull request closed without merging**
