### PR TITLE
Make TAP_THESHOLD  a user settable property. closes #2366

### LINKED ISSUE #2366: Dragging on the canvas
**Describe the desired feature**

Could someone take a look at the canvas component? The idea is to modify the component so that some event returns all the coordinates from touching the canvas to moving to releasing. There is a "when.CanvasDraged" event but it shows the position only after 15 pixels. Link to the topic on the forum:

https://community.appinventor.mit.edu/t/asking-for-the-canvas-dragged-event/24264

### PR DESCRIPTION
**Pull request by Himanshu2107**

### CODE REVIEW

**Comment by AppInventorWorkerBee** [comment]
Can one of the admins verify this patch?

**Comment by Himanshu2107** [comment]
closes #2366

**Comment by Himanshu2107** [comment]
#2366

**Comment by ewpatton** [comment]
@Himanshu2107 You'll want to revert the merge from master.

**Pull request closed without merging**
