### PR TITLE
Create link to web published version in reference/other/backpack.html

### PR DESCRIPTION
**Pull request by halatmit**

### CODE REVIEW

**Comment by halatmit** [comment]
@jsheldonmit @jisqyv 
I tweaked the formatting to make the web published version look better.   It's still funny, but I suspect this is the best one can do in Google Docs.

**Comment by halatmit** [comment]
@jisqyv @jsheldonmit @ram8647 @graceRyu 
Jeff is currently the owner of the (non-web) version:
https://docs.google.com/document/d/14-VRxyUNDsYqzFplWHspThbkTQTL8gr0siAqPqYW5do/edit

Jeff, I think you should add the  Ralph and Grace as owners, so that they can see the public comments, and edit the doc in response.

**Comment by jisqyv** [comment]
@halatmit I've added Ralph and Grace. Btw. Can you look at #569. If you give it an LGTM, I can get it deployed as a minor release (no components).

**Comment by halatmit** [comment]
LGTM, but add a comment explaining that the instance might not exist for generics.  (That's the issue here, right?)

**Comment by jisqyv** [comment]
LGTM

**Comment by jisqyv** [comment]
MERGED

**Pull request closed without merging**
