### PR TITLE
Implement UsesAssets support for extensions

### LINKED ISSUE #1034: Add support for @UsesAssets with extensions
Inspired by a student project, it would be useful to allow for the use of the `@UsesAssets` in extensions to include assets into the companion and compiled apps.

### PR DESCRIPTION
**Pull request by ewpatton**
This PR provides an implementation of support for the `@UsesAsset` annotation in extensions.

If one has an extension at `components/src/com/example/extension/Foo.java`, assets are placed in an `assets` directory at the same level of `Foo.java`. For example, if `Foo.java` contains `@UsesAssets(fileNames = "index.html")`, then the file at `components/src/com/example/extension/assets/index.html` will be included in the compiled extension. Extension assets are segmented by package name, so that `index.html` defined in two different extensions do not collide in the final app.

During extension development, one can also keep `@SimpleObject(external = false)` so that assets referenced by an extension class will be available in a custom companion build. When external is false, extensions are loaded from the companion's assets directory in the file system, typically on `/sdcard`.

Closes #1034

### CODE REVIEW

**Comment by conorshipp** [comment]
I've just done some testing on ai2-test and found that when adding a marker to the map, I get the following runtime error: `Error from Companion: Unable to load SVG from assets`. I am using companion version 1.46bt3 which was downloaded from the Help -> Companion Information menu in ai2-test. Since the release notes state that this server has been updated with this PR, I suspect that it is most likely the issue.

**Comment by ewpatton** [comment]
Is this for the built in marker asset or custom assets?

**Comment by conorshipp** [comment]
I just dragged a marker from the palette onto the map so it's the default asset.

**Comment by jisqyv** [comment]
@ewpatton @conorshipp This code is now deployed on ai2-test (along with the current version of ucr and master). There is a new Companion 2.46bt4 and the buildservers are updated as well. Enjoy.

**Comment by conorshipp** [comment]
Just tested again on ai2-test and it looks like it's fixed I added a few markers and no errors appeared.

**Pull request merged**
