### PR TITLE
Change division so that dividing by 0 signals an error rather than re…

### PR DESCRIPTION
**Pull request by halatmit**
…turning NaN

### CODE REVIEW

**Comment by halatmit** [comment]
Issue #817

**Comment by jisqyv** [comment]
@halatmit I'm not sure I agree with this change. With it, a divide by 0 error will crash a packaged application. There is no way to catch a RuntimeException. It would be better to create an error that can be caught in Form and handled by the user.

**Comment by halatmit** [comment]
Good point.   I wasn't thinking.   I'll see if I can fix that.



== Hal

Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.

**Comment by halatmit** [comment]
@jisqyv @afmckinney I messed something up and confused myself.  I think this PR is obsoleted by #819

**Comment by jisqyv** [comment]
Replaced with #819

**Pull request closed without merging**
