### PR TITLE
reconcile block deletion confirmation (#1173)

### PR DESCRIPTION
**Pull request by ZhengCornell**
Reconcile four deletion confirmation (delete from workspace, delete from block itself, drag to trashcan, press delete key)

### CODE REVIEW

**Comment by AppInventorWorkerBee** [comment]
Can one of the admins verify this patch?

**Comment by ewpatton** [comment]
@AppInventorWorkerBee ok to test

**Comment by ewpatton** [comment]
LGTM, but I'm going to push a change that makes it so that one can use the escape and enter keys to dismiss the dialog similar to how the browser prompt works.

**Comment by ewpatton** [comment]
Marking this as on hold temporarily until we resolve the lib/blockly issue on master.

**Pull request merged**
