### PR TITLE
Added Image.RotationAngle method.

### PR DESCRIPTION
**Pull request by jisqyv**
Change-Id: Ia0b58453e3f93b6111a399d669bc850c75bc70a3

### CODE REVIEW

**Comment by jisqyv** [comment]
@halatmit Please review. this PR replace #648 which I will close. You will recognize this as your code with the addition of the SdkLevel checks. I have verified it under 4.4.4 (it works) and 2.2 (it gives an error message).

**Comment by halatmit** [comment]
LGTM

**Comment by jisqyv** [comment]
On Gerrit for the UCR Branch

**Comment by jisqyv** [comment]
@halatmit MERGED

**Pull request closed without merging**
