### PR TITLE
Introducing ant doctor 🐜👨‍⚕️💊

### PR DESCRIPTION
**Pull request by pavi2410**
### Motivation
I've been noticing a lot of topics in the community where people face problems with setting up their environment for App Inventor development. This causes inconvenience to both the newcomers and the veterans. The error logs produced aren't beginner-friendly and people can sometimes overlook the requirements in the README file. Such common issues can be identified automating the process, without us wasting time looking for issues in the error log manually.

The doctor can identify these symptoms:
- [x] Check if Java is installed
- [x] Check the required version of the Java installation
- [x] Check if git is installed
- [x] Check whether the git submodules are present (A most common source of error)
- [ ] Check if 32-bit dependencies are installed on 64-bit Linux system.
- [x] Check Google Cloud/App Engine SDK installation
- Reply below if I missed something

### Preview
Success | Failure
--- | ---
image | image

There could be another command `ant fix` which would fix common problems automatically. (Not yet implemented)

### CODE REVIEW

**Comment by ewpatton** [comment]
You should also update the README to include a note about this. Also, I'm not sure how the Java detection should work given that Java is needed to run ant. It seems to me that by virtue of running the script it confirms that at least some version of Java is present.

**Comment by rupesh-kumar-lpu** [comment]
Hi @pavi2410 I feel the idea is good to provide Ant doctor, it will help the beginners and we can skip the java checking step as @ewpatton mentioned. Will it be better to automate the process of installing the necessary java version and git environment by asking the user via a prompt? Will it be better to include checking the google cloud environment? thanks

**Comment by pavi2410** [comment]
> I'm not sure how the Java detection should work given that Java is needed to run ant.
You are right. I'll remove that.

> It seems to me that by virtue of running the script it confirms that at least some version of Java is present.
Yes, that's the goal.

> Will it be better to automate the process of installing the necessary java version and git environment by asking the user via a prompt(yes/no)?
I think that will be too much for a simple build script. IMO, people should be able to download and install the necessary components. The goal of this tool is to help them identify the issues and possibly offer them a fix.

> Will it be better to include checking the google cloud environment?
Of course! I knew I missed something!

**Comment by pavi2410** [comment]
> You should also update the README to include a note about this. Also, I'm not sure how the Java detection should work given that Java is needed to run ant. It seems to me that by virtue of running the script it confirms that at least some version of Java is present.

@ewpatton I've made the necessary changes. Though, I feel that writing this as an Ant target was a wrong choice. I should've written this in shell scripts. In the coming days, I'll probably rewrite these this in shell scripts for maximum possible checks. So, **please do not merge this**. Thanks!

**Comment by pavi2410** [comment]
Superceded by #2358

**Pull request closed without merging**
