### PR TITLE
GitHub Actions

### PR DESCRIPTION
**Pull request by Sander0542**
# GitHub Actions
This Pull Request contains GitHub Actions to automate building and testing of the sources on every push.

## Build
- Set up JDK 1.8
- Checkout submodules
- Install 32-bit dependencies
- Make Auth Key
- Build appinventor
- Run Tests
- Upload Test Reports to Artifacts
- Build Companion
- Upload Companion to Artifacts

### CODE REVIEW

**Comment by ewpatton** [comment]
@Sander0542 We already do this with Jenkins, so it's not clear what this is accomplishing (especially since it doesn't run any tests).

**Comment by Sander0542** [comment]
@ewpatton I know there are already checks with Jenkins, but when someone forks the repo and starts editing files, then they can't use Jenkins. The point of GitHub Actions is that it works for everyone who forks the repo and wants to edit it.

**Comment by Biangkerok32** [comment]
@Sander0542 Thanks ☺️ this help me

**Comment by ewpatton** [comment]
We are going to need to think about this. Technically, people should be running the unit tests themselves locally as part of their development process, not relying on Jenkins (or GitHub) to fail them if their code breaks the tests. I'm not convinced of adding the actions as a technical solution for lack of rigor. Also, these artifacts that you are publishing as part of the action, where exactly do they end up?

**Comment by Sander0542** [comment]
The artifacts are published to the GitHub Actions (link below). You can download them to your local system. The build generates a log which is split up in multiple sections defined in the workflow file. You can still view and download the complete log.

Overview - https://github.com/Sander0542/appinventor-sources/actions/runs/44951612
Build Log - https://github.com/Sander0542/appinventor-sources/runs/467442955?check_suite_focus=true

**Comment by Sander0542** [comment]
@ewpatton is the Pull Request itself fine or do I need to add some check to the action?

**Pull request merged**
