### PR TITLE
Provide a Menu Item to Update the Companion

### PR DESCRIPTION
**Pull request by jisqyv**
Provide a Menu Item under the “Help” Menu to trigger a manual update
of the Companion. Also fix a bug in the Companion itself so that the
correct CORS headers are returned during the update (also put a work
around in replmgr.js to deal with the non-fixed
Companion). Automatically disconnect the Companion after the update so
the user doesn’t have to use the “Reset Connection” item before
connecting to the newly installed companion.

Change-Id: I31215863163974cf8f23bb68b03200cad8229ae5

### CODE REVIEW

**Comment by jisqyv** [comment]
@halatmit @afmckinney Please Review

**Comment by halatmit** [comment]
looks OK, but I did not test.   so I guess LGTM

**Comment by jisqyv** [comment]
I'm assuming you meant to put the "OK to move to Gerrit" label... not "reply to review" because I don't see a question...

**Comment by halatmit** [comment]
LGTM

**Comment by halatmit** [comment]
I mean that  I didn't test it.   But I just changed this to LGTM



== Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.

**Comment by jisqyv** [comment]
I tested it though...

**Pull request merged**
