### PR TITLE
Fixed Markdown errors in README.md

### PR DESCRIPTION
**Pull request by david2410**
I put some spaces to fix Markdown errors in README.md

### CODE REVIEW

**Comment by josmas** [comment]
Was there a change in the rendering engine? It was correct for years, no idea what's changed to make it look wrong now.

**Comment by pavi2410** [comment]
Yes, because this [doc](-$$--$) says, (in 4.2 ATX Headings)

> The opening sequence of # characters must be followed by a space or by the end of line.

Eg-

#Not Working :(
# Working :)

**Comment by jisqyv** [comment]
LGTM

**Comment by jisqyv** [comment]
MERGED (via Gerrit)

**Pull request closed without merging**
