### PR TITLE
Rename Project added in "Projects" menu

### PR DESCRIPTION
**Pull request by ColinTree**
Related: #905 

image
image
image

### CODE REVIEW

**Comment by ewpatton** [comment]
@ColinTree I'm wondering if there is a more effective way of doing this. Right now this will duplicate all of the entities and then deletes them. Since we pay for every data store operation it would be better to rename/update the existing entities.

**Comment by ColinTree** [comment]
I had tried to change the projectName successfully, but it is only on the server.
At this point, the client would not load the new project correctly until the whole webpage is refreshed, because the project name is cached everywhere, like in the ProjectNodes.
Unless a big change is maded, we still needs to re-get the project data. So should i make a change on the scructure?

**Comment by ColinTree** [comment]
The currently status of this thread:
all the rename processes are now in one request by explorer, named "rename", and do "copy" and "delete (the old project)" in the server

**Comment by AppInventorWorkerBee** [comment]
Can one of the admins verify this patch?

**Pull request closed without merging**
