### PR TITLE
Remove comment about supporting SDK level 3 in Compiler.java

### PR DESCRIPTION
**Pull request by halatmit**

### CODE REVIEW

**Comment by josmas** [comment]
@halatmit I am being very fussy here, but the sentence before the one you deleted should end in a full stop, not a comma. :)

I am at the moment making changes in Compiler.java; I think there's extra info for the Texting component that it's not needed. I can do the fix for this if you don't want to push another change.

**Comment by halatmit** [comment]
Sure, please do the fix.

Thanks,

...Whoops, I mean

Thanks.



== Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.

**Comment by jisqyv** [comment]
LGTM

**Comment by jisqyv** [comment]
MERGED

**Pull request closed without merging**
