### PR TITLE
Maps documentation bug Issue#2645

### PR DESCRIPTION
**Pull request by devarsh-mavani-19**
There was problem in description of showzoom feature in http://ai2.appinventor.mit.edu/reference/components/maps.html. see Issue #2645

### CODE REVIEW

**Comment by AppInventorWorkerBee** [comment]
Can one of the admins verify this patch?

**Comment by ewpatton** [comment]
@AppInventorWorkerBee ok to test

**Comment by ewpatton** [comment]
@devarsh-mavani-19 For components, the Javadoc on the component methods serve as the ground truth for documentation. Make sure that you update the Javadoc in Map.java to match your changes here otherwise they will get overwritten on a rebuild of the documentation.

**Comment by devarsh-mavani-19** [comment]
hey @ewpatton I also udpated javadoc can you please check it? Thanks

**Comment by devarsh-mavani-19** [comment]
> @devarsh-mavani-19 For components, the Javadoc on the component methods serve as the ground truth for documentation. Make sure that you update the Javadoc in Map.java to match your changes here otherwise they will get overwritten on a rebuild of the documentation.

@ewpatton I have changed the javadoc. Can you please review this? Thanks

**Review by ewpatton — APPROVED** [review]

**Pull request merged**
