### PR TITLE
Search Feature Impl.

### PR DESCRIPTION
**Pull request by abhijit5893**
Search Feature Implementation. All the Blockly code that has been introduced has been marked with comments.

Abhijit Suresh (GSOC 2016)Search Feature Implementation. All the Blockly code that has been introduced has been marked with comments.

Abhijit Suresh (GSOC 2016)

### CODE REVIEW

**Comment by abhijit5893** [comment]
@josmas Please take a look

**Comment by jisqyv** [comment]
@abhijit5893 two questions. Is this code ready to be reviewed and merged? Where did the translations come from? (Google Translate for example, or native speakers?)

**Comment by abhijit5893** [comment]
@josmas  It is ready to be reviewed. The translations came from Google Translate.

**Comment by josmas** [comment]
@abhijit5893 just to clarify, @jisqyv was the one asking.
Have you made any of the modifications suggested in the last discussion thread? or is it the same code you have in the test instance?
Who was that you've been working with through GSoC? Have they reviewed this?

**Comment by abhijit5893** [comment]
This version is the rebased version of the last discussion thread. It is the same code that I have in the test instance. I have been working with Benjamin @bxie. He has already reviewed it.

**Comment by bxie** [comment]
I have yet to review the absolute latest instance of the appspot. I'll look at it by tomorrow.

**Comment by bxie** [comment]
Reviewed code and it looks fine.
Tested instance as well. I found bugs that should be resolved but they are minor.
Bugs found:
1) When filter applied to previous search, functionality is unusual.
To replicate: With no filter selected, type something into search box that yields results and press enter. Apply a filter which should remove results.
Expected: filter is applied and graying of blocks updates accordingly.
Actual: No change. Filter does not appear to be applied.
Severity: Minor (S3)

2) Filter dropdown changes sizes.
To replicate: Check box for filter. Uncheck box.
Expected: filter dropdown doesn't change
Actual: Dropdown narrows (and widens again after clicking on it).
Severity: Trivial (S4)

@abhijit5893 How much testing did you do? These bugs are not very severe, but I do want to ensure that you rigorously tested this feature.

**Comment by josmas** [comment]
@bxie @abhijit5893 there were also a number of suggestions in an email thread that need to be taken care of (or at least discussed) before this could be merged.

**Comment by jisqyv** [comment]
@josmas Where is the discussion thread so I can review it?  -Jeff

**Comment by bxie** [comment]
Discussion Thread: https://groups.google.com/forum/#!searchin/app-inventor-dev/abhijit%7Csort:relevance/app-inventor-dev/_mZALZCaHmQ/CILfebaRCAAJ

What changes were made and what remains is explained at http://abhijit-suresh.herokuapp.com/
@abhijit5893 please provide more insight on what changes were made and not made.

**Comment by jisqyv** [comment]
@abhijit5893 This is a great start. However where it is most useful, large projects, it has some issues.

- A search on a large project takes a long time, with no user feedback. The interface locks up.
- It does too much work on the UI thread without relinquishing control. The effect is that the user is eventually faced with the browser generated "This script is taking too long" dialog. If they kill the script, it kills app inventor.

I would recommend re-factoring so that if there are more then "N" blocks (I'm not sure of what the threshold for N should be, but experimentation may reveal it) then a progress dialog (or at least a "spinner") is displayed. After every so many blocks are searched, the state of the search is checkpointed, and the search is re-queued to run again and control is returned. This will prevent the "too long" dialog from the browser. In fact it would be cool if the dialog had a cancel button on it. If this was pressed, it would set a flag that would cause the search to terminate on its next checkpoint.

-Jeff

**Comment by abhijit5893** [comment]
@jisqyv Cool. Thanks for the update. Can you point me to a large project which I can use to recreate the issue. @josmas @jisqyv  @bxie Here is the [link](https://docs.google.com/document/d/1aVFejI7B29xmWRFgpSHT4j7TCSrIEBe3PG5HKK__5Qg/edit#) to the proposal which details what changes were made and what are pending. Also, if you would like to schedule a meeting to discuss this issue further. Please let me know. I'm bit occupied this week but can start working from the next week.

**Comment by ewpatton** [comment]
This PR will be affected by the Blockly update, so we will need to assess what needs to be done to update this based on those changes.

**Comment by abhijit5893** [comment]
@jisqyv  @bxie  I dont want to leave this hanging. Please let me know what I can do to merge this feature with the current version of AI.

**Comment by kkashi01** [comment]
This would be a great feature to have

**Comment by ewpatton** [comment]
The challenge here is that there were a lot of changes to Blockly core, which we no longer keep as part of the repo but maintain as a separate repository via a submodule. We will need to factor out the changes to core where appropriate and then rebase the change onto the current master before this can be incorporated.

**Comment by moliata** [comment]
Also, there is like 10 conflicting files. So yeah

**Comment by ewpatton** [comment]
This makes too many changes to Blockly core. We also think it would be useful to design the appropriate data structures and associated UI/UX so that performance is acceptable. We should also consider touching base with Google about what would make sense for them (and there are competing implementations there).

**Pull request closed without merging**
