### PR TITLE
Update merger tool documentation

### PR DESCRIPTION
**Pull request by halatmit**

### CODE REVIEW

**Comment by jisqyv** [comment]
@halatmit The merger.html file is missing...

**Comment by halatmit** [comment]
I think that file needs to go on appinventor.mit.edu, not the appinventor
source.   I think I already fixed it there.  Check  the URL in the new page
in /other/...

Or we can look together later in the week.


== Hal

Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.

**Comment by halatmit** [comment]
The merger document should be pointed to at

https://docs.google.com/document/d/15cEkliGmGxLX2muxysEOrMbPJnjmmglMtMVhbDpLZFE/edit#heading=h.uqq1hmq6y3rx

**Comment by halatmit** [comment]
Hal a and Jeff will fix by Dec. 8

**Comment by jisqyv** [comment]
@halatmit LGTM -- Note: I removed the change to userinterface.html, it should be part of the json change (which we need to discuss).

**Comment by jisqyv** [comment]
@halatmit MERGED

**Comment by halatmit** [comment]
OK.  Let's talk about this next week.


== Hal

Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.

**Pull request closed without merging**
