### PR TITLE
Allow renaming template projects on name conflict

### PR DESCRIPTION
**Pull request by ewpatton**
Change-Id: Id7b28db3d1c44c1a01a43a40c6e350b0b67b5687

### CODE REVIEW

**Comment by ewpatton** [comment]
@stezelMIT @bobparks This addresses the issue reported today.

@jisqyv I've assigned this to you. I expect it's not possible to deploy it as a hotfix on ai2 before Saturday morning. If that's the case, we should definitely put it into the nb196 milestone.

**Comment by stezelMIT** [comment]
We have a plan in place for Saturday in case this is not an easy thing to fix.
Much thanks.

**Comment by ewpatton** [comment]
@stezelMIT It's good that you have figured out a workaround. In the meantime, I want to make sure this gets on our radar in terms of something to merge and deploy.

**Review by jisqyv — APPROVED** [review]
LGTM

**Pull request merged**
