### PR TITLE
Add click event for the Image component

### PR DESCRIPTION
**Pull request by conorshipp**
This PR is a continuation of #1070. The original commits by @moliata have been squashed and rebased onto the latest `ucr` branch, with changes from me including the addition of a "Clickable" property and updates to the documentation.

### CODE REVIEW

**Comment by AppInventorWorkerBee** [comment]
Can one of the admins verify this patch?

**Comment by ewpatton** [comment]
@AppInventorWorkerBee ok to test

**Comment by conorshipp** [comment]
@ewpatton do you need me to resolve the conflicts?

**Comment by ewpatton** [comment]
@conorshipp Yes, if you can bring this up-to-date with ucr that'd be helpful.

**Comment by ewpatton** [comment]
Thanks @conorshipp for pushing this over the finish line and @moliata for the initial implementation.

**Pull request merged**
