### PR TITLE
Unified file provider source

### PR DESCRIPTION
**Pull request by ColinTree**

### CODE REVIEW

**Comment by ewpatton** [comment]
@ColinTree Would you mind updating the PR description with some explanation of why you made this change and what we should be testing with it?

**Comment by ColinTree** [comment]
The only thing that need to be confirm is the change in Camera. Theoretically it would work, but we should still be careful

**Comment by ewpatton** [comment]
@ColinTree Is this just an optimization of something that already works or does it fix an issue with the existing code?

**Comment by AppInventorWorkerBee** [comment]
Can one of the admins verify this patch?

**Comment by ewpatton** [comment]
@AppInventorWorkerBee ok to test

**Comment by AppInventorWorkerBee** [comment]
All tests passed. +1 Verified.

**Pull request merged**
