### PR TITLE
Fix crash due to ClassCastException in Slider

### LINKED ISSUE #1287: Slider on Android 5.0 breaks due to bad cast
We downcast the result of `getProgressDrawable` from `Drawable` to `LayerDrawable`. However, on Android 5.0 the returned result is a `StateListDrawable` (see stack trace below). This prevents compiled apps with non-Classic themes from working on Android 5.0 devices.

Stack trace:
```
E/AndroidRuntime( 3486): java.lang.RuntimeException: Unable to start activity ComponentInfo{appinventor.ai_ewpatton.SliderTest/appinventor.ai_ewpatton.SliderTest.Screen1}: java.lang.ClassCastException: android.graphics.drawable.StateListDrawable cannot be cast to android.graphics.drawable.LayerDrawable
E/AndroidRuntime( 3486): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2298)
E/AndroidRuntime( 3486): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
E/AndroidRuntime( 3486): 	at android.app.ActivityThread.access$800(ActivityThread.java:144)
E/AndroidRuntime( 3486): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
E/AndroidRuntime( 3486): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 3486): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime( 3486): 	at android.app.ActivityThread.main(ActivityThread.java:5221)
E/AndroidRuntime( 3486): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 3486): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime( 3486): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
E/AndroidRuntime( 3486): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
E/AndroidRuntime( 3486): Caused by: java.lang.ClassCastException: android.graphics.drawable.StateListDrawable cannot be cast to android.graphics.drawable.LayerDrawable
E/AndroidRuntime( 3486): 	at com.google.appinventor.components.runtime.Slider.<init>(Slider.java:99)
E/AndroidRuntime( 3486): 	at java.lang.reflect.Constructor.newInstance(Native Method)
E/AndroidRuntime( 3486): 	at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
E/AndroidRuntime( 3486): 	at gnu.expr.PrimProcedure.apply(PrimProcedure.java:272)
E/AndroidRuntime( 3486): 	at gnu.mapping.CallContext.runUntilDone(CallContext.java:234)
E/AndroidRuntime( 3486): 	at gnu.mapping.CallContext.runUntilValue(CallContext.java:298)
E/AndroidRuntime( 3486): 	at gnu.kawa.reflect.Invoke.applyN(Invoke.java:209)
E/AndroidRuntime( 3486): 	at gnu.mapping.ProcedureN.apply2(ProcedureN.java:39)
E/AndroidRuntime( 3486): 	at appinventor.ai_ewpatton.SliderTest.Screen1.$define(Screen1.yail:10182)
E/AndroidRuntime( 3486): 	at com.google.appinventor.components.runtime.Form.onCreateFinish(Form.java:338)
E/AndroidRuntime( 3486): 	at com.google.appinventor.components.runtime.Form.onCreate(Form.java:285)
E/AndroidRuntime( 3486): 	at android.app.Activity.performCreate(Activity.java:5937)
E/AndroidRuntime( 3486): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
E/AndroidRuntime( 3486): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2251)
E/AndroidRuntime( 3486): 	... 10 more
```

### PR DESCRIPTION
**Pull request by ewpatton**
In Slider we cast the progress drawable to` LayerDrawable`, regardless of whether or not it is actually a `LayerDrawable` or subclass. This causes problems in compiled apps on Android 5.0+ when the theme is not Classic, since a `StateListDrawable` may be returned instead. As a result, the app crashes.

This change makes the code to update the slider colors more robust to different drawables based on the current Android version. It also includes an additional hack for Android 5.0 since `setProgressBackgroundTintList` and `setProgressBackgroundTintMode` seem to have no effect (they work fine on 5.1 and later).

Tested in both Companion and compiled app on emulators running the following SDK levels:
* 8
* 16
* 21
* 27

Fixes #1287

### CODE REVIEW

**Comment by halatmit** [comment]
LGTM but I didn't test this on older devices.

**Comment by jisqyv** [comment]
@ewpatton This code is now on ai2-test

**Comment by ewpatton** [comment]
Thanks @jisqyv. I emailed the developer who reported the issue to see if it solves the problem observed on his device.

**Comment by jisqyv** [comment]
@ewpatton I'll merge this as soon as we hear back...

**Pull request merged**
