### PR TITLE
[GSoC] Adding Different Preview Options To The Designer

### PR DESCRIPTION
**Pull request by HimaniKaul**
This summer I have worked on improving the MockForm by adding three different preview options in the Designer. The preview options are Android Material (Android 5+), Android Holo (Android 3.0-4.4.2) and introducing the new iPhone/iPad (iOS 13) MockForm so that users can preview their apps and get to know how it will look on different platforms.

### CODE REVIEW

**Comment by AppInventorWorkerBee** [comment]
Can one of the admins verify this patch?

**Comment by ewpatton** [comment]
@HimaniKaul  this has conflicts now with #2331. I've done my best to resolve them for deploying this on our test server but it doesn't look quite right, especially for the iPhone version. Would you mind reconciling this with master when you have a chance?

**Comment by jisqyv** [comment]
@HimaniKaul @ewpatton Looks like an extraneous copy of the adb binary is included in this PR. Please flush (Himani: We can take care of this). This note is mostly so we don't forget!

**Comment by HimaniKaul** [comment]
@jisqyv @ewpatton Sure, I will still have a look on it.

**Comment by jisqyv** [comment]
@HimaniKaul I'm about to push to your branch. I have done some work bringing your work up-to-date to the current master.

**Comment by HimaniKaul** [comment]
@jisqyv Okay!

**Comment by jisqyv** [comment]
@HimaniKaul I backed out the changes you made to MockSwitch. This was a policy decision. Although your change made the Classic theme correct for API 7, after API 14 the switch appears like a switch (not a checkbox) on devices in Classic mode. Given that almost all of our users are now using devices at or beyond API 14, we figured this makes more sense.

I believe we are very close to merging this change

**Comment by HimaniKaul** [comment]
@jisqyv Okay.

**Review by jisqyv — APPROVED** [review]
LGTM

**Comment by jisqyv** [comment]
@HimaniKaul Merged!

**Comment by pratyaksh177** [comment]
hellow @HimaniKaul I am fresers and actually I have little knowledge about open source. I know java language . If you dont mind will you please guide me :) pratyakshraj17@gmail.com

**Pull request merged**
