### PR TITLE
Improved Chinese translation & Fixed some errors

### PR DESCRIPTION
**Pull request by Donlon**
Most of the works are translating some text mistranslated and retranslating some elder texts, which expressed not so native, or were incorrect in syntax, and could be hardly understood before, into Chinese. In the meantime, I sorted items in OdeMessages_zh_CN.properties into the order likes OdeMessages.java. So they, in the same structure and has identical annotation now, can be looked-up or modified handily. By the way, some errors were fixed.

### CODE REVIEW

**Comment by jisqyv** [comment]
@Donlon Your change updated 32 files. If you only updated the Chinese translation, can you please cleanup this pull request so that other files are not updated. Thanks.

**Comment by Donlon** [comment]
@jisqyv Actually I only aim at making the translation more perfect originally. But I find somewhere can be fixed (such as internationalizing some text and some...) when I do it. So I updated those items and combined them and the translation files into one pull request to upload. Should I split them into few requests?

**Comment by Donlon** [comment]
Oops I may have forgotten something... (The annotation below the header tells what this file's item is identical to.)

**Comment by ewpatton** [comment]
@cavedunissin Would you mind reviewing this change, especially the translations?

**Comment by cavedunissin** [comment]
@ewpatton , for these two files (/OdeMessages_zh_TW.properties and  _messages.js) should use my latest commit (id: 80da726 ,30814ea and 30814ea) 

sorry don't know how to insert commit id in reply.

**Comment by ewpatton** [comment]
Since the work @cavedunissin did in #1000, I think this PR is now obsolete. If that's not the case, please reopen it and we can discuss further.

**Pull request closed without merging**
