### PR TITLE
Upgrade build system (including Companion) to Java 11

### PR DESCRIPTION
**Pull request by ewpatton**

### CODE REVIEW

**Comment by ewpatton** [comment]
I also tried to keep changes to somewhat self-contained commits. This PR is submitted against ucr, but the first 2 commits could go on master instead if we need to deploy the appengine related changes before this is fully reviewed. A test server (without significant configuration) is available here: https://java11test-dot-ai2-ewpatton-temp.uc.r.appspot.com

TODOs:

- [ ] Test the companion app a range of devices make sure it still works
    - [x] macOS Emulator (Android Lollipop)
    - [ ] Old Windows emulator (Android S)
    - [ ] New Windows emulator (Android Eclair)
    - [ ] Chromebook
    - [ ] Google Pixel
    - [ ] Samsung

**Comment by champ-farswal** [comment]
i want to contribute but i dont able to understand the codebase as i know java only please help me some mentor to understand the code base.

**Comment by ewpatton** [comment]
@jisqyv I have updated the buildserver libraries so that `ant RunLocalBuildServer` runs on Java 11.

There is still the outstanding issue with compiled apps not running on earlier versions of Android due to multidex failures. I think I should have that fixed by Monday.

**Comment by ewpatton** [comment]
So the libraries I used in my last update included some dependencies that are compiled for Java 11 minimum. The Jenkins server is still targeting Java 8 which is why that build failed. I have downgraded to an earlier version of the libraries (but newer than the ones in master) that are Java 8 compatible but still work when running `ant RunLocalBuildServer` on Java 11.

**Comment by ewpatton** [comment]
@jisqyv I approve your changes.

**Review by jisqyv — APPROVED** [review]
LGTM

**Pull request merged**
