### PR TITLE
TimePicker format with respect to device's context, fixes #374

### LINKED ISSUE #374: Add 24-hour time option to TimePicker
It is a little annoying for us users outside the US that the TimePicker is using 12 hour format on an device that is configured for 24 hour format. Maybe the java-code 'behind' this functionality need a change to something like: "new TimePickerDialog(this, mOnTimeSetListener, time.hour, time.minute, DateFormat.is24HourFormat(this));"?

### PR DESCRIPTION
**Pull request by RudyChin**
TimePicker will show 24-hour format or 12-hour format based on device's context
Attached with [test.apk](https://www.dropbox.com/s/949tvvml8cr1h1d/test.apk?dl=0) which is the modified version TimePicker.

### CODE REVIEW

**Comment by halatmit** [comment]
Thank you!

LGTM

**Comment by jisqyv** [comment]
@RudyChin This pull request is a bit hosed. It includes a bunch of commits that appear to checking pieces of the MIT App Inventor website into the source tree. That cannot be right! I assume that your actual change is just the last commit. Please let me know, I can extract just that commit so you don't have to do git magic to straighten out this PR (unless you know the incantations :-) ).

**Comment by josmas** [comment]
I checked this pull request the other day and it was fine; @RudyChin but you seem to be working off your master branch, so when you updated and pushed back to your fork, all the new commits are added here.
Try and work on feature branches instead, it will be a lot easier to manage!

**Comment by jisqyv** [comment]
Indeed, the commits in question were added between the time it was originally given the LGTM and now. That's an interesting mis-feature of doing reviews on GitHub. The PR isn't immutable but can change after an approval is given.

**Comment by halatmit** [comment]
Ditto.  This looked ok when I looked at it the other day, too.


== Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.
MIT Media Lab, Second Class Faculty

**Comment by RudyChin** [comment]
@jisqyv @josmas Thank you for your help! I think I did not understand Git clearly enough.
I tried that git magic and I will create another branch to do what I tended to do after fixing this issue. Big thanks.

**Comment by halatmit** [comment]
Is this obsoleted by #449 ?

**Comment by jisqyv** [comment]
I don't believe so...

-Jeff

On Sat, Jul 11, 2015 at 3:07 PM, hal <notifications@github.com> wrote:

> Is this obsoleted by #449
> <https://github.com/mit-cml/appinventor-sources/pull/449> ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mit-cml/appinventor-sources/pull/379#issuecomment-120652877>
> .
>



-- 
_______________________________________________________________________
Jeffrey I. Schiller
Information Systems and Technology – MIT App Inventor
Massachusetts Institute of Technology
77 Massachusetts Avenue  Room E17-110A, 32-392
Cambridge, MA 02139-4307
617.910.0259 - Voice
jis@mit.edu
http://jis.qyv.name
http://appinventor.mit.edu
_______________________________________________________________________

**Comment by jisqyv** [comment]
The branch is in good shape now. LGTM. Moving to Gerrit for the UCR branch.

**Comment by jisqyv** [comment]
@RudyChin MERGED into the "ucr" branch for the next App Inventor Component Release

**Pull request closed without merging**
