### PR TITLE
Feature/chatbot vision (unfinished)

### PR DESCRIPTION
**Pull request by catherinepaopao**
Created ConverseWithImage block, currently shows up but doesn't do anything

### CODE REVIEW

**Comment by AppInventorWorkerBee** [comment]
Can one of the admins verify this patch?

**Comment by daki7711** [comment]
@jisqyv This is the draft PR for the vision chatbot, could you take a look and comment what Catherine should do next? Or could you adjust things in the proxy server according to her implementation?

**Comment by ewpatton** [comment]
@catherinepaopao Thanks for demoing this at the team meeting yesterday. A few things are needed before we can merge this. In particular, since you are changing a component you will need to bump the version number for the ChatBot in YaVersion.java and then add code paths to handle upgrading to that version in YoungAndroidFormUpgrader.java and versioning.js. Adding a new block is effectively a "no-op" in these upgrade paths but it is still necessary to add them.

**Comment by daki7711** [comment]
Btw, do we wan to finish the ios version in this branch? I assume it shouldn't be that much difficult to add?

**Comment by ewpatton** [comment]
Yes.

**Review by ewpatton — CHANGES_REQUESTED** [review]
@catherinepaopao This is pretty much done. The only thing left is to bump the ChatBot version number in YaVersion.java because we are changing its API and then add the upgrade paths in YoungAndroidFormUpgrader.java and versioning.js (which will both be no-ops for a new block).

**Comment by ewpatton** [comment]
@AppInventorWorkerBee ok to test

**Review by jisqyv — APPROVED** [review]
LGTM. It's been working on ai2-test for a while now.

**Pull request merged**
