### PR TITLE
Italian Translation

### PR DESCRIPTION
**Pull request by tiffanyle**

### CODE REVIEW

**Comment by jisqyv** [comment]
@tiffanyle The Code looks good to me. Do we know how good this translation is? Did multiple people review it on the Pootle server?

**Comment by tiffanyle** [comment]
It looks like 2-3 people were working on the translation based on the statistics, so it should be a fairly accurate one.

**Comment by jisqyv** [comment]
@tiffanyle OK. I'll give this one final look today and will likely merge it today (or tonight).

**Comment by jisqyv** [comment]
@tiffanyle LGTM, MERGED

**Pull request closed without merging**
