### PR TITLE
Storage docs (again)

### PR DESCRIPTION
**Pull request by ajcolter**
Updated it some more to match the wording of the Pizza Party tutorial a little more.

@afmckinney @jisqyv @halatmit

### CODE REVIEW

**Comment by jisqyv** [comment]
@ajcolter You based this change on a version of master prior to your last storage documentation change. So I get a merge conflict. Please merge master into this work and resolve the conflicts. Thanks.

**Comment by ajcolter** [comment]
I think I fixed it. Merged the Storage document changes.

**Comment by jisqyv** [comment]
@ajcolter LGTM. I'm going to squash it down and submit it through Gerrit.

**Comment by jisqyv** [comment]
@ajcolter MERGED.

**Pull request closed without merging**
