### PR TITLE
Fix focusing on collapsed warnings/errors

### LINKED ISSUE #1678: Investigate warning/error stepper with collapsed blocks
From a beta tester of nb176:

> Clicking on the right set of up or down arrows does not show blocks that have errors. Instead it clears the blocks screen. I have 33 errors in my app but I can't find them. Why can't we add a "Show Errors" button?

### PR DESCRIPTION
**Pull request by BeksOmega**
### Resolves

Closes #1678 

### Description

Makes it so that when you are cycling through warnings or errors collapsed blocks are temporarily uncollapsed so that you can view them.

### Testing
HighlightingWarnings

### CODE REVIEW

**Comment by BeksOmega** [comment]
Fixed and tested! Also went and added some inline doc I forgot.
ReCollapse

**Comment by ewpatton** [comment]
So one issue I noticed while testing is that we can end up saving the workspace while the block is in an uncollapsed state. Unfortunately, I don't think there's a way for us to fix that without making changes to core. In this imagined change, we could add a `temporarilyExpanded` or similar flag that is used along with an optional arg to `setCollapsed` that records whether it is temporary. Further, temporary changes should be marked isTransient, which is how we determine whether to schedule a save. I'm going to merge this as is as people can mitigate by simply doing something else (triggering the collapse with your latest update0 or recollapsing the block if there are issues.

**Comment by BeksOmega** [comment]
> In this imagined change, we could add a `temporarilyExpanded` or similar flag that is used along with an optional arg to `setCollapsed` that records whether it is temporary. Further, temporary changes should be marked isTransient, which is how we determine whether to schedule a save.

So that I'm understanding the problem correctly: The reason this would be hard to implement is not because of `setCollapsed` (which we already override), but because isTransient would have to be applied to a blockly-core event (vis change)?

**Comment by ewpatton** [comment]
@BeksOmega It's a bit deeper than that because of the way App Inventor's auto-save mechanism works. When a change is made, a timer is set 5 seconds in the future to save the state to the server. This allows us to group together events close together into a single save operation. Therefore, I can make a "real" change to the project, then click the warning/error stepper, which expands the block, and then when the save timer goes off the expanded state of the block will be persisted. We need a way to specify for a given block that it is only temporarily expanded and that its expanded state shouldn't be persisted when the XML is generated. If the user explicitly expands the block, the normal behavior should occur (it triggers a save and the fact that it is expanded is stored).

**Comment by BeksOmega** [comment]
> Therefore, I can make a "real" change to the project, then click the warning/error stepper, which expands the block, and then when the save timer goes off the expanded state of the block will be persisted. We need a way to specify for a given block that it is only temporarily expanded and that its expanded state shouldn't be persisted when the XML is generated.

@ewpatton Ok! I think I getcha. We cannot keep from adding the collapsed tag to the XML b/c that would require editing xml.js (which would suck).

I was thinking, we /could/ prevent it by having isCollapsed() return true if it is only temporarily expanded... But that would probably cause unknown side affects we don't want.

Even if we can't fix it, would you like me to create a tracking issue for this? That way if anyone happens upon this in the future we can be like "yehhh we know :/ see le tracking issue". Or do you think the discussion here is documentation enough?

**Pull request merged**
