### PR TITLE
Add fixes to Blockly to address mutator performance

### LINKED ISSUE #959: ODE performance issues on projects with many mutators
@kkashi01 provided an example app from a user where opening a mutator bubble decreases the responsiveness of user interface events in the editor. Initial investigation suggests that there are many events being fired by a combination of Ode and Blockly that keep the browser's JS thread busy and prevent user interaction. We need to figure out why there are so many events being fired and how to reduce them to the minimal subset required to provide editor functionality.

### PR DESCRIPTION
**Pull request by ewpatton**
Fixes #959 

Change-Id: I07a51181269adfd79b8db11a40cec66dc43a4ed9

### CODE REVIEW

**Comment by ewpatton** [comment]
@kkashi01 Can you test this and let me know whether it addresses your performance issues? You will need to run `git submodule update` to get the changes I made to Blockly core.

**Comment by ewpatton** [comment]
Relevant [forum post](https://groups.google.com/d/msg/app-inventor-dev/PmoY-J9qFSc/bytZBPmdAQAJ) for testing.

**Comment by kkashi01** [comment]
@Evan that's a good point. However I thought there is a timestamp that is
used which should overcome the caching issue.

**Comment by jisqyv** [comment]
Note: I'll push "mitmaster" to our blockly repo when I merge this

**Pull request merged**
