### PR TITLE
Support for FIRST Tech Challenge

### PR DESCRIPTION
**Pull request by lizlooney**
This is the first commit related to support for FIRST Tech Challenge (FTC).

Added strings for FIRST Tech Challenge components, properties, parameters, events, and methods, to OdeMessages.java.
Added map entries for FIRST Tech Challenge parameters to TranslationComponentParams.java.
Added FIRST Tech Challenge components to TranslationDesignerPallete.java.

@halatmit @jisqyv @jsheldonmit

### CODE REVIEW

**Comment by halatmit** [comment]
LGTM
@jisqyv @afmckinney

**Comment by josmas** [comment]
@halatmit @lizlooney can we have some context about this? I vaguely recall FIRST being mentioned at a meeting a good while ago, but it sounds like it's actually going to happen now.

**Comment by lizlooney** [comment]
José, I just sent you the design doc.

-Liz

**Comment by halatmit** [comment]
We're still working on it.

Josh and I are trying to make a plan with FIRST.

Liz has been implementing the appropriate robot package.



== Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.
MIT Media Lab, Second Class Faculty

**Comment by jisqyv** [comment]
@lizlooney @halatmit @josmas @afmckinney I'm going to create a new branch "ftc" for the FIRST code. I'm going to make this the first commit on that branch and merge in the current master (which requires cleaning up the TranslationFoo... stuff).

Sound OK?

**Comment by halatmit** [comment]
+1



== Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.
MIT Media Lab, Second Class Faculty

**Comment by josmas** [comment]
thanks @lizlooney, it looks really good! A branch makes sense if things have not been finalised with FIRST.

**Comment by lizlooney** [comment]
Thanks!

Do I have to do anything different if it's in a branch? So far, I just
follow the steps on the Developing MIT App Inventor using git and github.com
<https://docs.google.com/document/u/0/d/1sAw0QObTxTWqRX7GQRCa2z9TIV2r5AKT9UKMFF1acZI/pub>
page.

-Liz

**Comment by josmas** [comment]
Hi @lizlooney we mention working on feature branches on that document, but we don't explain much how. Just merge in the master branch into your feature branch as often as possible so you are always up to date. I like pulling from upstream master with --rebase from my feature branch `git pull --rebase upstream master` so that your own commits bubble up to the top and you keep a *clean* branch

**Comment by lizlooney** [comment]
New components: FtcAccelerationSensor, FtcCompassSensor, FtcDcMotor, FtcGamepad, FtcGyroSensor, FtcHardwareDevice, FtcIrSeekerSensor, FtcLegacyModule, FtcLightSensor, FtcOpMode, FtcRobotController, FtcServo, FtcUltrasonicSensor, and FtcVoltageSensor.

New interfaces to support components that want to add items to the options menu: OnCreateOptionsMenuListener and OnOptionsItemSelectedListener.

New libraries: FtcCommon-release.aar and RobotCore-release.aar.

Added code to Compiler.java to handle FTC features, activities, services, and resources.

The FIRST® Tech Challenge category on the palette is not visible to the user yet because YoungAndroidPalettePanel.showCategory returns false for ComponentCategory.FIRSTTECHCHALLENGE.

Please see the design document for details:
https://docs.google.com/document/d/1SAU8usM4dIi2McizMv7mDb96eNKoEQ8kbgRhZzzpE_k/edit?usp=sharing

**Comment by lizlooney** [comment]
@afmckinney @jisqyv

**Comment by lizlooney** [comment]
The design doc is here: https://docs.google.com/document/d/1SAU8usM4dIi2McizMv7mDb96eNKoEQ8kbgRhZzzpE_k/edit?usp=sharing

**Comment by lizlooney** [comment]
Does MIT have a robot yet?

**Comment by halatmit** [comment]
Yes, we have a robot.  Haven't played with it yet .... Andrew's on vacation
and Jeff and I are dealing with the API4 release.   I'm also testing the
extension components (cdk) and preparing to put up a test instance.




== Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.
MIT Media Lab, Second Class Faculty

**Comment by lizlooney** [comment]
These changes should go into a new branch on mit-cml.
@jisqyv can you create a new branch for the FTC version of App Inventor?

**Comment by lizlooney** [comment]
@halatmit @jisqyv 
I think the next step is for Jeff to create a new branch for FTC on mit-cml/appinventor-sources. Then, I can create a new pull request (or modify this one so it's for the new branch, if that's possible).

**Comment by jisqyv** [comment]
@lizlooney I have created the "ftc" branch which is current at the same commit as master.

**Comment by lizlooney** [comment]
Thanks Jeff! I'm at my daughter's swimming lesson, but when I get to a
computer, I'll do the pull request.

-Liz

**Comment by jisqyv** [comment]
No rush, take your time.

-Jeff

On Sat, Oct 17, 2015 at 7:05 PM, Liz Looney <notifications@github.com>
wrote:

> Thanks Jeff! I'm at my daughter's swimming lesson, but when I get to a
> computer, I'll do the pull request.
>
> -Liz
> On Oct 17, 2015 4:03 PM, "Jeffrey Schiller" <notifications@github.com>
> wrote:
>
> > @lizlooney <https://github.com/lizlooney> I have created the "ftc"
> branch
> > which is current at the same commit as master.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/mit-cml/appinventor-sources/pull/362#issuecomment-148959384
> >
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mit-cml/appinventor-sources/pull/362#issuecomment-148959450>
> .
>



-- 
_______________________________________________________________________
Jeffrey I. Schiller
Information Systems and Technology – MIT App Inventor
Massachusetts Institute of Technology
77 Massachusetts Avenue  Room 32-386
Cambridge, MA 02139-4307
617.910.0259 - Voice
jis@mit.edu
http://jis.qyv.name
http://appinventor.mit.edu
_______________________________________________________________________

**Comment by lizlooney** [comment]
This pull request is obsolete.
See pull request #585.

**Pull request closed without merging**
