### PR TITLE
Bugfix655

### PR DESCRIPTION
**Pull request by wadleo**
Here is a quick fix to the issue reported at https://github.com/mit-cml/appinventor-sources/issues/655 and feedback from tests on this fix  will be appreciated, thanks.

### CODE REVIEW

**Comment by jisqyv** [comment]
@wadleo This change does not appear to fix the problem (using Chrome 47 under Linux). Below is a screenshot of the sharing component document.

-Jeff

snip

**Comment by wadleo** [comment]
Thanks @jisqyv working on that

**Comment by wadleo** [comment]
Hi @jisqyv, investigated this issue on chrome and firefox on linux, and saw the error on chrome as you stated. This can be corrected simply by setting the 'overflow' property in the 'ode-ComponentHelpPopup' div to auto. This is a quick fix but maybe there is a more appropriate one. Also am unsure as to if i should create a PR for this since you already assigned it to yourself.

**Comment by wadleo** [comment]
@jisqyv 
I corrected the issue here is the link to the pull request, https://github.com/mit-cml/appinventor-sources/pull/727. Thanks

**Pull request closed without merging**
