### PR TITLE
Space is not replaced with underscore when importing project from gallery

### PR DESCRIPTION
**Pull request by devarsh-mavani-19**
Space is not replaced with underscore when importing project from gallery. see issue #2648

### CODE REVIEW

**Comment by AppInventorWorkerBee** [comment]
Can one of the admins verify this patch?

**Comment by devarsh-mavani-19** [comment]
@ewpatton can you please check this PR? Thanks

**Comment by jisqyv** [comment]
@AppInventorWorkerBee ok to test

**Review by jisqyv — APPROVED** [review]
LGTM

**Pull request merged**
