### PR TITLE
Upadted the Documentation for the Flung part of Canvas and ImageSprite

### LINKED ISSUE #1340: Heading behavior and documentation mismatch
[From the forum](https://groups.google.com/d/msg/mitappinventortest/cq7TaW-BGbw/PesPuCJlEAAJ): The documentation for `Flung` for Canvas and Sprites claims that `heading` will be in the range [0, 360). However, values reported by a test app show that values are in the range [-180,180).

So there are three things we should consider:

1. Update the documentation so that the range is [180, 180) and be done with it.
2. Fix the math so that it normalizes the value to [0, 360).
3. Slightly more challenging: I always think of heading as relative to north (+Y on 2D screen). Right now the 0 value is +X (east). We could rotate the heading value so that 0 is +Y and 90 is +X.

In the case of 2 or 3, we should provide an option on the Canvas to retain the Legacy behavior with upgrader for projects so that existing projects relying on the old semantics do not break.

### PR DESCRIPTION
**Pull request by dhruvpatidar359**
closes #1340

### CODE REVIEW

**Comment by AppInventorWorkerBee** [comment]
Can one of the admins verify this patch?

**Review by ewpatton — CHANGES_REQUESTED** [review]
You also need to run ant docs and check in the resulting changes to the markdown and HTML files.

**Comment by dhruvpatidar359** [comment]
> You also need to run ant docs and check in the resulting changes to the markdown and HTML files.

done

**Comment by ewpatton** [comment]
@AppInventorWorkerBee ok to test

**Review by ewpatton — APPROVED** [review]
LGTM

**Pull request merged**
