### PR TITLE
Fix several typos in MockComponent.java

### PR DESCRIPTION
**Pull request by HollowMan6**
YoungAndroidProjectServce -> YoungAndroidProjectService
overriden -> overridden
invididual -> individual

### CODE REVIEW

**Comment by AppInventorWorkerBee** [comment]
Can one of the admins verify this patch?

**Comment by gourish3** [comment]
Can you assign me this issue?

**Comment by ewpatton** [comment]
@AppInventorWorkerBee ok to test

**Review by jisqyv — APPROVED** [review]
LGTM

**Pull request merged**
