### PR TITLE
Fixed Form JUnit test fails on Windows

### LINKED ISSUE #2460: Form unit test fails on Windows machine
**Describe the bug**
JUnit test case for **Form** fails on Windows machine because of line separator. 

**Affects**

- [ ] Designer
- [ ] Blocks editor
- [ ] Companion
- [ ] Compiled apps
- [ ] Buildserver
- [ ] Debugging
- [x] Other... (please describe)

**Steps to solve**
Line separator in Linux = **`\n`** 
Line separator in Windows = **`\r\n`**

due to this Form test fails into Windows machine to overcome this problem just replace **`\n`**  with **`System.lineSeparator()`** so that it works for all machines.

Thank You
Preet Vadaliya

### PR DESCRIPTION
**Pull request by preetvadaliya**
Fixes #2460

### CODE REVIEW

**Comment by AppInventorWorkerBee** [comment]
Can one of the admins verify this patch?

**Comment by ewpatton** [comment]
Technically the issue isn't in the test, it is in the fact that by default git replaces the unix line terminator with the windows one. On an Android device this wouldn't be a problem because Android runs on Linux so the terminator should always be "\n".

**Comment by preetvadaliya** [comment]
@ewpatton thanks for your commitment 

but due to "\n" test report shows that the tests are failed.

**Comment by ewpatton** [comment]
@preetvadaliya Given that #2462 solved the underlying issue I'm going to close this PR.

**Pull request closed without merging**
