### PR TITLE
Any Component Improvements

### LINKED ISSUE #1223: Request generic component event feature
Well, I have finished a working version. [https://dev.wxbit.com](https://dev.wxbit.com)
The version is asking for test. Maybe I should submit later?
Also, I have added dynamic creation capability to component container, all the visible ui component can be created in blocky code.

canvas

### PR DESCRIPTION
**Pull request by ewpatton**
### Any component events

The first change in this PR provides improvements to the any component blocks language feature by allowing for any component event handlers to complement any method/any property getter-setters. This implementation is based heavily on the one provided by @wxbit in PR #1263. The differences from that PR are:

1. Generics are always run regardless of whether an event block for the component exists and was evaluated. This is similar semantics to how Canvas and Map handle "generic" events on their children.
2. We add a boolean `wasHandled` parameter in the any event blocks to indicate whether a specific event handler was already evaluated.

Resolves #1223 

### Actions to swap between specific component/any component blocks

The second improvement is menu options in the blocks editor to transform from specific method/property blocks to generic versions, and to transform specific event handlers to generic event handlers.  The latter feature will replace all occurrences of the component named in the specific event handler to a version that accepts the generic event handler's component parameter.

__NB__: Typically, this change could just go against master as it is just changing the behavior of the blocks editor, but since it relies on generic events it is included as part of this PR.

### CODE REVIEW

**Comment by ewpatton** [comment]
Please use the Rebase option when merging this PR so that the authorship credits are maintained.

**Comment by ewpatton** [comment]
Test server: http://generics.ai2-ewpatton-temp.appspot.com

**Comment by SusanRatiLane** [comment]
Could you give a use case for wasHandled?

**Comment by SusanRatiLane** [comment]
If one switches a specific event to generic with the companion running, the specific event continues to run. I believe this is a case of a known issue refreshing the Companion but thought I'd mention it.

**Comment by ewpatton** [comment]
@SusanRatiLane See the discussion on the power users thread. I included an example of a calculator app where the Clear button is handled and therefore the generic event doesn't need to handle it. And yes, the other issue you noted is a separate problem (also happens if you disable the specific event handler, and in production today).

**Comment by SusanRatiLane** [comment]
> @SusanRatiLane See the discussion on the power users thread. I included an example of a calculator app where the Clear button is handled and therefore the generic event doesn't need to handle it. And yes, the other issue you noted is a separate problem (also happens if you disable the specific event handler, and in production today).

Oh, I saw that example and saved, but I haven't looked at it. Thanks.

**Comment by SusanRatiLane** [comment]
Am holding off on merge until Power User discussion is concluded.

**Comment by ewpatton** [comment]
@SusanRatiLane @jisqyv This is the version that is running on the test server, with the parameter name change and with the semantic change that allows for component blocks and property getters to be used in global var declarations.

**Comment by AppInventorWorkerBee** [comment]
All tests passed. +1 Verified.

**Comment by ewpatton** [comment]
@SusanRatiLane @jisqyv This has been rebased onto the latest ucr and is ready for another review.

**Pull request merged**
