### PR TITLE
Upgrade to Android 5.1.1 build tool 23.0.2

### PR DESCRIPTION
**Pull request by josmas**
This is an upgrade to 5.1.1, needed mainly to work with BLE (needed to upgrade to 4.3, so went up to 5).

There are 3 commits because I first upgraded the mac tools, then the windows tools, and finally the linux tools (in three separate machines); squashing should be easy (no conflicts).

I have tried upgrading to 6.0, but a number of things break, mostly the removal of Apache HTTP client, and Notification builders ([changes in 6.0](http://developer.android.com/about/versions/marshmallow/android-6.0-changes.html)).

Could you please review? @jisqyv @halatmit

### CODE REVIEW

**Comment by jisqyv** [comment]
@josmas @halatmit I'll look at this over the weekend

**Comment by josmas** [comment]
Thanks, @jisqyv!

**Comment by afmckinney** [comment]
I am looking at this too.

**Comment by jisqyv** [comment]
Can you checkout #725?

-Jeff

On Sat, Mar 19, 2016 at 4:06 PM, Andrew F. McKinney <
notifications@github.com> wrote:

> I am looking at this too.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/mit-cml/appinventor-sources/pull/734#issuecomment-198777862>
>



-- 
_______________________________________________________________________
Jeffrey I. Schiller
Information Systems and Technology – MIT App Inventor
Massachusetts Institute of Technology
77 Massachusetts Avenue  Room 32-386
Cambridge, MA 02139-4307
617.910.0259 - Voice
jis@mit.edu
http://jis.qyv.name
http://appinventor.mit.edu
_______________________________________________________________________

**Comment by jisqyv** [comment]
@josmas LGTM -- Note: This will be merged into the "ucr" branch because it changes the Companion and buildservers. I will also remove the 4.2.2 android.jar file when I merge the commits together. I have done my testing with this jar removed.

**Comment by jisqyv** [comment]
@josmas MERGED onto ucr.

**Comment by josmas** [comment]
Thanks for the review @jisqyv 
4.2.2 is not referenced in any of the xml files, so removing it should be trivial.

**Pull request closed without merging**
