### PR TITLE
Deprecate the Twitter component

### PR DESCRIPTION
**Pull request by gordonlu310**
This PR deprecates the Twitter component, which as of my knowledge, no longer works because of the Twitter4J library. ([issue #1293](https://github.com/mit-cml/appinventor-sources/issues/1293))

This PR includes:

- **Removing the Twitter component in the Palette** by changing the category to Internal.
- **Removing relevant documentation of the Twitter component** in the Social page.
- **Adding a warning dialog of the deprecation** every time when the browser page is refreshed and the project is loaded.

Copyright dates are updated where appropriate.

### CODE REVIEW

**Comment by AppInventorWorkerBee** [comment]
Can one of the admins verify this patch?

**Comment by patryk84a** [comment]
Now, in 2024, isn't there some alternative API that will fix this component?

**Comment by gordonlu310** [comment]
Yes, but they function differently after the new v2 update, for example API key and bearer token instead of consumer key/secret. Also the new v2 API is relatively unstable from what I read.

https://mashable.com/article/twitter-api-elon-musk-developer-issues-apps

**Comment by ewpatton** [comment]
@gordonlu310 I think this looks good. Can you resolve the conflicts so we can merge it?

**Comment by ewpatton** [comment]
@AppInventorWorkerBee ok to test

**Review by ewpatton — APPROVED** [review]

**Pull request merged**
