### PR TITLE
Handle non-printable ASCII characters in Blockly XML

### LINKED ISSUE #2364: The blocks area did not load properly / Empty block area
**Describe the bug**

When i load my project, there appears an error message: "The block area did not load properly. Changes to the blocks for screen ... will not be saved." (refer to the picture at the bottom. I've censored the code, i don't know if it contains sensitive information). I don't know, what i've did wrong. Yesterday, i saved my project and today, the errormessage appears and the block-view is empty. The backup from yesterday (aia-export to computer) leads to the same issue. How i can get back my code?

Ive remembered: I've added a string-block with some unprintable characters from ASCII, maybe this led to this issue?

**Affects**

- [ ] Designer
- [X] Blocks editor
- [ ] Companion
- [ ] Compiled apps
- [ ] Buildserver
- [ ] Debugging
- [ ] Other... (please describe)

> ai2 bug

--
edit: This Issue occurs, among other, when a backspace appears in a string-block. But, the question remain: 
 - How to get back the code in case of use of an illegal character?

### PR DESCRIPTION
**Pull request by ewpatton**
Fixes #2364 

Change-Id: I3db24a8677fc0c810c0d60d2ce129f51e01d14be

### CODE REVIEW

**Comment by ewpatton** [comment]
Tested on Chrome and Firefox on macOS so far.

**Comment by ewpatton** [comment]
@BeksOmega I'm curious what your thoughts are on something like this. We see that people can use non-printable characters in their blocks and Blockly serializes the content without any attempt to clean it up. This particular fixes the XML just before it's parsed but I expect we probably want to have Blockly serialize the content correctly. Given you've worked with more recent Blockly sources, do you have suggestions?

**Comment by BeksOmega** [comment]
@ewpatton I think this solution works totally fine for the version of Blockly you're using! You could also add it to the [fieldToDom](https://github.com/mit-cml/blockly/blob/99604ec642a36d202e04533076ddf80f6eb009dc/core/xml.js#L108) function since the values should only be coming from fields (or so it seems).

In the more recent versions, serialization of field values has been moved into the fields themselves (eg [here](https://github.com/google/blockly/blob/edd475f37b02888819b87ddfca1d6eeebe68898a/core/field.js#L402)), so I would probably try to fix it there if I was working in the latest version of Blockly.

One thing I noticed is that is seems you've tried to fix this in core before: https://github.com/google/blockly/pull/1628 But it looks like the core team wasn't sure how they wanted to fix it: https://github.com/google/blockly/pull/1628#discussion_r168625147 As such I've put up a [new issue](https://github.com/google/blockly/issues/4590) for fixing this in core, so we can get it figured out.

Hopefully that answers your question! If I missed the point of what you were asking feel free to ping me.

**Comment by ewpatton** [comment]
It also affects comments, such as when someone reads a string of bytes from the Serial component and the Do It result is in the comment.

**Comment by BeksOmega** [comment]
> It also affects comments, such as when someone reads a string of bytes from the Serial component and the Do It result is in the comment.

Coolio! I editted the core issue to address that =)

**Review by daki7711 — COMMENTED** [review]
Does anyone know why u0009 is not included in line 266? Other than that LGTM

**Comment by ewpatton** [comment]
ASCII 9 is the TAB character, which is allowable in XML.

**Comment by daki7711** [comment]
I see that makes sense

**Review by daki7711 — APPROVED** [review]

**Comment by daki7711** [comment]
Is this ready to merge?

**Pull request merged**
