### PR TITLE
Initialize selection and selectionIndex for ListView and ListPicker

### PR DESCRIPTION
**Pull request by halatmit**
Initialize these to the empty string and zero.

### CODE REVIEW

**Comment by halatmit** [comment]
This requires a companion change.

**Comment by halatmit** [comment]
issue #634

**Comment by afmckinney** [comment]
Tested LGTM (Move to gerrit)

**Comment by jisqyv** [comment]
On Gerrit for ucr branch

**Comment by jisqyv** [comment]
@halatmit @afmckinney MERGED into ucr

**Pull request closed without merging**
