### PR TITLE
Add WebViewStringChange Event

### LINKED ISSUE #1036: Add event for WebViewString changes in WebViewer
If the JavaScript in a WebViewer changes the WebViewString property, there is no event in the blocks language to handle this. Instead, one needs to add a Clock or other mechanism to periodically poll the WebViewString. Adding an event so that the change can be handled immediately would eliminate the need to poll the value.

### PR DESCRIPTION
**Pull request by ChitiSims**
Closes #1036

### CODE REVIEW

**Comment by ColinTree** [comment]
is the value read-only in javascript? If it is not, listener may need to be set for changes from javascript.

**Comment by ewpatton** [comment]
@ColinTree The `setWebViewString` method is callable from JavaScript. You should be able to test this by loading an HTML page with a button that calls `window.AppInventor.setWebViewString()` with some string, which will be made available via the `WebViewString` property.

**Comment by ColinTree** [comment]
@ewpatton Okay i will try that, i thought that it was just a field but not a Object.

**Comment by ChitiSims** [comment]
Could I come to the office tomorrow at 2?
________________________________

**Comment by jisqyv** [comment]
Merged via Gerrit

**Pull request closed without merging**
