### PR TITLE
Add VR paper writeup

### PR DESCRIPTION
**Pull request by halatmit**

### CODE REVIEW

**Comment by halatmit** [comment]
@afmckinney @jisqyv 
please merge this , so we can release it soon

**Comment by jisqyv** [comment]
@halatmit @afmckinney I'm reviewing this now (which should be trivial). Do you have an issue with me putting out a minor (non-component) release after this is merged to get it out there in front of people?

-Jeff

**Comment by jisqyv** [comment]
@halatmit I found a problem. You named the page vr.html but referenced it as VR.html in the index.html. I'm just going to fix it and send the result to Gerrit. So no action needed on your part.

**Comment by halatmit** [comment]
Thanks for catching that.

Please go ahead and do the minor release

== Hal

Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.

**Comment by jisqyv** [comment]
@halatmit All set (LGTM). Sending to Gerrit

**Comment by jisqyv** [comment]
@halatmit MERGED

**Pull request closed without merging**
