### PR TITLE
Rightclick

### PR DESCRIPTION
**Pull request by ram8647**
Adds a context menu to the backpack that is brought up by right-clicking the backpack.  The context menu has a single item "Backpack documentation" that when selected brings up an alert window with a short description of the Backpack and a link to its online documentation. 

@jisqyv @halatmit

### CODE REVIEW

**Comment by halatmit** [comment]
@jisqyv @ram8647 
Jeff, When you modify this, see if there's a way to keep the change out of core.

**Comment by ram8647** [comment]
In this case, there's only 1 line added to core in blockly.js in the
onMouseDown_ function.   I think this is unavoidable because the core is
the only place where mouse clicks are handled.    It seems to me that
changes like this to the core could be avoided if it were possible to
override onMouseDown_ and similar functions outside of the core?

However, I think there's quite a bit of context-menu code in blockly.js
that could be moved outside the core.  I'm thinking of the
Blockly.showContextMenu_() function.    Was that originally originally a
Blockly function or was it added for App Inventor?

-- ralph

**Comment by halatmit** [comment]
I don't know specifically about showContextMenu.    But the idea is to
start structuring our changes so that it will be easier to update App
Inventor to new blockly releases.



== Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.
MIT Media Lab, Second Class Faculty

**Comment by ram8647** [comment]
What would be helpful is if Blockly core contained functions like
showContextMenu that could be overridden outside the core.   As it stands
now, even we moved all the showContextMenu() code out of the core, it would
still have to be called from the core.

-- ralph

**Comment by halatmit** [comment]
We need to talk more with Neil about ideas like this.



== Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.
MIT Media Lab, Second Class Faculty

**Comment by afmckinney** [comment]
This is refactored in Neils latest Blockly code. It is on my list of things I'm working on to get Blockly in sync with ours.

**Comment by jisqyv** [comment]
@afmckinney Note: I am working on converting Ralph's Alerts into more friendly dialogs

**Comment by jisqyv** [comment]
#580 Now includes this code. Closing this PR

**Pull request closed without merging**
