### PR TITLE
Fix MakePhoneCall in Android 11+

### LINKED ISSUE #2704: Update phone call to work on latest Android OS
**Describe the bug**

the make phone call method does nothing.

One possible approach is to use activity starter?
Is there anything we can do for iOS

### PR DESCRIPTION
**Pull request by jisqyv**
Add the UsesQueries annotation to declare that we make phone calls.

Fixes #2704

Change-Id: I62e59890fb550600991341abf7b4ae9d4f7115cf

### CODE REVIEW

**Comment by jisqyv** [comment]
I've tested this with the emulator (Android 11). Test Application built before this change causes nothing to happen when you attempt a phone call. With this change, the phone dialer is called up (but of course, it is an emulator, so it doesn't actually make phone calls). Someone with an Android 11+ phone should also test.

To ease testing, you can download both the test aia file and a test apk file (compiled with this change) Here:

   https://files.appinventor.mit.edu/share/fdyyci0U

-Jeff

**Review by daki7711 — APPROVED** [review]
LGTM

**Comment by halatmit** [comment]
I tried TestPhoneCaller.apk with my pixel 6 running Android 12 and
it successfully called the SnowLine.

Did not try the aia file.



==Hal

**Comment by jisqyv** [comment]
> I tried TestPhoneCaller.apk with my pixel 6 running Android 12 and it successfully called the SnowLine. Did not try the aia file. ==Hal

Thanks, Hal. That is what I needed to know!

-Jeff

**Pull request merged**
