### PR TITLE
Added DataFile component description in documentation

### PR DESCRIPTION
**Pull request by gordonlu310**
Added a component description for the DataFile component in the Storage documentation. It used to be "Component for DataFile".

### CODE REVIEW

**Comment by AppInventorWorkerBee** [comment]
Can one of the admins verify this patch?

**Comment by ewpatton** [comment]
@gordonlu310 Note that the description comes from the Javadoc on the component class. You probably want to add your description there otherwise it will get overwritten when we rebuild the documentation from sources.

**Comment by gordonlu310** [comment]
@ewpatton The description for DataFile is already available in DataFile.java. I simply copied it over. Is there anything else I need to change? Thanks.

**Comment by ewpatton** [comment]
@gordonlu310 I think the issue may be that the Javadoc for a component is prioritized over the content of the annotation. If you update the Javadoc with the content it should be fine. Otherwise, when we build a release build the changes you've made in docs/ will be overwritten by the content of the Javadoc.

**Comment by gordonlu310** [comment]
I think this is what I should do. Let me know if I'm wrong. Thanks!

**Comment by ewpatton** [comment]
@AppInventorWorkerBee ok to test

**Review by ewpatton — APPROVED** [review]

**Pull request merged**
