### PR TITLE
Fix canvas TextAlignment

### PR DESCRIPTION
**Pull request by halatmit**

### CODE REVIEW

**Comment by jisqyv** [comment]
So it looks like you are changing the default alignment from "NORMAL" to CENTER. Shouldn't you update the version of the component and have the YoungAndroidFormUpgrader set the alignment of Canvases in existing projects back to NORMAL?

-Jeff

**Comment by halatmit** [comment]
@fturbak 
@afmckinney 
I'll wait on this for the upgrader to be merged.

**Comment by halatmit** [comment]
@jisqyv 

I'm planning on doing what I think you are suggesting.  Here's the comment I'm planning to put YoungAndroidFormUpgrader.  Is this what you meant?

     // Set the TextAlignment property to ALIGNMENT_NORMAL.  This was the
      // default on old projects.  The new default is ALIGNMENT_CENTER.  In
      // this way, old projects that used the default will not be messed up.
      // Old projects that explicitly set alignment to ALIGNMENT_CENTER will get messed up (sadly).

**Comment by halatmit** [comment]
This has been superceded by PR 231.  I'm closing it.

**Pull request closed without merging**
