### PR TITLE
Added ActivityCanceled event to ActivityStarter component.

### PR DESCRIPTION
**Pull request by lizlooney**
Added ActivityCanceled event to ActivityStarter component.

This solves the problem reported on the MIT App Inventor Forum: https://groups.google.com/forum/#!topic/mitappinventortest/qPupD_e7xBg

@halatmit @jisqyv

### CODE REVIEW

**Comment by halatmit** [comment]
Thank you!!!!



== Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.
MIT Media Lab, Second Class Faculty

**Comment by halatmit** [comment]
Thanks.   
This also needs the language and component versioning, since an event was added.
See the current version of your old comment in YaVersion.java at line 385ff.
Don't forget the blockly side in versioning.js

This also needs the event  @description added to 
appinventor/docs/reference/components/connectivity.html

**Comment by lizlooney** [comment]
Thanks for catching that! PTAL (please take a look).

**Comment by halatmit** [comment]
LGTM
Thanks.

**Comment by jisqyv** [comment]
MERGED into the "ucr" branch (Upcoming Component Release).

**Pull request closed without merging**
