### PR TITLE
Update dependencies in node_modules in preparation for Blockly update

### PR DESCRIPTION
**Pull request by ewpatton**
Change-Id: Ide8a0a2aef89cb6a8bd59572f73002026cd5cb7f

This PR separates out the node_modules changes that are required for the Blockly update. After this is merged, the changes will need to be rebased out of #3275. So long as this passes CI/CD it should be good to go since the node_modules is only used for the tests.

### CODE REVIEW

**Comment by josmas** [comment]
Hey @ewpatton, was it a conscious choice to push node_modules to the repo?

This PR looks very scary, but there are also some more practical issues like using different versions of node, or native dependencies that will fail on different platforms when checked out, and this can show up at deployment time.

Would it be possible to remove it all and depend on the lock file? unless there is something very specific that I am missing.
I guess it would mean running `npm i` at some stage, which I guess it is not needed now.

**Comment by ewpatton** [comment]
Yes this is intentional. We vendor all of the dependencies to ensure we can always build App Inventor and we do not believe npm to be trustworthy enough to serve that role. Sent from my iPhoneOn Dec 5, 2024, at 16:14, Jos ***@***.***> wrote:﻿
Hey @ewpatton, was it a conscious choice to push node_modules to the repo?
This PR looks very scary, but there are also some more practical issues like using different versions of node, or native dependencies that will fail on different platforms when checked out, and this can show up at deployment time.
Would it be possible to remove it all and depend on the lock file? unless there is something very specific that I am missing.
I guess it would mean running npm i at some stage, which I guess it is not needed now.

**Review by mark-friedman — APPROVED** [review]

**Comment by ewpatton** [comment]
@josmas I should also point out that the node stuff is just used for running tests. It's not in any way deployed to production. Maybe in the future if we start to lean more on other technologies (e.g., Typescript) then we may want to revisit this.

**Comment by mark-friedman** [comment]
In addition to TypeScript I wonder if the move to ES6 modules for Blockly makes any difference.

**Comment by ewpatton** [comment]
> In addition to TypeScript I wonder if the move to ES6 modules for Blockly makes any difference.

@mark-friedman Can you expand on that more? Since we're just importing the final build of Blockly now it shouldn't matter at the moment. My thought was more that we could eventually rewrite the blocklyeditor code in Typescript to get some additional safety.

**Comment by mark-friedman** [comment]
@ewpatton I was just being paranoid maybe and worrying that Blockly's move to ES6 modules might change the way that we have to import the packages or that the move would change the way that we would have to access the Blockly bindings.

**Comment by ewpatton** [comment]
I'm going to hold off merging this for the moment in case we need to do an emergency release of #3278 @jisqyv

**Pull request merged**
