### PR TITLE
Remove ancient debug logging

### PR DESCRIPTION
**Pull request by espertus**
It's mortifying that we've been logging to consoles unnecessarily for years.

### CODE REVIEW

**Comment by AppInventorWorkerBee** [comment]
Can one of the admins verify this patch?

**Comment by ewpatton** [comment]
Some of this is more recent, but I agree we can at this point probably remove this logging as it serves its purpose (although it’s unclear whether there is a significant performance penalty if the dev tools aren’t open).

This is ok to test.

**Comment by espertus** [comment]
> Some of this is more recent

Good to know. It hadn't occurred to me to do a `git blame`.

FWIW, what called my attention to it was when I did my own logging for debugging and had to dig through irrelevant messages.

**Comment by ewpatton** [comment]
@jisqyv Is there any reason we shouldn't remove this logging?

**Comment by jisqyv** [comment]
@ewpatton No reason, it can go...

**Pull request merged**
