### PR TITLE
Change horizontal alignment so that 2 is centered and 3 is right, in

### PR DESCRIPTION
**Pull request by halatmit**
accord with the documentation.
Note that this is an incompatible change that will break current projects.

### CODE REVIEW

**Comment by halatmit** [comment]
I'd not sure we should do this, since it will break existing projects (but seems more logical and also compatible with the docs).   Suggestions?

**Comment by josmas** [comment]
Is it possible to write an upgrader? Otherwise I'd be weary to do so.

**Comment by halatmit** [comment]
@josmas What do you think the upgrader should do?  I don't see how to do one in general.

**Comment by josmas** [comment]
Is this affecting the numbers used in Blocks when setting alignment in arrangements? I'd say it would not only be blocks, but also property values in scm files, right?

If that's so, the upgrader should take all arrangements and swap 2s and 3s?

**Comment by halatmit** [comment]
We can do the swap if the block has a literal 2 or 3, but not if it's a computed value.
Is that second case rare enough that we can go ahead and break things?   Another approach is to mark the block an add a message to the user warning them to fix it.   We did that sort of thing in Google App Inventor when we switch trig function default from radians to degrees.

**Comment by josmas** [comment]
What do you mean by a computed value in this context? If the value is not either 2 or 3, it should not change.

**Comment by halatmit** [comment]
I mean if  the value is set to an expression, or the value of a variable.



== Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.

**Comment by josmas** [comment]
Right, that makes sense now.I'd say that would be rare enough, though.

**Comment by halatmit** [comment]
I'll work on it.

**Comment by halatmit** [comment]
Subsumed by #711 
Closing

**Pull request closed without merging**
