### PR TITLE
Moved HideKeyboard from TextBox to Form (Bug #285)

### PR DESCRIPTION
**Pull request by farxinu**
The method block has been moved from TextBox.java to Form.java, which increments the versions of YoungAndroid, Form, and TextBox.

### CODE REVIEW

**Comment by farxinu** [comment]
@halatmit @marksherman

**Comment by halatmit** [comment]
@afmckinney @farxinu @marksherman 
Andrew please review this.  Pne issue is that removing the HideKeyboard method from TextBox break existing projects.   It's better to keep the old method there (and also have it in Form), but arrange the upgrader so that the TextBox method is show as deprecated, in a tooltip or something.

**Comment by afmckinney** [comment]
I am testing this now.

**Comment by jisqyv** [comment]
@farxinu Sorry for the slow response, we have been busy on other issues.

A change like this has to provide a an upgrader to upgrade existing projects that are using the HideKeyboard function in TextBlock to use the block from Form (Screen1). As currently written any project that using the HideKeyboard block will break and become unusable.

**Comment by jisqyv** [comment]
@farxinu Btw. If you leave the version in place in TextBox, then you don't have to do an upgrader. We believe that is a reasonable approach.

**Comment by farxinu** [comment]
So I should re-add HideKeyboard as a TextBox method and also have it as a Form method?

**Comment by farxinu** [comment]
@jisqyv sorry, forgot to tag you.

**Comment by jisqyv** [comment]
@farxinu Yes. That will avoid the need for an upgrader.

**Comment by farxinu** [comment]
@jisqyv Should be fixed now.

**Comment by jisqyv** [comment]
@farxinu Note: When you add a new error number, you also have to add the message that goes with it. In this case I have done that for you:

     errorMessages.put(ERROR_SCREEN_INVALID_ANIMATION,
         "Bad value for screen open/close animation: %s");
+    errorMessages.put(ERROR_NO_FOCUSABLE_VIEW_FOUND,
+        "No Focusable View Found");
     // Canvas errors

(for future reference).

Otherwise: LGTM. Tested and on Gerrit for final unit tests.

**Comment by halatmit** [comment]
What's the actual error message being shown by default as the notofication?




== Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.
MIT Media Lab, Second Class Faculty

**Comment by jisqyv** [comment]
@halatmit "No Focusable View Found" (Yeah, I know... I just merged this change, but we can add another change to change the message).

**Comment by jisqyv** [comment]
MERGED

**Comment by halatmit** [comment]
How about "No keyboard is showing".

Does that adequately describe the error condition?


== Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.
MIT Media Lab, Second Class Faculty


On Sun, Oct 18, 2015 at 10:01 PM, Jeffrey Schiller <notifications@github.com

**Comment by jisqyv** [comment]
Not really. The keyboard may well be showing...

**Comment by halatmit** [comment]
Hmm.

OK.  Let's leave it as is and someday figure out something better to say.




== Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.
MIT Media Lab, Second Class Faculty


On Sun, Oct 18, 2015 at 10:32 PM, Jeffrey Schiller <notifications@github.com

**Comment by farxinu** [comment]
Thank you! Sorry, I didn't realize that.

**Pull request closed without merging**
