### PR TITLE
Implement OnOrientationChange interface

### LINKED ISSUE #1322: Orientation change interface
Please read following problem:
https://groups.google.com/forum/m/#!searchin/app-inventor-open-source-dev/Orientation/app-inventor-open-source-dev/QHBlzClp-u8

Now you know what Iam talking about.
Is there any way to create a custom interface which we then can use in any component to detect the orientation change was done?
I ask because I want to handle that case without that users needs any block for some changes. 
I want to let it do it the component with a interface byitself. 

I added as example a interface which is invoked at the same time when the screen orientation change fires. 

Does anyone have a solution for that?

### PR DESCRIPTION
**Pull request by bartmathijssen**
Resolves #1322

### CODE REVIEW

**Comment by SusanRatiLane** [comment]
@bartmathijssen I'm sorry for the long delay on review, but I've been trying to verify my results.

I'm not seeing the Screen1.ScreenOrientationChanged event triggered on change of screen orientation in emulation. It's possible I don't fully appreciate what you're doing here. The old forum link in the issue report was not accessible, so I didn't see all the context.

**Comment by bartmathijssen** [comment]
@SusanRatiLane I didn't give this new addition too much though. I saw the issue and thought this would be a fun addition to the source code. Specifically for extension developers. For example, extension developers could use this new interface to provide an OnOrientationChange event for the blocks editor. They could also choose to use the interface internally.

I hope this gives a little more insight. If not, please let me know.

**Comment by SusanRatiLane** [comment]
@bartmathijssen I thought that existing event functionality was affected, but I've confirmed now that it's an issue with Android emulation and our event.

**Comment by ewpatton** [comment]
It's possible we need to test it on a physical device. I can run a test on my Google Pixel.

**Comment by ewpatton** [comment]
@SusanRatiLane Do you have one of the chromebooks that turns into a tablet? That might work.

**Pull request merged**
