### PR TITLE
Fix a couple of doc pages to remove internal scrollbar

### PR DESCRIPTION
**Pull request by halatmit**

### CODE REVIEW

**Comment by halatmit** [comment]
@jisqyv 
fixing the other 3 pages, the way you fixed activityStarter doc

**Comment by jisqyv** [comment]
@halatmit The changes here look good. However the appstoplay Google doc doesn't have the correct permissions. The document itself also requires some minor editing.

**Comment by jisqyv** [comment]
@halatmit Btw. Where do all the Google Docs themselves live?

**Comment by halatmit** [comment]
Thanks.   I fixed the permissions.   Go ahead and edit.  It probably needs
a better rewrite, though.   We can do that after it's released.

The docs themselves live on my drive in a folder called App Inventor Web
Site pages.  Is there a better place?




== Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.
MIT Media Lab, Second Class Faculty


On Sun, Feb 22, 2015 at 10:16 AM, Jeffrey Schiller <notifications@github.com

**Comment by jisqyv** [comment]
@halatmit Is that folder shared with app-inventor-dev?

**Comment by jisqyv** [comment]
@halatmit Or some similar appropriate team...

**Comment by jisqyv** [comment]
LGTM, Moving to Gerrit for Merge

**Comment by jisqyv** [comment]
MERGED

**Pull request closed without merging**
