### PR TITLE
Reapply css to disabled buttons

### PR DESCRIPTION
**Pull request by E-Hon**
@halatmit 

Please read the doc for details. If this change is a go, a new commit will be made so that the doc will not stay in master branch.

### CODE REVIEW

**Comment by josmas** [comment]
Hi @E-Hon, instead of pushing a pdf doc to each branch, which needs an additional commit (or a cherry pick) it is a lot easier to use this panel for discussion. You can add pictures to this panel too. Could you please change all the pull requests you've done in the last day? Thanks!

**Comment by halatmit** [comment]
I suggest doing only one pull request first, to get the process nailed down.




== Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.
MIT Media Lab, Second Class Faculty

**Comment by halatmit** [comment]
@afmckinney @jisqyv 

Looks good.  And the doc explaining the change is good.
We probably don't want to use the branch_doc convention.
Andrew will write to you saying what convention we do want to use.

**Comment by E-Hon** [comment]
**Description**
The css for disabled ode-TextButtons is used

**Origin**
Screen1 cannot be removed or renamed yet the related buttons are shown like normal. After some look-up, the css supposed to apply to disabled ode-TextButtons is not used. Some of those buttons are “Remove Screen”, “Rename” and “Remove” for Screen1, “Designer” in designer view, “Delete Project” when none is selected.

**Inspection**
The suspected selector is .ode-TextButton[disabled] in appinventor-sources/appinventor/appengine/war/Ya.css. It is shown by Dust-Me that selector is not used even though Screen1 is currently selected
Imgur
According to PushButton (GWT Javadoc) (http://www.gwtproject.org/javadoc/latest/com/google/gwt/user/client/ui/PushButton.html), style rule for disabled buttons should have up-disabled appended. So should ode-TextButtons because the associated widget, TextButton, is a subclass of PushButton. Indeed, the html-class for those buttons, e.g. “Rename”, has ode-TextButton-up-disabled.

**Solution**
Change .ode-TextButton[disabled] to .ode-TextButton-up-disabled
Imgur

**Comment by E-Hon** [comment]
You may try this change here.
http://ai2newfeatures.appspot.com

**Comment by jisqyv** [comment]
@E-Hon LGTM, MERGED

**Comment by E-Hon** [comment]
THX~

**Pull request closed without merging**
