### PR TITLE
Keep extension classes in extension package when proguarding

### PR DESCRIPTION
**Pull request by ewpatton**
Change-Id: Iefd9d3a22cb5ac4a25fdc762843f3422ae1223e8

### CODE REVIEW

**Comment by ewpatton** [comment]
[Relevant discussion](https://community.appinventor.mit.edu/t/error-dx-returned-an-error-code/93800/21?u=ewpatton) with the power users as to why this is needed.

**Comment by puravidaapps** [comment]
after adjusting the proguard rules, rebuilding my extension and importing it into the test project, it now builds fine... 
thank you very much @ewpatton for this fast fix

Taifun

**Review by jisqyv — APPROVED** [review]
LGTM

**Comment by V58M** [comment]
Hola buenas, donde está la extensión bluetooth taifun

**Comment by V58M** [comment]
> Hola buenas, donde está la extensión bluetooth taifun

**Comment by puravidaapps** [comment]
Your question is off topic for here... please use the community https://community.appinventor.mit.edu/ next time

You can find the extension here https://puravidaapps.com/bluetooth.php 

Taifun

**Pull request merged**
