### PR TITLE
Make and/or blocks mutatable

### PR DESCRIPTION
**Pull request by ewpatton**
Co-authored-by: Xueqi Fan <xueqifan@mit.edu>

Change-Id: I9962994dd63381016f9ca187d5e49ac1193c1596

### CODE REVIEW

**Comment by ewpatton** [comment]
This pull request supersedes #804. I've added a coauthored byline because I reused some of the code from that commit. Once merged, we should merge master -> ucr.

**Comment by ewpatton** [comment]
@jisqyv This was a side-effect of me not properly populating the new dropdown when reconstructing the block from the mutator. It should be fixed now.

**Comment by jisqyv** [comment]
@ewpatton Note quite there yet... 
block
I managed to create this monstrosity.

1. Create a three-way *and* block.
2. Change it to an "or" block (it will look fine)
3. Reload the browser.... oops

**Comment by ewpatton** [comment]
@jisqyv The issue with the loading should be addressed. When the block initializes, it always initializes as an AND block, then during the load the field is set to OR. However, this doesn't trigger the update function, so the block never knows to update the other (label) fields to reflect the dropdown state. I've done a bit of a hack to provide a custom setValue function that will also trigger the state update so that the block should reflect the serialized op value.

**Comment by jisqyv** [comment]
@ewpatton It would be helpful if someone more familiar with the blocklyeditor code reviewed this change. I can test, but I'm not the best judge of the correctness of the code vis. a vis. the blockly way of doing things.

**Comment by ewpatton** [comment]
@ellelili2025 @BeksOmega Do either of you want to take a look at this, particularly the logic around the dropdown field.

**Comment by ellelili2025** [comment]
@ewpatton I like the fact that two  initial slots are enforced not to be deleted  when adding an and/or logic. However, after a new slot is added on the top using the mutator, then delete the one on top. All the slots are gone. After this, two or more slots are no longer enforced for and/or logic. The number of slots can be 0, or 1. Is this expected? And we assume users know what they are doing  in that case?

**Comment by ewpatton** [comment]
@ellelili2025 Thanks for catching that. I've pushed a change that should make the mutator more robust to that.

**Pull request merged**
