### PR TITLE
Add dropdown blocks to the blocks editor

### PR DESCRIPTION
**Pull request by BeksOmega**
### Description

This is the mega-PR for my GSoC 2020 project. I squash-and-merge-ed most PRs so most commits on this branch have a link to the PR which covers it. The PR descriptions include a better description and info about how I tested it.

### Dev Docs

I sent all my doc links to Ms. Susan, but I figured I might as well include them here.

Docs for adding new kinds of helper blocks (like dropdown blocks) to the blocks editor. Targeted at App Inventor sources developers: [link](https://docs.google.com/document/d/1cdjkiHvrwWkBm62DR6JrMdCKleOJTlyUwgfVxZq2Rfs/edit?usp=sharing)

Docs for adding helper blocks to your component. Targeted at extension developers or built-in component developers. Meant to act as a living document as new helper block types are added: [link](https://docs.google.com/document/d/1D5K_1JwGzcRFSYFq4n9J8ESK2nJJ_TsNwBtrX8w6-9g/edit?usp=sharing)

Docs for adding dropdown blocks to your component. Targeted at extension developers or built-in component developers. This goes into more detail about dropdown blocks than the previous doc. [link](https://docs.google.com/document/d/10kdXhSKlNBylE9mu2bago76jZVEj4R7H7pe0RKwoLAg/edit?usp=sharing)

### User Docs

I tried my best not to regen the documentation while I was working (some might have snuck through though). I can do that now and add it as a commit, or someone can do it right before they merge. I'm happy to do whatever =)

### CODE REVIEW

**Comment by ewpatton** [comment]
On ai2-test there is an error around the `protect-enum` syntax that I wasn't seeing when testing this before. I'm looking into it and may provide a PR to your branch once I have a fix.

**Comment by ewpatton** [comment]
@BeksOmega As pointed out [here](https://community.appinventor.mit.edu/t/testing-the-next-release-of-mit-app-inventor-nb187/21928/35?u=ewpatton), the dropdown blocks don't appear in the generic component blocks. Can you merge in the latest version of ucr and address that issue? I think we can proceed once these two things are addressed.

**Comment by BeksOmega** [comment]
I'm going to smoke test this after supper, then should be gtg :+1:  (assuming it builds haha)

**Comment by BeksOmega** [comment]
Everything looks good! Obviously I couldn't test everything, but what I did test worked.

- Normal & Generic flyouts
- Helpers in event flydowns, method parameters, and setter parameters
- Upgrading (tested with Ball)
- Comparisons (tested with Ball and EdgeReached)
- DoIt (tested with Direction)

If there's anything else you'd like me to check just shout :D

**Review by ewpatton — APPROVED** [review]
I've merged `ucr` to bring this up-to-date and addressed some minor code issues along with a fix to make this work with iOS as well. I tested with Android 2.60u, the Android companion built by this PR, iOS 2.60 (prod), and iOS 2.60.1 with additional PRs. LGTM.

**Pull request merged**
