### PR TITLE
Save and restore user preferred locale

### LINKED ISSUE #1479: Save locale in UserSettings
[From the forum](https://groups.google.com/d/msg/mitappinventortest/qogmIisZtxc/Sw3o51JYCgAJ): It would be nice if App Inventor remembers the user language selection. Otherwise, it always defaults to English unless the user goes to the specific locale URL.

### PR DESCRIPTION
**Pull request by ewpatton**
For non-English users of App Inventor, if they go to the main page or
click a link without a locale specified, for example, a repo link,
then they will be presented App Inventor in English. This is bad from
a UX perspective as the user then has to change the language and wait
for the site to reload. It also interrupts whatever workflow they were
currently doing (e.g., when opening a template project).

This change stores the last locale from the query string as the user's
preferred locale. When a locale isn't specified in the URL, we will
check the locale and if it is set, redirect to that page
automatically. To also save on performing actions that would be
canceled by the redirect, we also reorder some initialization of Ode
so that it only occurs if the redirect won't happen.

Resolves #1479 

Change-Id: I1b9ffa756aa08f05495832768b242341e4a30c38

### CODE REVIEW

**Comment by ewpatton** [comment]
@jisqyv @SusanRatiLane So I've had this branch sitting around for a couple months, but I think it's reached a stable state where it can be reviewed and merged. and I would rather it not rot.

The motivation for this change is to support our non-English speaking users by saving their locale and using that to automatically restore their preferred language when they open App Inventor (rather than resuming in English).

**Comment by ewpatton** [comment]
I should also note that this is broken out into 3 changes to make it slightly easier to reason about (but they can be squashed down to a single commit). The first change removes some dead code for the AI classic blocks editor that was still being compiled and included in the client code. The second change adds a missing GWT DTD for validating the module. Both make the last change less complicated, which is where the real functionality is added.

**Comment by jisqyv** [comment]
@ewpatton We should probably keep these as three separate commits, as each is a logical unit (and can be reviewed independently). So a "Rebase and Merge" would be better.

**Comment by ewpatton** [comment]
@jisqyv Works for me.

**Comment by jisqyv** [comment]
@AppInventorWorkerBee [skip ci]

**Pull request merged**
