### PR TITLE
remove align restriction, and set linearlayout baselineAlign to false…

### PR DESCRIPTION
**Pull request by liyucun**
This commit is for solving issue #410 and #468 .

The part for #410 is to remove restriction code for alignVertical/alignHorizontal property.

The part for #468  is to add method for setting baselineAlign property, and set it to false by default when initialize arrangement.

Other than this, there are some code to be done on designer screen side. But I create this pull request for testing for this change first, designer won't cause any problem if this one can be integrated to App Inventor.

### CODE REVIEW

**Comment by halatmit** [comment]
@liyucun 
I looked at this quickly and it looks OK, but I'd rather no to a review until it's also fixed in the designer:  we don't want to merge something that's only half done.

**Comment by liyucun** [comment]
Hi @halatmit 

I have fixed this in the designer now. The app inventor instance can be found at: spinner-issue.appspot.com

This enable designer screen show related changed when alignVertical property is Top/Center/Bottom in a automatic height/weight Arrangement.

**Comment by halatmit** [comment]
LGTM
Really nice work!

**Comment by jisqyv** [comment]
LGTM, Pushed to Gerrit for the UCR branch

**Comment by jisqyv** [comment]
@liyucun @halatmit MERGED into UCR

**Pull request closed without merging**
