### PR TITLE
Reserve some Scheme keywords

### LINKED ISSUE #2305: Component named quote breaks apps
**Describe the bug**

[From the forum](https://community.appinventor.mit.edu/t/error-from-companion-attempt-to-invoke-virtual-method-java-lang-class-java-lang-object-getclass-on-a-null-object-reference/15679?u=ewpatton): Companion gives cryptic error about not being able to invoke `getClass()` on null object. The issue was due to a component being named `quote`, which I expect caused issues with the Scheme code.

**Affects**

- [ ] Designer
- [ ] Blocks editor
- [x] Companion
- [ ] Compiled apps
- [x] Buildserver (possibly compilation of screens)
- [ ] Debugging
- [ ] Other... (please describe)

**Expected behavior**

We should not allow people to name their components with reserved keywords for Scheme.

**Steps to reproduce**

1. Create a Label component
2. Rename it to `quote`
3. Connect the companion
4. Observe failure

Renaming the label to something different fixed the issue.

### PR DESCRIPTION
**Pull request by conorshipp**
Resolves #2305

### CODE REVIEW

**Comment by conorshipp** [comment]
I'm not too familiar with Scheme so there might be a few more keywords that I've missed, but any more problematic words can easily be added to the list in the future.

I also noticed that question marks `?` can be added to component names, is this intentional or is that something that should also be fixed as scheme keywords can also contain them.

**Comment by ewpatton** [comment]
A few more I found while testing:

* YailDictionary
* def
* JavaStringUtils
* foreach
* forrange

**Comment by ewpatton** [comment]
I think this looks good @conorshipp. If you can add the additional keywords we can go ahead and merge it.

**Comment by conorshipp** [comment]
@ewpatton I have added those keywords you suggested.

**Review by ewpatton — APPROVED** [review]
LGTM

**Pull request merged**
