### PR TITLE
Updated a sentence in storage documentation, to match the pizza party tutorial better.

### PR DESCRIPTION
**Pull request by ajcolter**
@afmckinney

### CODE REVIEW

**Comment by halatmit** [comment]
LGTM

**Comment by jisqyv** [comment]
@ajcolter @halatmit Actually, there needs to be a corresponding change in FusiontablesControl and OdeMessages (otherwise we may loose this change if we update the documentation from the component build system). I can take care of this (and likely will now) as I prepare this change for Gerrit.

**Comment by jisqyv** [comment]
@ajcolter @halatmit Hmm. Apparently the text in storage.html is way out of phase with the text in FusiontablesControl and OdeMessages. So I'm *not* going to edit them. I'll just put this change in as is.

**Comment by jisqyv** [comment]
MERGED

**Comment by halatmit** [comment]
ugh.   file as issue for fixing this.


== Hal

Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.

**Comment by ajcolter** [comment]
I'll file it as an issue. I didn't realize that my changes to storage.html hadn't been merged yet (I can find those again). Where are the other locations this impacts? I didn't realize this was also in OdeMessages or the FusionTablesControl. I'll take a look.

**Pull request closed without merging**
