### PR TITLE
Fixing the "ShowStatusBar" checkbox in the Designer.

### PR DESCRIPTION
**Pull request by HimaniKaul**
This PR fixes the "ShowStatusBar" checkbox in the properties panel of the Designer.

### CODE REVIEW

**Comment by AppInventorWorkerBee** [comment]
Can one of the admins verify this patch?

**Comment by ewpatton** [comment]
@AppInventorWorkerBee ok to test

**Comment by ewpatton** [comment]
@HimaniKaul This seems fine to me, but one odd thing is that when we hide the status bar in the designer whole phone screen gets smaller. I think what we want is for the screen to stay the same size but increase the size of the MockForm by the size of the (now invisible) status bar.

**Comment by HimaniKaul** [comment]
@ewpatton Okay I will update it.

**Review by ewpatton — APPROVED** [review]

**Pull request merged**
