### PR TITLE
0-indexed row numbers returned in Spreadsheets component resolved

### LINKED ISSUE #2813: 0-indexed row numbers returned in Spreadsheets component
**Describe the bug**

Forum post: https://community.appinventor.mit.edu/t/testers-wanted-google-sheets-component/49195/75

Row numbers returned from the Filter blocks in the Spreadsheets component are 0-indexed when they should be 1-indexed. Other blocks use 1-indexed rows, which can lead to an off-by-one error when reading and writing data.

**Affects**

- [ ] Designer
- [ ] Blocks editor
- [X] Companion
- [X] Compiled apps
- [ ] Buildserver
- [ ] Debugging
- [ ] Other... (please describe)

**Expected behavior**

Row numbers returned should match the row numbers displayed on the spreadsheet.

### PR DESCRIPTION
**Pull request by dhruvpatidar359**
fixes #2813

This PR is making the filter of spreadsheets return the 1-indeex row number while reading from the spreadsheets.

### CODE REVIEW

**Comment by AppInventorWorkerBee** [comment]
Can one of the admins verify this patch?

**Comment by ewpatton** [comment]
@AppInventorWorkerBee ok to test

**Comment by SusanRatiLane** [comment]
@dhruvpatidar359 When a PR affects the Companion, it needs to point to the ucr branch rather than master. The Companion code is found in the components project. 

We would like to get this PR in quickly, so I cherry picked your change onto ucr and updated the the PR.

**Review by SusanRatiLane — APPROVED** [review]
Looks good.

**Comment by dhruvpatidar359** [comment]
> @dhruvpatidar359 When a PR affects the Companion, it needs to point to the ucr branch rather than master. The Companion code is found in the components project.
> 
> We would like to get this PR in quickly, so I cherry picked your change onto ucr and updated the the PR.

ok , i will take care of  it , next time.
Thank You

**Pull request merged**
