### PR TITLE
Implement Trendline component for Charts

### PR DESCRIPTION
**Pull request by ewpatton**
This pull request implements a Trendline component, similar to the Excel feature, that visualizes trends in a ChartData2D element on the corresponding Chart. Note in earlier versions the component was called LineOfBestFit but we decided to align it with existing software students may already be familiar with.

This PR also includes a minor change to the AnomalyDetection component that allows for passing a ChartData2D element in evaluation so that the user does not need to manually construct a parallel version of the dataset for the DetectAnomalies function, which expects a list of data points.

### CODE REVIEW

**Comment by ewpatton** [comment]
@bobparks @stezelMIT If you encounter any errors in testing the new Trendline component, please report them on this PR.

**Comment by stezelMIT** [comment]
Thanks for the amazing effort here @ewpatton .  Issues noticed so far:
(1)Regression component currently only doing linear regression.  Will this change?  Is there a way to indicate  which model they want in the designer or otherwise?  If so can the LOBFValues (name not general? maybe   RegressionValues? or just Values?) dropdown adjust according to model chosen? 
For ex for Linear Regression we should not see QuadCoefficient, ExponentialCoefficient etc. options.  Intercept option should be dropped as there is already a YIntercept option.

(2)For Trendline component too, can the LOBFValues block (name not general?,  RegressionValues? or just Values?) dropdown adjust according to model chosen for ex for Linear Regression we should not see QuadCoefficient, ExponentialCoefficient etc.  Intercept option should be dropped as there is a YIntercept option.
For exponential y=ab^x so there are two parameters to return not clear what Exponential Coefficient is returning (a?) and how to access b?
For logarithmic y=a+bln(x) so there are two parameters to return not clear what LogarithmCoefficient is returning (a or b?) and how to access both?

@bobparks  will be testing his tutorial to see if there are any problems with the functionality.

**Comment by stezelMIT** [comment]
Also for quad regression we need to be  able to access three coefficients a,b,c where  y=ax^2+bx+c 
and we can't call b slope anymore.

**Comment by bobparks** [comment]
Yes, thanks so much, @ewpatton. This will be great for the workshop. 

A critical issue is an error that comes up using our tutorial AIA. The error comes from the set.trendline.ChartData component. Despite the error, the block creates a correct LOBF line in Companion for the top chart but does not execute any additional code in the event handler (such as a second LOBF line for the bottom chart.) 
LOBF_draw_error copy

Here is the AIA: https://drive.google.com/file/d/1oEPTUCosq6Fa4aMfzIoS-scT91z1fS2e/view?usp=sharing

**Comment by ewpatton** [comment]
> (1)Regression component currently only doing linear regression. Will this change? Is there a way to indicate which model they want in the designer or otherwise?

I should be able to add this without too much effort.

> If so can the LOBFValues (name not general? maybe RegressionValues? or just Values?) dropdown adjust according to model chosen?

LOBFValues was the name that Hanya gave to the enum and while changing it is possible it is difficult. I would try to avoid Values as that is much too generic. RegressionValues might be okay. Adjusting the dropdown to the state isn't feasible because we cannot guarantee what the state of the property is at coding time since the model can be changed programmatically at runtime.

> For exponential y=ab^x so there are two parameters to return not clear what Exponential Coefficient is returning (a?) and how to access b?

The exponential formula in the OLS model is modeled as y = e^(ax + b), so at the moment the linear coefficient returns a and the Yintercept returns b. If you want a and b in your version you'd have to transform both by raising e to the power of a and b, respectively. Ditto the logarithmic version (just the opposite operation).

> A critical issue is an error that comes up using our tutorial AIA. The error comes from the set.trendline.ChartData component.

I believe this is already fixed in the PR but it wasn't at the time I built the test server. I will rebuild and redeploy.

**Comment by stezelMIT** [comment]
>Adjusting the dropdown to the state isn't feasible because we cannot guarantee what the state of the property is at coding time since the model can be changed programmatically at runtime.
If so, it is not clear what happens if someone  puts QuadCoefficient or ExpoCoefficient into a linear regression query.  Do you get NaN, or 0?
> The exponential formula in the OLS model is modeled as y = e^(ax + b), so at the moment the linear coefficient returns a and the Yintercept returns b. If you want a and b in your version you'd have to transform both by raising e to the power of a and b, respectively. Ditto the logarithmic version (just the opposite operation).
> 
Then somewhere in the documentation we  need to show exactly what type of equation is being used  to describe exponential and logarithmic  regressions.  In high school math classes we  have been using the y=ab^x for exponential and y=a+bln(x) for logarithmic which seems different than what we have here, we need to explicitly show what each of the returned values represent in the documentation.

BTW the documentation has a lot of references to LOBF language, we need to make sure things are generalized there also.

**Comment by bobparks** [comment]
A critical issue is an error that comes up using our tutorial AIA. The error comes from the set.trendline.ChartData component.

I believe this is already fixed in the PR but it wasn't at the time I built the test server. I will rebuild and redeploy.

Hi Evan,

Thanks. Did you get a chance to redeploy the LOBF instance? I’m still getting the error.

***@***.***

Robert

**Comment by halatmit** [comment]
Thanks.
Please make sure to update
testing appinventor development
with any  new server info
https://docs.google.com/document/d/1UXNJ8dlcAFXvAA2n3M6x5fiQBvHSq_yYysj8Z7iypHk/edit#heading=h.gzi2593zsuch

**Comment by bobparks** [comment]
Hi Evan, Just an update on another issue that popped up. First, thanks so much for simplifying the process of detectAnomalies by using the new detectAnomaliesInChartData block. It works great. 

The issue is same Yail error when I try to include this block to update the top chart. I assume it's because when it updates it runs the flawed Trendline block. 

image

**Comment by ewpatton** [comment]
@bobparks The test server has been updated. Please make sure to install companion version 2.69d4u from the server to get the bugfix.

@halatmit The doc has been updated and the test server for this feature is listed under Data Science.

**Comment by bobparks** [comment]
Thanks so much! Have a good weekend

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by stezelMIT** [comment]
I am wondering if for this release we should get rid of ALL non-linear regression references, properties etc.   EVERYWHERE (including the info pages) Options like QuadCoeff, LogCoeff etc. give wrong impression that these non-linear models are ready to go.  Given our timeline this is what I recommend.  We will worry about non-linear approaches  at a later time, perhaps an excellent work for a UROP.

**Comment by bobparks** [comment]
Hi @ewpatton, I've been writing the lesson using the new blocks, but there are a few bugs that I hope are easy to fix. For now, though, they are holding us back from completing the lesson. 

1.) After kids have performed the various data cleaning steps on the screen, we want kids to be able to restart their screen with blank data to try the whole sequence again (Show Data --> Draw LOBF --> Detect Anomalies --> Clean Data --> Restart from original state). However, there does not seem to be a way to remove the trendline from the chart. [It reappears after you clear the chart](https://drive.google.com/file/d/1Z3umS7Q8Ugt4rhutncB_O22ui7A2RxGI/view?usp=drive_link). An easy solution would seem to be to make the trendline invisible, but [an invisible trendline still enforces a big change in the chart's domain](https://drive.google.com/file/d/1DnCsHXzoocrbCWvfmPPz8kPtb5ER-AB_/view?usp=drive_link). [Here is an AIA to test](https://drive.google.com/file/d/1OG6HXohdaFqKZ4zqgBxiiKFRHcLm6bjY/view?usp=drive_link) with this. To reproduce this code, go to cleanDataScreen. (Please ignore the weirdness of the if statement; it is explained below.) 

2.) Something in the EntryClick block in this code is causing the chart to [spontaneously reset its *range*](https://drive.google.com/file/d/12jRpYyVhGAzGvHNdH3EhzRyJtztNihhQ/view?usp=drive_link
) when the user clicks a datapoint with EntryClick a *second time*. [Here is the same AIA as above to test](https://drive.google.com/file/d/1OG6HXohdaFqKZ4zqgBxiiKFRHcLm6bjY/view?usp=drive_link) with this. To reproduce this problem, go to cleanDataScreen and remove the two anomalies, starting with the one on the left (this is a quirk of the code, as explained below.) Notice that when you remove the second anomaly, the top chart range changes and defies its property setting. 

3.) We would like kids to be able to remove the out-of-context anomalies using the touchscreen. However, when the user clicks anywhere on a blank space in the chart, the EntryClick block returns any data point on this x-axis, even if it is not near one's finger. To avoid accidentally selecting data points, we tried to set up [an if statement that would check if the EntryClick return is in the list of anomalies](https://drive.google.com/file/d/1aICVqLHo4w3y51-Pd_Z2L07RwjpbI4xi/view?usp=drive_link). However, DetectAnomalies returns a list of data points in which [X is incremented from 1](https://drive.google.com/file/d/10FcHJNm5BvZdqi7N8CvXLTMYjXtcrGhk/view?usp=drive_link) and EntryClick returns the real value of X for the datapoint, so they are hard to compare. Can we make DetectAnomalies (and HighlightDataPoints) use the actual x values and not an incremented list? This is the reason for the strange acrobatics in the if statement of the test code. Here is [an image of the code](https://drive.google.com/file/d/1aICVqLHo4w3y51-Pd_Z2L07RwjpbI4xi/view?usp=drive_link
) and [here is the AIA](https://drive.google.com/file/d/1OG6HXohdaFqKZ4zqgBxiiKFRHcLm6bjY/view?usp=drive_link
). To test the code, go to cleanDataScreen and remove the two anomalies starting with the one on the left (I'm sure there's a better way to reconcile the x values for EntryClick with those in the DetectAnomalies list, but this was my quick test.) 

4.) The new trendline component seems to crash the emulator. (It would be nice to use the emulator to write the tutorials.) To reproduce the problem, [run this test AIA](https://drive.google.com/file/d/1oEZdTEM4N0B3mt_jaqDiLkL_iNLEskTw/view?usp=drive_link
) and go to the cleanDataScreen. If you call trendline.chartdata by pressing the Show Data button, then the Draw LOBF button, then the Show Data button again to reset the screen, the emulator crashes. Alternatively, if you do not call trendline, it's fine.  

To get a sense of the direction we would like to head by solving some of these issues, here is our ideal code, which encounters the issues listed above: ([image](https://drive.google.com/file/d/1vgQmewalieGM_oF5hURwO8vvTAd_7VMt/view?usp=drive_link
) and [AIA](https://drive.google.com/file/d/12vtfGkUO1TaaEy3knKeRm1RCAtqkg03z/view?usp=drive_link
)). 
@stezelMIT

**Comment by ewpatton** [comment]
@bobparks @stezelMIT The test server has been updated. I have tried to address your feedback in the following ways:

> If so, it is not clear what happens if someone puts QuadCoefficient or ExpoCoefficient into a linear regression query. Do you get NaN, or 0?

A lack of a property will result in NaN if the property isn't relevant, for example using Yintercept when in Exponential or Logarithmic mode. The only exception is that QuadraticCoefficient will return 0 for Linear models (since technically a linear model is just a quadratic model where the quadratic a coefficient is 0).

> Then somewhere in the documentation we need to show exactly what type of equation is being used to describe exponential and logarithmic regressions. In high school math classes we have been using the y=ab^x for exponential and y=a+bln(x) for logarithmic which seems different than what we have here, we need to explicitly show what each of the returned values represent in the documentation.

I have updated the exponential and logarithmic models to conform to the mathematical versions desired by Selim. The following properties have been added to support them: ExponentialCoefficient, ExponentialBase, LogarithmicCoefficient, and LogarithmicConstant. I have also [updated the reference documentation](https://lobf-dot-ai2-ewpatton-temp.uc.r.appspot.com/reference/components/charts.html#Trendline) to include the explanation of the equations and how they map to each property. 

> After kids have performed the various data cleaning steps on the screen, we want kids to be able to restart their screen with blank data to try the whole sequence again (Show Data --> Draw LOBF --> Detect Anomalies --> Clean Data --> Restart from original state). However, there does not seem to be a way to remove the trendline from the chart. It reappears after you clear the chart.

Technically, the trendline does disappear when you clear the dataset. Once you add more data to the ChartData2D, the trendline recomputes itself. To address this, I have added a new block DisconnectFromChartData that you can use to disassociate the trendline from the original dataset. However, I imagine it should still be sufficient to just use Visible = false.

> Something in the EntryClick block in this code is causing the chart to spontaneously reset its range when the user clicks a datapoint with EntryClick a second time.

There is actually not an issue in the Chart or Trendline code here and the component is behaving as expected. The behavior you are seeing is due to the fact that when you remove the anomalies in the top dataset, the trendline updates itself, which triggers the Updated event of the Trendline, in which you then call ExtendDomainToInclude(Trendline.XIntercepts). The chart also updates its range based on the Y values in the dataset. I found the best approach was to call ExtendRangeToInclude(0) so that the bottom of the chart was always fixed to 0 days of ice. This also has the benefit of being able to see where the trendline intercepts the Y axis.

> However, DetectAnomalies returns a list of data points in which X is incremented from 1 and EntryClick returns the real value of X for the datapoint, so they are hard to compare. Can we make DetectAnomalies (and HighlightDataPoints) use the actual x values and not an incremented list? 

I will have to think about this further because Hanya's implementation has no concept of an X value. It's simply looking at the distribution of values, assumes they are gaussian, and then flags anything > n z-scores away from the mean where n is specified by the user. Changing the APIs of these existing blocks will break any apps currently using them. Let's plan to make some time on Monday to discuss this.

> The new trendline component seems to crash the emulator. 

This should be fixed in this latest release. Make sure you are using companion verison 2.69ud5.

**Comment by bobparks** [comment]
Thanks, Evan!

**Comment by ewpatton** [comment]
Per the conversation by email, I've updated the Chart component to provide the Type getter block. Companion version is now 2.69d6u.

**Comment by bobparks** [comment]
@ewpatton @stezelMIT  Things are working well with these blocks except for one new problem: When I set the trendline or update the trendline, the ExtendDomainToInclude method does not take effect. Only when I reimport new chart data or change the chart data does the ExtendDomainToInclude work. This is different from the last iteration, where [this AIA](https://drive.google.com/file/d/1BrrTjf9qPD9P1mhUtkCsGhV1hZYees4V/view?usp=sharing
) would extend the domain as soon as the user pressed the trendline button. Thanks for your help with this.

**Comment by bobparks** [comment]
@ewpatton @stezelMIT Excuse me. The issue listed above only occurs on the Emulator. So not a priority.

**Comment by ewpatton** [comment]
@bobparks The test server has been updated to version 7 and the companion version is now 2.69d7u. With this change, you should be able to do the following logic in the EntryClick handler:

blocks (98)

Although for performance reasons it would make more sense to store the result of the anomaly calculation in a global list so it doesn't have to be recomputed for every click event.

**Comment by bobparks** [comment]
Sounds good. I'll instruct kids to create a global list to hold the anomalies.

**Comment by ewpatton** [comment]
@bobparks @stezelMIT Unless there are any critical blockers at this point, I want to invite @mit-cml/core-reviewers to start a formal review so we can get this into the next release.

**Comment by stezelMIT** [comment]
My LOBF graph stopped showing while testing Roberts latest starter file.  Don't know what is going on.  Also getting several "internal error" bugs when this file uploads.
[Lesson_4_Predictions_template_02_02_24.aia.zip](https://github.com/mit-cml/appinventor-sources/files/14144977/Lesson_4_Predictions_template_02_02_24.aia.zip)

**Comment by ewpatton** [comment]
@stezelMIT Ok I will take a look.

**Comment by stezelMIT** [comment]
Getting error from ChatBot code -1 Error talking to ChatBot proxy.  Here is the finished product:
[Lesson_4_Predictions_template_02_02_24_withAI.aia.zip](https://github.com/mit-cml/appinventor-sources/files/14171563/Lesson_4_Predictions_template_02_02_24_withAI.aia.zip)

**Comment by bobparks** [comment]
Hi Evan,   When you get a chance, would you take a look at these last issues? 

To sum up, 169.d7 has the following issues: 

-- Bug notices when loading [the AIA](https://drive.google.com/file/d/1R7jFvleaoyWtdXQD0WR09ZPsjf0SmvN_/view?usp=drive_link)
-- Method extendDomainToInclude doesn't fire the first time it's called. 
-- ChatBot does not work in the LOBF test instance and throws ChatBot code -1 Error talking to ChatBot proxy error 

Thanks!

**Comment by ewpatton** [comment]
I will try to get to these tomorrow once I am back in the office.

**Comment by ewpatton** [comment]
So I think for 1 and 3 the issue is just that the test server hadn't been configured to work with ChatBot since that wasn't really necessary for testing. For item 2, I am looking into that now.

**Comment by ewpatton** [comment]
@stezelMIT @bobparks The test server has been updated. New companion is 2.69d8u. I also configured it to support the ChatBot so you can test that integration.

**Comment by ewpatton** [comment]
@AppInventorWorkerBee retest this please

**Comment by ewpatton** [comment]
@daki7711 I think this is ready for a final review pending any last comments from @bobparks.

**Comment by bobparks** [comment]
Thanks for these changes and the work behind them. Everything works well on this end.

**Comment by stezelMIT** [comment]
Our humble gratitude for all the enormous work that has gone into this.

**Comment by bobparks** [comment]
@ewpatton Hi Evan, 

Sorry about the late response, but we realized that one of the issues from above is still open: 

      -- Method extendDomainToInclude doesn't fire the first time it's called

Also, we were wondering if the change in the wording of X-intercept(s) -- using parenthesis -- was implemented yet on the server. Thanks.

**Comment by ewpatton** [comment]
@bobparks I am not seeing any issues when using the ExtendDomainToInclude (or ExtendRangeToInclude) block. At least in the AIA you attached previously those blocks are not used. I added them into the Trendline1.Updated event and the graph appears to update everything correctly for me when I remove the anomalies. Do you have exact reproduction steps with a project file?

**Comment by stezelMIT** [comment]
[Lesson_4_Predictions_template_02_13_24_final_starter_step2Test.aia.zip](https://github.com/mit-cml/appinventor-sources/files/14300374/Lesson_4_Predictions_template_02_13_24_final_starter_step2Test.aia.zip)

Try the AIA file here.  When using the Predictions screen after LOBF is generated, the domain does not adjust as requested.

**Comment by ewpatton** [comment]
@bobparks The lobf server now has version 9 with the redraw issue resolved.

**Comment by ewpatton** [comment]
@bobparks Please let us know once you've tested this latest version so that Jeff can merge this and start the release process.

**Comment by bobparks** [comment]
@ewpatton I just ran both apps on the emulator (#9), and everything works well. No problems with any of the functions. Thanks for fixing the redraw issue!
@stezelMIT

**Review by jisqyv — APPROVED** [review]
LGTM

**Comment by Aditya-dom** [comment]
> This pull request implements a Trendline component, similar to the Excel feature, that visualizes trends in a ChartData2D element on the corresponding Chart. Note in earlier versions the component was called LineOfBestFit but we decided to align it with existing software students may already be familiar with.
> 
> This PR also includes a minor change to the AnomalyDetection component that allows for passing a ChartData2D element in evaluation so that the user does not need to manually construct a parallel version of the dataset for the DetectAnomalies function, which expects a list of data points.

### **I have doubt**

// -*- mode: java; c-basic-offset: 2; -*-
// Copyright 2023-2024 MIT, All rights reserved
// Released under the Apache License, Version 2.0
// http://www.apache.org/licenses/LICENSE-2.0

package com.google.appinventor.client.editor.youngandroid.properties;

import static com.google.appinventor.client.Ode.MESSAGES;

import com.google.appinventor.client.widgets.properties.ChoicePropertyEditor;

public class YoungAndroidStrokeStylePropertyEditor extends ChoicePropertyEditor {
    **private static final Choice[] strokeStyles = {**
        new Choice(MESSAGES.strokeStyleSolid(), "1"),
        new Choice(MESSAGES.strokeStyleDashed(), "2"),
        new Choice(MESSAGES.strokeStyleDotted(), "3")
    };

    public YoungAndroidStrokeStylePropertyEditor() {
        super(strokeStyles);
    }
} 

Can we do this?

**Pull request merged**
