### PR TITLE
Add brief Firebase intro (does not replace full documentation)

### PR DESCRIPTION
**Pull request by halatmit**

### CODE REVIEW

**Comment by jisqyv** [comment]
@halatmit LGTM. Do we want to merge this now or wait until we merge the Firebase component and merge it with it?

**Comment by halatmit** [comment]
Either way is fine.  You saw the disclaimer I added at the beginning.  But
it might be safer to Wait.

**Comment by jisqyv** [comment]
@afmckinney @halatmit I "stole" this review from you. I'm checking it now, but my intention would be to merge this after the Firebase change is merged (alternatively, I can incorporate this change in the Firebase commit). Hal, what do you think?

**Comment by jisqyv** [comment]
@halatmit LGTM

**Comment by halatmit** [comment]
@jisqyv  I'd merge this after the Firebase change is merged.

**Comment by jisqyv** [comment]
@halatmit MERGED

**Pull request closed without merging**
