### PR TITLE
Update traditional chinese translation for HK

### PR DESCRIPTION
**Pull request by ellelili2025**
translate the newly added messages into tranditional chinese.

### CODE REVIEW

**Comment by ellelili2025** [comment]
@AppInventorWorkerBee  please retest it.

**Comment by ellelili2025** [comment]
@AppInventorWorkerBee please retest it.

**Comment by jisqyv** [comment]
@ellelili2025 It looks like you brought some of the branding branch changes into the master branch (we try to keep MIT specific documentation out of master because it is used by other instances of App Inventor not hosted by MIT). Also, the Google Doc referenced in one of the changes is deleted (!!).

**Review by jisqyv — CHANGES_REQUESTED** [review]
See comments

**Comment by ellelili2025** [comment]
@jisqyv  I thought these changes were meant for HK branding branch only. And I don't have access to the branding branch. I was told to make these changes in master branch but would need your help to transfer them to branding branch. @ewpatton  Let me know if I understood it wrong.

**Comment by ellelili2025** [comment]
@jisqyv  I have removed the change that linked to the deleted google doc per your request.

**Comment by SusanRatiLane** [comment]
@jisqyv Does this PR still have branding branch content? It looks ok to me.

**Comment by jisqyv** [comment]
@SusanRatiLane It still does, but it is probably fine as is. The branding branch changes are just references to our documentation, but is probably OK even for other systems.

**Comment by SusanRatiLane** [comment]
"Switch" isn't translated, which is odd, because newer stuff seems to be. Otherwise looks fine. I'm merging.

**Review by SusanRatiLane — APPROVED** [review]

**Pull request merged**
