### PR TITLE
Implement SAF (Storage Access Framework) component 

### PR DESCRIPTION
**Pull request by vknow360**
Most developers felt homely by using legacy "File" approach, but launching of Android 10 started causing troubles for them and SAF is the solution to most of their problems.
Using this, you can-

* access phone storage`*`
* access SD card`*`
* read from/write to files created by other apps
* help user in protecting his/her data and restrict Storage consumed by apps
* get access to files and folders which are important to your app.
In this way, you needn't ask for MANAGE_EXTERNAL_STORAGE permission.
* work with non-media files too, such as creating a CSV file of user's data or accessing a PDF file

`*`: `Android/data` and `Android/obb` folders are exception

One major advantage I would like to emphasize is usage of URIs instead of paths.

### CODE REVIEW

**Comment by ansh2166** [comment]
Epic work @vknow360 🥳

**Review by thexomadev — CHANGES_REQUESTED** [review]
In most of the methods, you're returning the result or the exception message, which make it difficult for the user to determine if it's the result or what.

I would recommend adding line breaks for those "long" descriptions if possible, it would be more readable also with some Docs (comments).

For function like 'StringToUriObject', you should consider making it simpler like 'CreateUriObject'.

**Comment by AppInventorWorkerBee** [comment]
Can one of the admins verify this patch?

**Comment by XomaDev** [comment]
Throwing exceptions are the most important part and you are just posting the message to the event, it's too not okay to debug. Exceptions are there for work.

**Comment by ewpatton** [comment]
@vknow360 You should rebase the SAF-specific commits onto ucr. At the moment there are a number of commits from master not on ucr in this PR and it creates a lot of extra files to review unnecessarily.

**Pull request closed without merging**
