### PR TITLE
fix for typeblock with mutators #257

### PR DESCRIPTION
**Pull request by josmas**
Fix for #257

### CODE REVIEW

**Comment by halatmit** [comment]
LGTM

**Comment by jisqyv** [comment]
Getting ready to push to Gerrit...

**Comment by jisqyv** [comment]
MERGED

**Comment by afmckinney** [comment]
Thanks Jeff… 


Andrew F. McKinney
andrew.f.mckinney@gmail.com <mailto:andrew.f.mckinney@gmail.com>
+1 978-255-3979

**Pull request closed without merging**
