### PR TITLE
Implement multidex in the buildserver

### PR DESCRIPTION
**Pull request by ewpatton**
Change-Id: I1593438f80d59e9bcf6e7eb407ce902700bc67dc

### CODE REVIEW

**Comment by jisqyv** [comment]
@ewpatton P.S. Build time went from 3:30 to 5:10 on my machine.

**Comment by ewpatton** [comment]
Hmm. That should have been handled with the addition of everything in AndroidRuntime.jar to the main classes dex file. I'll run some tests and figure out what's going on there.

**Comment by ewpatton** [comment]
@jisqyv So it turned out there were two issues. The first was that I didn't have the format of the main dex list file correct. It's generated by the gradle plugin these days, but I found an old script in the AOSP that helped me get it correct. The second issue was that with all of the support libraries, the main dex while still a single dex causes the DexOpt tool to crash on the emulator during install. I've created `CRITICAL_JARS` to be enough to bootstrap to the point where MultiDex will run, and then the rest of the support libraries + component libraries will be loaded. On Android 5.0+, ART converts the dex files to OAT so there's nothing that needs to be done.

I tested on an emulator running SDK 7 and my Google Pixel running Android (SDK 29).

**Comment by ewpatton** [comment]
@jisqyv That's also quite a difference in build time. This PR takes 2:36 to build versus master at 2:47 on my Mac. Were those numbers with your CPU throttle on or off?

**Comment by pavi2410** [comment]
> The first was that I didn't have the format of the main dex list file correct. It's generated by the gradle plugin these days, but I found an old script in the AOSP that helped me get it correct.

I generated a [mainDexList.txt](https://github.com/mit-cml/appinventor-sources/pull/2034/commits/9f8e487cb0abec7e8a32facac5601ae6263b58a1) which lists all the classes required in the main dex. To generate that, I ran this command on `d8.jar`:

```
java -cp d8.jar com.android.tools.r8.GenerateMainDexList --lib "D:\AndroidSDK\platforms\android-28\android.jar" plain.apk  
```

**Comment by pavi2410** [comment]
Also, it is necessary to manage dex files manually when D8 (PR #2034) does this automatically?

**Comment by ewpatton** [comment]
@pavi2410 I'm confused by your example. If you've already got the apk, you would have had to previously generate the classes.dex file prior to creating the apk (otherwise, it wouldn't have any classes in it, which seems useless to me). Could you expand on why your example would work in the context of the BuildServer? Note that the main dex list also needs to include all of the screens included in the app, otherwise it would be possible to generate a classes.dex without the screens. I don't get the sense reading through #2034 that this is handled.

**Comment by jisqyv** [comment]
@ewpatton On buildtimes. I believe we were comparing Apples and Oranges. With your latest change, I did an "ant clean" followed by an "ant PlayApp" (so no GWT compiling) and the total time was 46 seconds. Not bad!

**Pull request merged**
