### PR TITLE
Fixed Issue 2517

### PR DESCRIPTION
**Pull request by preetvadaliya**
This PR fixed issue #2517

### CODE REVIEW

**Comment by AppInventorWorkerBee** [comment]
Can one of the admins verify this patch?

**Comment by ewpatton** [comment]
@AppInventorWorkerBee ok to test

**Comment by ewpatton** [comment]
@preetvadaliya Note that this change should technically be on `ucr` since it changes the behavior of the component in the companion. That said, since we are close to a companion release and it has limited potential effect I think it's probably okay ot keep it against `master`. In the future you may want to double check which base branch to submit against.

**Comment by ewpatton** [comment]
Up to you. I'd like to merge it today. If you have time please do otherwise I'll do it at the end of the day.

**Pull request merged**
