### PR TITLE
Add documentation for using Genymotion emulator

### PR DESCRIPTION
**Pull request by halatmit**

### CODE REVIEW

**Comment by jisqyv** [comment]
@halatmit Did you really intend to remove the index.html file in the doc/reference section and the sample .gitignore?

**Comment by halatmit** [comment]
I think that index.html was a superfluous wrong one.   Am I correct about
that?

Bu you're right,  should have kept the sample-.gitignore.   I think I
created mu .gitignore by renaming sample, when I should have copied.  That
might be wrong in our instructions.




== Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.
MIT Media Lab, Second Class Faculty

**Comment by jisqyv** [comment]
I'm not sure about the index.html page. It is definitely in the old style, but the links on it are valid. I don't know if it is referenced anywhere.

**Comment by halatmit** [comment]
I think that everything on it is duplicated here:

http://appinventor.mit.edu/explore/library.html

in the separate pages linked to at the bottom. Is that correct?



== Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.
MIT Media Lab, Second Class Faculty

**Comment by halatmit** [comment]
issue #331

**Comment by jisqyv** [comment]
@halatmit I've restored the sample-.gitignore but left the index.html file deleted. If it turns out we need it, we can put it back.

**Comment by jisqyv** [comment]
LGTM

**Comment by jisqyv** [comment]
MERGED (master)

**Pull request closed without merging**
