### PR TITLE
Implement metadata annotations for extensions

### LINKED ISSUE #1882: App Metadata and Activity Metadata for extensions
**Describe the desired feature**

Over the years we have received a number of requests for adding supplemental metadata to the Android Manifest. We do have a mechanism for doing this for new activities introduced by extensions, but these methods fall short if one wants to update metadata associated with Screen1 or with the app as a whole.

**Give an example of how this feature would be used**

I imagine that we would need to have two tags `@UsesApplicationMetadata` and `@UsesActivityMetadata`. The former would place metadata within the `<application>` tag in AndroidManifest.xml and the latter would place it into the `<activity>` tag associated the current component's form.

**Why doesn't the current App Inventor system address this use case?**

Extension cannot add this data to the manifest at this time.

**Why is this feature beneficial to App Inventor's educational mission?**

Odds are that it probably isn't, but I'm making this issue as a tracking issue in case someone in the extension community wants to work on it.

### PR DESCRIPTION
**Pull request by bartmathijssen**
Resolves #1882

### CODE REVIEW

**Comment by ShreyashSaitwal** [comment]
How long will it take for this PR to be reviewed? 🙂
I've some work pending on an extension that needs to update the application's metadata.

**Comment by jisqyv** [comment]
@bartmathijssen I'll look at it today.

**Comment by ShreyashSaitwal** [comment]
BTW @bartmathijssen, can you please provide some sort of examples on how to use these annotations?

**Comment by AKBIROCK3** [comment]
lets say that we want to add a changable value like app ID in meta data 
how to do it ?
is it possible ?

**Comment by souvik-bera** [comment]
@AKBIROCK3 That is still not possible unfortunately

**Comment by mpbejo** [comment]
Hi everybody,
I am developing an extension to read and write NFC Tag, to manage correctly the different type of NFC Tags I have to add some lines in the AndroidManifest.xml file 
In the https://docs.google.com/document/d/1UsjVC6bjf4rKPLP6FULUPeB6C8O-A5GbpYjvvwqTYK8/edit#heading=h.am32jfxx9u74
I read that I can add MetaDataElement for the AndroidManifest.xml file,now in my extension I added:
usesActivities
And I think is correct, only I don't understand how to add the nfc_tech_list.xml file to the extension.
I need some help 
Thank You 
Marco

**Comment by mpbejo** [comment]
No comment! not a single word, possible? is such a waste of time?

**Pull request merged**
