### PR TITLE
Rotate image

### PR DESCRIPTION
**Pull request by halatmit**

### CODE REVIEW

**Comment by halatmit** [comment]
Issue #645

**Comment by jisqyv** [comment]
@halatmit ImageView.setRotation requires API 11 (Honeycomb). I was able to build a Companion with your code and it loaded in the Emulator (API 8), but generated an error at runtime. I'm not sure why it didn't get a linkage error when loading though. That said, a conservative approach might be to move the call to setRotation to HoneycombUtil and call it there from Image.java based on an appropriate SdkLevel test.

**Comment by halatmit** [comment]
Weird.  I thought I'd tested that on Gingerbread but I guess I blew it.

I agree with your plan.   Do you want to do it, or should I?




== Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.

**Comment by jisqyv** [comment]
If you do it I can review it. Or I can do it and you can review it. The
interesting question is what to do on older devices.
-Jeff

**Comment by halatmit** [comment]
Can you do it?  I'm in Hong Kong jail.

I suggest on older devices to just give a notice that it cannot be done.
I think full screen on video shows a similar notice.



== Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.

**Comment by jisqyv** [comment]
@halatmit I'll take care of it then...

**Comment by halatmit** [comment]
Thanks.


== Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.

**Comment by jisqyv** [comment]
Superceded by #659

**Pull request closed without merging**
