### PR TITLE
Restore HELPURLs and strings that were not converted to JSON

### PR DESCRIPTION
**Pull request by SusanRatiLane**
Deleted lines are strings that were moved into the proper alphabetic location in the file.

### CODE REVIEW

**Comment by ewpatton** [comment]
@SusanRatiLane I think this is also missing the Chinese translations provided by @ellelili2025 in an earlier change. Can you update the two Chinese files as well?

**Comment by SusanRatiLane** [comment]
@ewpatton I have added the Chinese translations, but there's a bug in translations of those CONTAINS blocks that is not directly related to these strings. The contains block only loads into the Text flyout menu when the language is English. I'm looking but haven't found the issue yet.

**Comment by SusanRatiLane** [comment]
@ewpatton Fixes the contains string. This is ready for another look.

**Comment by SusanRatiLane** [comment]
@ewpatton @ellelili2025 Test failure addressed. Should be ready for a look.

**Review by ewpatton — APPROVED** [review]
LGTM

**Pull request merged**
