### PR TITLE
Immediately active new screen when opening

### PR DESCRIPTION
**Pull request by ewpatton**
Change-Id: If0f8a1faa3230e7116400d8e8c8ea1c48ed55220

### CODE REVIEW

**Comment by ewpatton** [comment]
The relevant community post is here: https://community.appinventor.mit.edu/t/after-screen2-initialize-nothing-is-displayed/79455?u=ewpatton

There appears to be a race condition in how quickly iOS can switch screens and when the code is sent from the web editor. This change makes the new screen active just before sending a message via the RetValManager to ensure that it is active for when the code arrives.

**Comment by daki7711** [comment]
Maybe I'm doing something wrong in my testing but this PR didn't help fixing the bug that was explained in the community site. Funny thing is, when I input nothing for heights and weights I get something in Screen2 but when I input some numbers (e.g., height 175, weight 70) Screen2 is just blank

**Comment by ewpatton** [comment]
@daki7711 So there were some other interactions that needed to be fixed. In particular, in the particular app in question if the user is editing the text and then clicks calculate, the LostFocus event fires on the TextBox, which resets the active form to the old screen (which then receives the Screen2 code). However, if you're not editing the text when clicking the button, there isn't a post transition event involved so my first iteration of the fix worked. The PR has been updated with the additional logic.

**Review by daki7711 — APPROVED** [review]
LGTM

**Pull request merged**
