### PR TITLE
Fix gyro sensor - reset previousValue to -1 on mode switch

### LINKED ISSUE #2291: Ev3GyroSensor should reset previousValue in setMode?
**Describe the bug**

It seems that the Ev3GyroSensor should reset its previousValue to -1 inside its [setMode](https://github.com/mit-cml/appinventor-sources/blob/9638c167f559ad4b40fccd310ee5baf3ce6f76ad/appinventor/components/src/com/google/appinventor/components/runtime/Ev3GyroSensor.java#L178) function to match the behavior of the [Ev3ColorSensor](https://github.com/mit-cml/appinventor-sources/blob/9638c167f559ad4b40fccd310ee5baf3ce6f76ad/appinventor/components/src/com/google/appinventor/components/runtime/Ev3ColorSensor.java#L445). As noted by Evan [here](https://github.com/BeksOmega/appinventor-sources/pull/21#discussion_r476446536):

> The checker logic uses -1 to indicate that data has yet to be received. Given that changing the mode changes the value space of the data being received it really ought to reset the previous value to indicate no data has been received in the new value space. Otherwise, the comparisons occurring in that code are really apples to oranges (or angles to rates).

**Affects**

- [ ] Designer
- [ ] Blocks editor
- [ ] Companion
- [ ] Compiled apps
- [ ] Buildserver
- [ ] Debugging
- [X] Components

### PR DESCRIPTION
**Pull request by BeksOmega**
### Description

Closes #2291 

### Testing

No hardware available for testing as yet, b/c covid. Requires a Lego Ev3 Gyro sensor to test.

### Additional Info

@ewpatton  I assume I don't need to bump the component version for this? But if I do  I'm happy to =)

### CODE REVIEW

**Comment by ewpatton** [comment]
@BeksOmega Correct, no need to bump the version numbers because the user-facing API hasn't changed.

**Comment by ewpatton** [comment]
@BeksOmega I'm going to mark this on hold for now until we can get our hands on an Ev3 from the lab.

**Review by ewpatton — CHANGES_REQUESTED** [review]
@BeksOmega I haven't been able to get my hands on a gyro sensor yet (apparently it is not included in the main kit), but looking at this I think it's correct *except* that you should reset the value after the argument check and if the value is actually different. This way we don't invalidate the state if nothing is going to change.

**Comment by BeksOmega** [comment]
@ewpatton I changed it so that the previousValue is only reset if the mode actually switched. Build succeeded & tests pass.

**Comment by ewpatton** [comment]
Thanks @BeksOmega. I've put in an order for a gyro sensor and I will be able to hopefully test this on Monday once it comes in. I think the logic is good though.

**Comment by ewpatton** [comment]
This worked fine for me on the gyro. I pushed a small code style fix and once Jenkins finishes I'll squash and merge.

**Review by ewpatton — APPROVED** [review]

**Pull request merged**
