### PR TITLE
Implement the ImageBot component

### PR DESCRIPTION
**Pull request by ewpatton**
Change-Id: I17d277de54a7fef1e22d2ac40486af65f5f5df9c

### CODE REVIEW

**Comment by mark-friedman** [comment]
Why not use the same proxying mechanism as the ChatBox component?  It seems strange that they should use different approaches.

**Comment by ewpatton** [comment]
We can always move to the proxy method eventually. This is the version that is currently deployed on the DALL-E test server I set up.

**Comment by mark-friedman** [comment]
> We can always move to the proxy method eventually. This is the version that is currently deployed on the DALL-E test server I set up.

Sure.  I just know how the best laid plans can get indefinitely postponed ;-). Plus, it would just be nice for developers to have a single model for how this type of thing should be done.  I also imagine that the proxy method makes creating the iOS versions of these components easier.

**Comment by jisqyv** [comment]
@ewpatton Let's see if we can get the proxy to handle this, next week.

**Comment by jisqyv** [comment]
@ewpatton This code doesn't compile, you need to add httpcore to the class path for components.

```diff
From 948d85609de949bf7c012613de97b63a5ef32425 Mon Sep 17 00:00:00 2001
From: "Jeffrey I. Schiller" <jis@mit.edu>
Date: Wed, 7 Jun 2023 13:33:15 -0400
Subject: [PATCH] Add httpcore jar file

Change-Id: I49c05536d3be45d02b954f18e04447e58233eb2f
---
 appinventor/components/build.xml | 1 +
 1 file changed, 1 insertion(+)

diff --git a/appinventor/components/build.xml b/appinventor/components/build.xml
index 2370de6dc9..9f44db2698 100644
--- a/appinventor/components/build.xml
+++ b/appinventor/components/build.xml
@@ -139,6 +139,7 @@
     <copy toFile="${public.deps.dir}/acra-4.4.0.jar" file="${lib.dir}/acra/acra-4.4.0.jar" />
     <copy toFile="${public.deps.dir}/twitter4j.jar" file="${lib.dir}/twitter/twitter4j-core-3.0.5.jar" />
     <copy toFile="${public.deps.dir}/twitter4jmedia.jar" file="${lib.dir}/twitter/twitter4j-media-support-3.0.5.jar" />
+    <copy toFile="${public.deps.dir}/httpcore.jar" file="${lib.dir}/apache-http/httpcore-4.3.2.jar" />
     <copy toFile="${public.deps.dir}/httpmime.jar" file="${lib.dir}/apache-http/httpmime-4.3.4.jar" />
     <copy toFile="${public.deps.dir}/fusiontables.jar" file="${lib.dir}/fusiontables/fusiontables.jar" />
     <copy toFile="${public.deps.dir}/firebase.jar" file="${lib.dir}/firebase/firebase-client-android-2.5.0.jar" />
-- 
2.17.1
```

**Comment by jisqyv** [comment]
@ewpatton Note: The above will likely be moot when I add the proxy.

**Pull request closed without merging**
