### PR TITLE
Fixes problems with sizes of elements in API Level 4 changes

### PR DESCRIPTION
**Pull request by josmas**
- Some fields such as radius or lineWidth need density corrections when returned
  - Width and Height for Form need to be corrected for density when returned

@jisqyv @afmckinney @halatmit

### CODE REVIEW

**Comment by halatmit** [comment]
@josmas @jisqyv @afmckinney 
What is the current status on this, and on API Level 4 in general?  Should this pull request still be open?  Is it subsume by what jeff is working on?

**Comment by jisqyv** [comment]
@halatmit @afmckinney @josmas I believe this is included in the code I am working on. But I am not sure. The code I am working on is in my fork in the api4jis branch if you want to look at it.

**Comment by jisqyv** [comment]
This PR has been overtaken by events (or code :-) ).

**Comment by halatmit** [comment]
:)

thanks for closing it


== Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.
MIT Media Lab, Second Class Faculty

**Pull request closed without merging**
