### PR TITLE
First Step and Using the Website CSS for documentation

### PR DESCRIPTION
**Pull request by jisqyv**
Change-Id: I050c7538a7f522e53855e6c32e2f704393c02eb0

### CODE REVIEW

**Comment by SusanRatiLane** [comment]
@jisqyv I don't see the Codi logo in the top left of the title bar. 

Looks like the image link is http://jis.qyv.net/sites/all/themes/appinventor/logo.png

**Comment by jisqyv** [comment]
@SusanRatiLane Ooops. Good catch! I'll fix

**Comment by ewpatton** [comment]
I think we should keep a local copy just in case. Odds are that path on the website won't exist a few months from now.

**Comment by jisqyv** [comment]
@ewpatton I'm with Evan, I'm about to push up another commit with the local copy.

**Comment by jisqyv** [comment]
@SusanRatiLane @ewpatton I put in the Favicon. I also fixed the page titles.

**Comment by ewpatton** [comment]
So taking a step back I realized we already have the favicon in appengine/war. Is there any reason to keep the icon for the documentation separate from the service? In theory we could just remove the link tag and the browser will look for /favicon.ico on the server by default.

**Comment by ColinTree** [comment]
Just curious how you add file [`vjs.eot?`](https://github.com/mit-cml/appinventor-sources/pull/1601/commits/821be059b39771927e19b718e206ecb77240dca2#diff-5985a34a70269dd8f38c0b5c80098f11) into index..

**Comment by ewpatton** [comment]
@ColinTree I believe that file was introduced due to a minor bug. This change is based on a crawl of our website to generate the template for the documentation. The inclusion of the ? in the filename is due to how the URLs were formatted so it was really part of the query string. On •nix systems, ? is a valid filename character, but not on Windows, so that is how it got in there.

**Comment by ColinTree** [comment]
@ewpatton I see, Thanks

**Pull request merged**
