### PR TITLE
Update ftc branch with release nb146i commits.

### PR DESCRIPTION
**Pull request by lizlooney**
Fix to Russian Translation
This fix will cause the “List” drawer in the blocks editor to work
properly in Russian.

Change-Id: Ia1ea9633575003b0710e2bf8addbaed1568cfedc

@jisqyv

### CODE REVIEW

**Comment by jisqyv** [comment]
@lizlooney I'm going to do this merge after one more change hits master and master is released.

**Comment by lizlooney** [comment]
Sounds great. Thanks!

**Comment by afmckinney** [comment]
This should be ready to go now have reviewed PR's that this is waiting on.

**Comment by lizlooney** [comment]
Jeff,
Can you update the ftc branch to include the commits in master that have been released?
Thanks,
Liz

**Comment by jisqyv** [comment]
I'll take care of it tomorrow morning.

-Jeff

**Comment by jisqyv** [comment]
@lizlooney I've merged the current master into the ftc branch

**Pull request merged**
