### PR TITLE
Remove unused context constructor param

### PR DESCRIPTION
**Pull request by pavi2410**

### CODE REVIEW

**Comment by AppInventorWorkerBee** [comment]
Can one of the admins verify this patch?

**Comment by pavi2410** [comment]
@AppInventorWorkerBee ok to test

**Comment by pavi2410** [comment]
@AppInventorWorkerBee push to production

**Comment by ewpatton** [comment]
@AppInventorWorkerBee ok to test

**Comment by ewpatton** [comment]
@pavi2410 While this technically affects the companion (and therefore should go on `ucr`), it doesn't affect any user-facing APIs so we'll allow it on `master`.

**Pull request merged**
