### PR TITLE
Hard reset confirmation button should be "Reset"-Resolved

### PR DESCRIPTION
**Pull request by dhruvpatidar359**
Fixes #1228 , this PR has added translation in proper manner , also including the translation for polisky.
Thus changes the ok - reset in all cases except the korean one.

In this the cancel,ok,factory_reset text is also changed for polisky.

### CODE REVIEW

**Comment by AppInventorWorkerBee** [comment]
Can one of the admins verify this patch?

**Comment by dhruvpatidar359** [comment]
@ewpatton sir ,may you please review this pr

**Comment by SusanRatiLane** [comment]
> @ewpatton sir ,may you please review this pr

We're a small team and very busy, so we're not always able to review as quickly as 5 days.

**Comment by SusanRatiLane** [comment]
@ewpatton Since this is an update to @conorshipp's 2019 PR, I assume they should share authorship of this PR. Is there a preferred process for that?

**Comment by dhruvpatidar359** [comment]
> > @ewpatton sir ,may you please review this pr
> 
> We're a small team and very busy, so we're not always able to review as quickly as 5 days.

I apologise for the haste. I'll look after it.

**Comment by dhruvpatidar359** [comment]
> @ewpatton Since this is an update to @conorshipp's 2019 PR, I assume they should share authorship of this PR. Is there a preferred process for that?

Hello @SusanRatiLane  we can do something like this 
image

**Review by SusanRatiLane — APPROVED** [review]
LGTM.

**Review by SusanRatiLane — CHANGES_REQUESTED** [review]
The change is fine, but it looks like you're submitting all your PRs from the same branch (master). This makes the change log difficult to read because it contains the history for changes you submitted in other PRs.

You really should create a new branch from our master with its own name for each change. That way the history will only contain the changes specific to this PR.

**Review by dhruvpatidar359 — COMMENTED** [review]
created a new branch , gave a reference for it in this PR

**Comment by SusanRatiLane** [comment]
> created a new branch , gave a reference for it in this PR

Great. I merged that PR, and I am closing this one.

**Pull request closed without merging**
