### PR TITLE
Include if-else and if-elseif-else mutations in blocks drawer

### LINKED ISSUE #1975: Include if-else and if-elseif-else mutations in blocks drawer
**Describe the desired feature**

We should add if-else and if-elseif-else block mutations in the blocks drawer as using the mutator on the if block is not obvious. This is particular true of the if-else block because people often (wrongly) identify the if-then-else ternary block as the if-else block and wonder why it has a plug rather than statement notches.

**Give an example of how this feature would be used**

People could drag out if-else and if-elseif-else blocks without needing to use the mutator, making the branching more discoverable than it currently is.

**Why doesn't the current App Inventor system address this use case?**

The current system only includes the if block with mutator. Getting more complicated branch statements requires first understanding the mutator (which is not particularly intuitive).

**Why is this feature beneficial to App Inventor's educational mission?**

This feature makes mutated variations of the if block more readily accessible to new users without forcing a discussion of mutators onto the critical path when they're just getting started programming.

### PR DESCRIPTION
**Pull request by conorshipp**
Resolves #1975

### CODE REVIEW

**Comment by AppInventorWorkerBee** [comment]
Can one of the admins verify this patch?

**Comment by conorshipp** [comment]
@ewpatton does this require bumping `BLOCKS_LANGUAGE_VERSION`?

**Comment by ewpatton** [comment]
@conorshipp In this case it does not require bumping the version number because the semantics of the blocks language are exactly the same. We are just exposing existing options that would normally be reached by other means.

**Comment by ewpatton** [comment]
@AppInventorWorkerBee ok to test

**Comment by jisqyv** [comment]
@stezelMIT @ewpatton I have put this change up on ai2-test

**Comment by stezelMIT** [comment]
Sorry I must have missed this earlier.  Thank you Jeff S. for bringing to my attention.  I personally like the three options.  I am wondering if for the first two (if then, if then else) there should be the little blue gear.  Probably they should have it. In terms of the curriculum, I don't remember where we would have triple if then else if then else, but this comes to the bigger question about what to do about the curriculum every time we have revision to App Inventor components etc.  Major changes will probably mean re-writing/re-imaging the curriculum.  @kdclang Karen any thoughts?

**Comment by kdclang** [comment]
The order of blocks looks good to me.

**Comment by ewpatton** [comment]
@stezelMIT @kdclang Thanks for the feedback. I think we can go ahead and merge this as the discussion about handling curriculum screenshots is a larger challenge to be addressed.

**Pull request merged**
