### PR TITLE
Newpr577

### PR DESCRIPTION
**Pull request by jisqyv**
Updates #577 To add a dialog box for the documentation instead of an Alert window.

### CODE REVIEW

**Comment by jisqyv** [comment]
@afmckinney @ram8647 @halatmit This code builds on top of (and replaces) #577 I'm going to close #577.

**Comment by jisqyv** [comment]
@afmckinney @halatmit Note: If you are happy with this code, just give it an LGTM. I'm going to do some git hackery on gerrit to make this change be two commits. The first being the refactoring of Blockly.ReplMgr.Dialog to Blockly.Util.Dialog and the second being Ralph's right click documentation, updated to use the Dialog instead of an alert window.

**Comment by halatmit** [comment]
LGTM

**Comment by jisqyv** [comment]
MERGED

**Pull request closed without merging**
